// deno-lint-ignore-file no-explicit-any
// This file was auto-generated by @brad-jones/open-api-client

import { type OpenAPIClientConfig, openAPIFetch, type OpenAPIResponses } from "@brad-jones/deno-net-open-api-client";
import { z } from "@zod/zod";

/**
 * API Client class with path-based access to all operations.
 * All methods are inline within the class.
 */
export class ApiClient {
  constructor(private readonly config: OpenAPIClientConfig) {}

  readonly "/foo/{bar}" = {
    get: (request: {
      path: {
        bar: string;
      };
    }): Promise<
      OpenAPIResponses<{
        200: {
          body: {
            message: string;
          };
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/foo/{bar}",
          method: "get",
          requestSchema: z.object({
            path: z.object({
              bar: z.string(),
            }),
          }),
          responseSchema: {
            200: z.object({
              body: z.object({
                message: z.string(),
              }).strict(),
            }),
          },
        },
        request,
      ) as any,
  };
}
