# The Conventional Commits toolbox
# see: https://github.com/cocogitto/cocogitto

tag_prefix = "v"
branch_whitelist = ["master"]
from_latest_tag = true

pre_package_bump_hooks = [
  "task package COG_VERSION_TAG={{package}}-v{{version}} COG_VERSION={{version}} COG_PACKAGE_NAME={{package}}",
]

post_package_bump_hooks = [
  "task publish COG_VERSION_TAG={{package}}-v{{version}} COG_VERSION={{version}} COG_PACKAGE_NAME={{package}}",
]

[commit_types]
build = { bump_patch = true }
ci = { bump_patch = true }
revert = { bump_patch = true }
docs = { bump_patch = true }
test = { bump_patch = true }
style = { bump_patch = true }
chore = { bump_patch = true }
perf = { bump_patch = true }

# Create a CHANGELOG that includes helpful links to github diffs / commits / PRs, etc.
[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
owner = "brad-jones"
repository = "deno.net"
authors = [
  { signature = "Brad Jones", username = "brad-jones" },
]

[packages]

[packages.container]
path = "packages/container"
include = ["packages/container/**"]

[packages.app-builder]
path = "packages/app-builder"
include = ["packages/app-builder/**"]

[packages.problem-details]
path = "packages/problem-details"
include = ["packages/problem-details/**"]

[packages.logging]
path = "packages/logging"
include = ["packages/logging/**"]
