import { outdent } from "@cspotcode/outdent";
import { BaseClientGenerator } from "./base_generator.ts";
import type { TypeScriptTypeGenerator, ZodSchemaGenerator } from "./schema/mod.ts";
import type { OpenAPISpec } from "./types/mod.ts";

/**
 * Generates a classical object-oriented TypeScript API client from OpenAPI specifications.
 *
 * This generator creates a client class with a path-based structure where each API endpoint
 * is represented as a nested property on the client instance. Methods for each HTTP operation
 * (GET, POST, PUT, DELETE, etc.) are inlined within path objects, providing a clean and
 * intuitive API surface.
 *
 * The generated client structure follows this pattern:
 * ```ts
 * const client = new ApiClient(config);
 * await client["/users/{id}"].get({ path: { id: 123 } });
 * await client["/users"].post({ body: userData });
 * ```
 *
 * Features:
 * - Path-based access to all API operations
 * - Inline method definitions with full type safety
 * - Automatic type inference for request and response types
 * - Optional Zod validation for requests and responses
 * - JSDoc comments from OpenAPI descriptions
 * - Sorted paths and methods for consistent output
 *
 * @example
 * ```ts
 * import { ClassicalClientGenerator } from "./classical_client_generator.ts";
 *
 * const generator = new ClassicalClientGenerator({
 *   validateRequests: true,
 *   validateResponses: true
 * });
 *
 * // Generate from URL
 * await generator.generateFromUrl(
 *   "https://petstore3.swagger.io/api/v3/openapi.json",
 *   "./src/petstore-client.ts"
 * );
 *
 * // Use the generated client
 * import { ApiClient } from "./src/petstore-client.ts";
 *
 * const client = new ApiClient({
 *   baseUrl: "https://petstore3.swagger.io/api/v3"
 * });
 *
 * // Make a request - returns a response object with status, headers, body, and raw
 * const response = await client["/pet/{petId}"].get({
 *   path: { petId: 1 }
 * });
 *
 * // TypeScript narrows the body type based on status code
 * if (response.status === 200) {
 *   // response.body is typed as Pet
 *   console.log(response.body.name);
 *   console.log(response.body.status);
 * } else if (response.status === 404) {
 *   // response.body is typed as Error
 *   console.error(response.body.message);
 * }
 * ```
 */
export class ClassicalClientGenerator extends BaseClientGenerator {
  protected generateClient(spec: OpenAPISpec): string {
    const { code: componentSchemas, typeGen, zodGen } = this
      .generateComponentSchemas(
        spec.components?.schemas,
      );

    return outdent`
      // deno-lint-ignore-file no-explicit-any
      // This file was auto-generated by @brad-jones/open-api-client

      ${this.generateImports()}

      ${componentSchemas}
      ${this.generateApiClientClass(spec, typeGen, zodGen)}
    `;
  }

  private generateImports(): string {
    const imports: string[] = [];

    // Add Zod import if validation is enabled
    if (this.options?.validateRequests || this.options?.validateResponses) {
      imports.push(`import { z } from "${this.zodImport}";`);
    }

    // Add core imports
    imports.push(outdent`
      import {
        openAPIFetch,
        type OpenAPIClientConfig,
        type OpenAPIResponses
      } from "${this.clientImport}";
    `);

    return imports.join("\n");
  }

  private generateApiClientClass(
    spec: OpenAPISpec,
    typeGen: TypeScriptTypeGenerator,
    schemaGen: ZodSchemaGenerator,
  ): string {
    const parts: string[] = [];

    // Class header
    parts.push("/**");
    parts.push(" * API Client class with path-based access to all operations.");
    parts.push(" * All methods are inline within the class.");
    parts.push(" */");
    parts.push("export class ApiClient {");
    parts.push(
      "  constructor(private readonly config: OpenAPIClientConfig) {}",
    );
    parts.push("");

    // Sort paths for consistent output
    const pathsArray = Object.entries(spec.paths).sort(([a], [b]) => a.localeCompare(b));

    // Generate path objects with inline methods
    for (const [path, pathItem] of pathsArray) {
      parts.push(`  readonly "${path}" = {`);

      const methods = [
        "get",
        "post",
        "put",
        "delete",
        "patch",
        "head",
        "options",
        "trace",
      ] as const;
      const methodOrder = [
        "get",
        "post",
        "put",
        "patch",
        "delete",
        "head",
        "options",
        "trace",
      ];

      // Collect methods and sort them
      const methodsToGenerate: Array<
        { method: string; operation: Record<string, unknown> }
      > = [];
      for (const method of methods) {
        const operation = pathItem[method];
        if (!operation) continue;
        methodsToGenerate.push({ method, operation });
      }

      // Sort methods by standard HTTP order
      methodsToGenerate.sort((a, b) => methodOrder.indexOf(a.method) - methodOrder.indexOf(b.method));

      // Generate each method inline
      for (let i = 0; i < methodsToGenerate.length; i++) {
        const { method, operation } = methodsToGenerate[i];
        const isLast = i === methodsToGenerate.length - 1;

        try {
          const methodCode = this.generateInlineMethod(
            typeGen,
            schemaGen,
            path,
            method,
            operation,
            pathItem,
            spec.components,
            isLast,
          );
          parts.push(methodCode);
        } catch (error) {
          console.error(
            `Error generating method ${method.toUpperCase()} ${path}: ${error}`,
          );
        }
      }

      parts.push("  };");
      parts.push("");
    }

    parts.push("}");

    return parts.join("\n");
  }

  private generateInlineMethod(
    typeGen: TypeScriptTypeGenerator,
    schemaGen: ZodSchemaGenerator,
    path: string,
    method: string,
    operation: Record<string, unknown>,
    pathItem: Record<string, unknown>,
    components?: Record<string, unknown>,
    isLast: boolean = false,
  ): string {
    const parts: string[] = [];

    // Add JSDoc comment if operation has summary or description
    const jsdoc = this.generateOperationJSDoc(operation);
    if (jsdoc) {
      // Indent JSDoc for method inside object
      parts.push(jsdoc.split("\n").map((line) => `    ${line}`).join("\n"));
    }

    // Generate method signature with inline types
    const { signature, hasRequest } = this.generateMethodSignature(
      typeGen,
      path,
      method,
      operation,
      pathItem,
      components,
    );

    parts.push(`    ${signature}`);

    // Generate method body
    const body = this.generateMethodBody(
      schemaGen,
      path,
      method,
      operation,
      pathItem,
      hasRequest,
      components,
    );
    parts.push(body);

    // Add comma unless it's the last method
    if (!isLast) {
      parts.push(",");
    }

    return parts.join("\n");
  }

  private generateMethodSignature(
    typeGen: TypeScriptTypeGenerator,
    path: string,
    method: string,
    operation: Record<string, unknown>,
    pathItem: Record<string, unknown>,
    components?: Record<string, unknown>,
  ): { signature: string; hasRequest: boolean } {
    const { hasRequest, requestType } = this.buildRequestSignature(
      typeGen,
      path,
      method,
      operation,
      pathItem,
      components,
    );

    // Generate inline response type
    const responseType = this.generateResponseTypeInline(operation, typeGen);

    // Build method signature
    const params: string[] = [];
    if (hasRequest) {
      params.push(requestType);
    }

    const signature = params.length > 0
      ? `${method}: (${params.join(", ")}): Promise<OpenAPIResponses<${responseType}>> =>`
      : `${method}: (): Promise<OpenAPIResponses<${responseType}>> =>`;

    return { signature, hasRequest };
  }

  private generateMethodBody(
    schemaGen: ZodSchemaGenerator,
    path: string,
    method: string,
    operation: Record<string, unknown>,
    pathItem: Record<string, unknown>,
    hasRequest: boolean,
    components?: Record<string, unknown>,
  ): string {
    const parts: string[] = [];

    // Generate metadata object
    const metadata = this.generateOperationMetadata(
      schemaGen,
      path,
      method,
      operation,
      pathItem,
      components,
    );

    parts.push("openAPIFetch(");
    parts.push("this.config");
    parts.push(",");
    parts.push(metadata);

    // Add request parameter if needed
    if (hasRequest) {
      parts.push(",");
      parts.push("request");
    }

    parts.push(") as any");

    return parts.join("\n");
  }
}
