// deno-lint-ignore-file no-explicit-any
// This file was auto-generated by @brad-jones/open-api-client

import {
  type OpenAPIClientConfig,
  openAPIFetch,
  type OpenAPIResponsePromise,
  type OpenAPIResponses,
} from "jsr:@brad-jones/deno-net-open-api-client@0.2.4";
import { z } from "npm:zod@^4.1.12";

/** Data transfer object for public create usage end point */
export type CreateUsageRecord = {
  /**
   * The initial quantity for the usage record. Must be a whole number that is greater than or equal to 0
   *
   * @format int32
   */
  quantity: number;
  /**
   * DateTime in UTC of when the the product was consumed/used
   *
   * @format date-time
   */
  timestamp: string;
};

export type Price = {
  /**
   * The net (before tax) amount.
   *
   * @format double
   */
  amount: number;
  /** The currency of the price. */
  currency: string;
  /**
   * The unique identifier of the price.
   *
   * @format uuid
   */
  id: string;
};

export type ProblemDetails = {
  detail?: string;
  extensions?: Record<string, never>;
  instance?: string;
  status?: number;
  title?: string;
  type?: string;
};

export type Product = unknown;

export type SubscriptionItem = {
  /**
   * Date when the subscription to this product will end
   *
   * @format date-time
   */
  endDate?: string;
  /**
   * The unique identifier of the subscription item.
   *
   * @format uuid
   */
  id: string;
  price: Price;
  product: Product;
  /** The quantity of the item. For a fixed product, it is 1. For a per-seat product, it is a positive integer. For metered products, it is always null. */
  quantity?: number;
  /**
   * Date the subscription started, or will start. Note: this could be in
   * the future for downgrades or reduced number of seats that haven't taken effect yet.
   *
   * @format date-time
   */
  startDate: string;
  status: "ACTIVE" | "CANCELED" | "PENDING_ACTIVATION";
  /** If the subscription is a test subscription */
  testMode?: boolean;
};

export type Plan = {
  /**
   * The unique identifier of the plan
   *
   * @format uuid
   */
  id: string;
  /**
   * The name of the plan. It is used in the invoice line item
   * description.
   */
  name: string;
  status: "ACTIVE" | "CANCELED" | "PENDING_ACTIVATION";
  /**
   * List of the subscription items belonging to the plan. It does not
   * include cancelled subscription items.
   */
  subscriptionItems: SubscriptionItem[];
};

export type Subscription = {
  /**
   * End of the current period that the subscription has been invoiced for.
   *
   * @format date-time
   */
  currentPeriodEnd: string;
  /**
   * If the subscription has been canceled, this is the date when the subscription ends. If null, the subscription is active and has not been cancelled
   *
   * @format date-time
   */
  endDate?: string;
  /**
   * The unique identifier of the subscription
   *
   * @format uuid
   */
  id: string;
  /**
   * The Xero generated unique identifier for the organisation
   *
   * @format uuid
   */
  organisationId: string;
  /** List of plans for the subscription. */
  plans: Plan[];
  /**
   * Date when the subscription was first created.
   *
   * @format date-time
   */
  startDate: string;
  status: "ACTIVE" | "CANCELED" | "PAST_DUE";
  /** Boolean used to indicate if the subscription is in test mode */
  testMode?: boolean;
};

/** Data transfer object for public update usage end point */
export type UpdateUsageRecord = {
  /**
   * The new quantity for the usage record. Must be a whole number that is greater than or equal to 0
   *
   * @format int32
   */
  quantity: number;
};

export type UsageRecord = {
  /**
   * The quantity recorded
   *
   * @format int32
   */
  quantity: number;
  /**
   * The unique identifier of the Subscription.
   *
   * @format guid
   */
  subscriptionId: string;
  /**
   * The unique identifier of the SubscriptionItem.
   *
   * @format guid
   */
  subscriptionItemId: string;
  /** If the subscription is a test subscription */
  testMode: boolean;
  /**
   * The time when this usage was recorded in UTC
   *
   * @format date-time
   */
  recordedAt: string;
  /**
   * The unique identifier of the usageRecord.
   *
   * @format guid
   */
  usageRecordId: string;
  /**
   * The price per unit
   *
   * @format decimal
   */
  pricePerUnit: number;
  /**
   * The unique identifier of the linked Product
   *
   * @format guid
   */
  productId: string;
};

/** Response to get usage record */
export type UsageRecordsList = {
  /** A collection of usage records */
  usageRecords: UsageRecord[];
};

export const CreateUsageRecordSchema: z.ZodType<CreateUsageRecord> = z.object({
  quantity: z.number().int(),
  timestamp: z.string(),
});

export const PriceSchema: z.ZodType<Price> = z.object({
  amount: z.number(),
  currency: z.string(),
  id: z.string(),
});

export const ProblemDetailsSchema: z.ZodType<ProblemDetails> = z.object({
  detail: z.string().optional(),
  extensions: z.object({}).optional(),
  instance: z.string().optional(),
  status: z.number().int().optional(),
  title: z.string().optional(),
  type: z.string().optional(),
});

export const ProductSchema: z.ZodType<Product> = z.unknown();

export const SubscriptionItemSchema: z.ZodType<SubscriptionItem> = z.object({
  endDate: z.string().optional(),
  id: z.string(),
  price: PriceSchema,
  product: ProductSchema,
  quantity: z.number().int().optional(),
  startDate: z.string(),
  status: z.enum(["ACTIVE", "CANCELED", "PENDING_ACTIVATION"]),
  testMode: z.boolean().optional(),
});

export const PlanSchema: z.ZodType<Plan> = z.object({
  id: z.string(),
  name: z.string(),
  status: z.enum(["ACTIVE", "CANCELED", "PENDING_ACTIVATION"]),
  subscriptionItems: z.array(SubscriptionItemSchema),
});

export const SubscriptionSchema: z.ZodType<Subscription> = z.object({
  currentPeriodEnd: z.string(),
  endDate: z.string().optional(),
  id: z.string(),
  organisationId: z.string(),
  plans: z.array(PlanSchema),
  startDate: z.string(),
  status: z.enum(["ACTIVE", "CANCELED", "PAST_DUE"]),
  testMode: z.boolean().optional(),
});

export const UpdateUsageRecordSchema: z.ZodType<UpdateUsageRecord> = z.object({
  quantity: z.number().int(),
});

export const UsageRecordSchema: z.ZodType<UsageRecord> = z.object({
  quantity: z.number().int(),
  subscriptionId: z.string(),
  subscriptionItemId: z.string(),
  testMode: z.boolean(),
  recordedAt: z.string(),
  usageRecordId: z.string(),
  pricePerUnit: z.number(),
  productId: z.string(),
});

export const UsageRecordsListSchema: z.ZodType<UsageRecordsList> = z.object({
  usageRecords: z.array(UsageRecordSchema),
});

/**
 * API Client class with path-based access to all operations.
 * All methods are inline within the class.
 */
export class ApiClient {
  constructor(private readonly config: OpenAPIClientConfig) {}

  readonly "/subscriptions/{subscriptionId}" = {
    /**
     * Retrieves a subscription for a given subscriptionId
     */
    get: (request: {
      path: {
        /** Unique identifier for Subscription object */
        subscriptionId: string;
      };
    }): OpenAPIResponsePromise<
      OpenAPIResponses<{
        /** Success - return response of unique Subscription object */
        200: {
          body: Subscription;
        };
        /** When a failure occurs in the endpoint */
        404: {
          body: ProblemDetails;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/subscriptions/{subscriptionId}",
          method: "get",
          requestSchema: z.object({
            path: z.object({
              subscriptionId: z.string(),
            }),
          }),
          responseSchema: {
            200: z.object({ body: SubscriptionSchema }),
            404: z.object({ body: ProblemDetailsSchema }),
          },
        },
        request,
      ) as any,
  };

  readonly "/subscriptions/{subscriptionId}/items/{subscriptionItemId}/usage-records" = {
    /**
     * Send metered usage belonging to this subscription and subscription item
     */
    post: (request: {
      path: {
        /** Unique identifier for Subscription object */
        subscriptionId: string;
        /** The unique identifier of the subscriptionItem */
        subscriptionItemId: string;
      };
      headers?: {
        /** This allows you to safely retry requests without the risk of duplicate processing. 128 character max. */
        "Idempotency-Key"?: string;
      };
      body: CreateUsageRecord;
    }): OpenAPIResponsePromise<
      OpenAPIResponses<{
        /** Success - return response of the record submitted */
        200: {
          body: UsageRecord;
        };
        /** When a failure occurs in the endpoint */
        404: {
          body: ProblemDetails;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/subscriptions/{subscriptionId}/items/{subscriptionItemId}/usage-records",
          method: "post",
          requestSchema: z.object({
            path: z.object({
              subscriptionId: z.string(),
              subscriptionItemId: z.string(),
            }),
            headers: z.object({
              "Idempotency-Key": z.string().optional(),
            }).optional(),
            body: CreateUsageRecordSchema,
          }),
          responseSchema: {
            200: z.object({ body: UsageRecordSchema }),
            404: z.object({ body: ProblemDetailsSchema }),
          },
        },
        request,
      ) as any,
  };

  readonly "/subscriptions/{subscriptionId}/items/{subscriptionItemId}/usage-records/{usageRecordId}" = {
    /**
     * Update and existing metered usage belonging to this subscription and subscription item
     */
    put: (request: {
      path: {
        /** Unique identifier for Subscription object */
        subscriptionId: string;
        /** The unique identifier of the subscriptionItem */
        subscriptionItemId: string;
        /** The unique identifier of the usage record */
        usageRecordId: string;
      };
      headers?: {
        /** This allows you to safely retry requests without the risk of duplicate processing. 128 character max. */
        "Idempotency-Key"?: string;
      };
      body: UpdateUsageRecord;
    }): OpenAPIResponsePromise<
      OpenAPIResponses<{
        /** Success - return response of the modified record */
        200: {
          body: UsageRecord;
        };
        /** When a failure occurs in the endpoint */
        404: {
          body: ProblemDetails;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/subscriptions/{subscriptionId}/items/{subscriptionItemId}/usage-records/{usageRecordId}",
          method: "put",
          requestSchema: z.object({
            path: z.object({
              subscriptionId: z.string(),
              subscriptionItemId: z.string(),
              usageRecordId: z.string(),
            }),
            headers: z.object({
              "Idempotency-Key": z.string().optional(),
            }).optional(),
            body: UpdateUsageRecordSchema,
          }),
          responseSchema: {
            200: z.object({ body: UsageRecordSchema }),
            404: z.object({ body: ProblemDetailsSchema }),
          },
        },
        request,
      ) as any,
  };

  readonly "/subscriptions/{subscriptionId}/usage-records" = {
    /**
     * Gets all usage records related to the subscription
     */
    get: (request: {
      path: {
        /** Unique identifier for Subscription object */
        subscriptionId: string;
      };
    }): OpenAPIResponsePromise<
      OpenAPIResponses<{
        /** Success - return a list of all usage record submitted against this subscription for this subscription period */
        200: {
          body: UsageRecordsList;
        };
        /** When a failure occurs in the endpoint */
        404: {
          body: ProblemDetails;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/subscriptions/{subscriptionId}/usage-records",
          method: "get",
          requestSchema: z.object({
            path: z.object({
              subscriptionId: z.string(),
            }),
          }),
          responseSchema: {
            200: z.object({ body: UsageRecordsListSchema }),
            404: z.object({ body: ProblemDetailsSchema }),
          },
        },
        request,
      ) as any,
  };
}
