// deno-lint-ignore-file no-explicit-any
// This file was auto-generated by @brad-jones/open-api-client

import {
  createCustomClient,
  type OpenAPIClientConfig,
  openAPIFetch,
  type OpenAPIResponses,
} from "jsr:@brad-jones/deno-net-open-api-client@0.2.1";
import { z } from "npm:zod@^4.1.12";

export type AssetStatus = "Draft" | "Registered" | "Disposed";

export type AssetStatusQueryParam = "DRAFT" | "REGISTERED" | "DISPOSED";

export type BookDepreciationDetail = unknown;

export type BookDepreciationSetting = unknown;

export type Asset = {
  /**
   * The Xero-generated Id for the asset
   *
   * @format uuid
   */
  assetId?: string;
  /** The name of the asset */
  assetName: string;
  /**
   * The Xero-generated Id for the asset type
   *
   * @format uuid
   */
  assetTypeId?: string;
  /** Must be unique. */
  assetNumber?: string;
  /**
   * The date the asset was purchased YYYY-MM-DD
   *
   * @format date
   */
  purchaseDate?: string;
  /**
   * The purchase price of the asset
   *
   * @format double
   */
  purchasePrice?: number;
  /**
   * The date the asset was disposed
   *
   * @format date
   */
  disposalDate?: string;
  /**
   * The price the asset was disposed at
   *
   * @format double
   */
  disposalPrice?: number;
  assetStatus?: AssetStatus;
  /** The date the asset’s warranty expires (if needed) YYYY-MM-DD */
  warrantyExpiryDate?: string;
  /** The asset's serial number */
  serialNumber?: string;
  bookDepreciationSetting?: BookDepreciationSetting;
  bookDepreciationDetail?: BookDepreciationDetail;
  /** Boolean to indicate whether depreciation can be rolled back for this asset individually. This is true if it doesn't have 'legacy' journal entries and if there is no lock period that would prevent this asset from rolling back. */
  canRollback?: boolean;
  /**
   * The accounting value of the asset
   *
   * @format double
   */
  accountingBookValue?: number;
  /** Boolean to indicate whether delete is enabled */
  isDeleteEnabledForDate?: boolean;
};

export type AssetType = {
  /**
   * Xero generated unique identifier for asset types
   *
   * @format uuid
   */
  assetTypeId?: string;
  /** The name of the asset type */
  assetTypeName: string;
  /**
   * The asset account for fixed assets of this type
   *
   * @format uuid
   */
  fixedAssetAccountId?: string;
  /**
   * The expense account for the depreciation of fixed assets of this type
   *
   * @format uuid
   */
  depreciationExpenseAccountId?: string;
  /**
   * The account for accumulated depreciation of fixed assets of this type
   *
   * @format uuid
   */
  accumulatedDepreciationAccountId?: string;
  bookDepreciationSetting: BookDepreciationSetting;
  /** All asset types that have accumulated depreciation for any assets that use them are deemed ‘locked’ and cannot be removed. */
  locks?: number;
};

export type FieldValidationErrorsElement = {
  /** The field name of the erroneous field */
  fieldName?: string;
  /** The provided value */
  valueProvided?: string;
  /** Explanation of the field validation error */
  localisedMessage?: string;
  /** Internal type of the field validation error message */
  type?: string;
  /** Title of the field validation error */
  title?: string;
  /** Detail of the field validation error */
  detail?: string;
};

export type Pagination = unknown;

export type Assets = {
  pagination?: Pagination;
  items?: Asset[];
};

export type ResourceValidationErrorsElement = {
  /** The field name of the erroneous field */
  resourceName?: string;
  /** Explanation of the resource validation error */
  localisedMessage?: string;
  /** Internal type of the resource error message */
  type?: string;
  /** Title of the resource validation error */
  title?: string;
  /** Detail of the resource validation error */
  detail?: string;
};

export type Error = {
  /** Array of elements of resource validation errors */
  resourceValidationErrors?: ResourceValidationErrorsElement[];
  /** Array of elements of field validation errors */
  fieldValidationErrors?: FieldValidationErrorsElement[];
  /** The internal type of error, not accessible externally */
  type?: string;
  /** Title of the error */
  title?: string;
  /** Detail of the error */
  detail?: string;
};

export type Setting = {
  /** The prefix used for fixed asset numbers (“FA-” by default) */
  assetNumberPrefix?: string;
  /** The next available sequence number */
  assetNumberSequence?: string;
  /**
   * The date depreciation calculations started on registered fixed assets in Xero
   *
   * @format date
   */
  assetStartDate?: string;
  /**
   * The last depreciation date
   *
   * @format date
   */
  lastDepreciationDate?: string;
  /**
   * Default account that gains are posted to
   *
   * @format uuid
   */
  defaultGainOnDisposalAccountId?: string;
  /**
   * Default account that losses are posted to
   *
   * @format uuid
   */
  defaultLossOnDisposalAccountId?: string;
  /**
   * Default account that capital gains are posted to
   *
   * @format uuid
   */
  defaultCapitalGainOnDisposalAccountId?: string;
  /** opt in for tax calculation */
  optInForTax?: boolean;
};

export const AssetStatusSchema: z.ZodType<AssetStatus> = z.enum(["Draft", "Registered", "Disposed"]);

export const AssetStatusQueryParamSchema: z.ZodType<AssetStatusQueryParam> = z.enum([
  "DRAFT",
  "REGISTERED",
  "DISPOSED",
]);

export const BookDepreciationDetailSchema: z.ZodType<BookDepreciationDetail> = z.unknown();

export const BookDepreciationSettingSchema: z.ZodType<BookDepreciationSetting> = z.unknown();

export const AssetSchema: z.ZodType<Asset> = z.object({
  assetId: z.string().optional(),
  assetName: z.string(),
  assetTypeId: z.string().optional(),
  assetNumber: z.string().optional(),
  purchaseDate: z.string().optional(),
  purchasePrice: z.number().optional(),
  disposalDate: z.string().optional(),
  disposalPrice: z.number().optional(),
  assetStatus: AssetStatusSchema.optional(),
  warrantyExpiryDate: z.string().optional(),
  serialNumber: z.string().optional(),
  bookDepreciationSetting: BookDepreciationSettingSchema.optional(),
  bookDepreciationDetail: BookDepreciationDetailSchema.optional(),
  canRollback: z.boolean().optional(),
  accountingBookValue: z.number().optional(),
  isDeleteEnabledForDate: z.boolean().optional(),
});

export const AssetTypeSchema: z.ZodType<AssetType> = z.object({
  assetTypeId: z.string().optional(),
  assetTypeName: z.string(),
  fixedAssetAccountId: z.string().optional(),
  depreciationExpenseAccountId: z.string().optional(),
  accumulatedDepreciationAccountId: z.string().optional(),
  bookDepreciationSetting: BookDepreciationSettingSchema,
  locks: z.number().int().optional(),
});

export const FieldValidationErrorsElementSchema: z.ZodType<FieldValidationErrorsElement> = z.object({
  fieldName: z.string().optional(),
  valueProvided: z.string().optional(),
  localisedMessage: z.string().optional(),
  type: z.string().optional(),
  title: z.string().optional(),
  detail: z.string().optional(),
});

export const PaginationSchema: z.ZodType<Pagination> = z.unknown();

export const AssetsSchema: z.ZodType<Assets> = z.object({
  pagination: PaginationSchema.optional(),
  items: z.array(AssetSchema).optional(),
});

export const ResourceValidationErrorsElementSchema: z.ZodType<ResourceValidationErrorsElement> = z.object({
  resourceName: z.string().optional(),
  localisedMessage: z.string().optional(),
  type: z.string().optional(),
  title: z.string().optional(),
  detail: z.string().optional(),
});

export const ErrorSchema: z.ZodType<Error> = z.object({
  resourceValidationErrors: z.array(ResourceValidationErrorsElementSchema).optional(),
  fieldValidationErrors: z.array(FieldValidationErrorsElementSchema).optional(),
  type: z.string().optional(),
  title: z.string().optional(),
  detail: z.string().optional(),
});

export const SettingSchema: z.ZodType<Setting> = z.object({
  assetNumberPrefix: z.string().optional(),
  assetNumberSequence: z.string().optional(),
  assetStartDate: z.string().optional(),
  lastDepreciationDate: z.string().optional(),
  defaultGainOnDisposalAccountId: z.string().optional(),
  defaultLossOnDisposalAccountId: z.string().optional(),
  defaultCapitalGainOnDisposalAccountId: z.string().optional(),
  optInForTax: z.boolean().optional(),
});

/**
 * searches fixed asset
 *
 * By passing in the appropriate options, you can search for available fixed asset in the system
 */
export const getAssets = (config: OpenAPIClientConfig, request: {
  query: {
    /** Required when retrieving a collection of assets. See Asset Status Codes */
    status: AssetStatusQueryParam;
    /** Results are paged. This specifies which page of the results to return. The default page is 1. */
    page?: number;
    /** The number of records returned per page. By default the number of records returned is 10. */
    pageSize?: number;
    /** Requests can be ordered by AssetType, AssetName, AssetNumber, PurchaseDate and PurchasePrice. If the asset status is DISPOSED it also allows DisposalDate and DisposalPrice. */
    orderBy?:
      | "AssetType"
      | "AssetName"
      | "AssetNumber"
      | "PurchaseDate"
      | "PurchasePrice"
      | "DisposalDate"
      | "DisposalPrice";
    /** ASC or DESC */
    sortDirection?: "asc" | "desc";
    /** A string that can be used to filter the list to only return assets containing the text. Checks it against the AssetName, AssetNumber, Description and AssetTypeName fields. */
    filterBy?: string;
  };
  headers: {
    /** Xero identifier for Tenant */
    "xero-tenant-id": string;
  };
}): Promise<
  OpenAPIResponses<{
    /** search results matching criteria */
    200: {
      body: Assets;
    };
    /** bad input parameter */
    400: {
      body: unknown;
    };
  }>
> =>
  openAPIFetch(
    config,
    {
      path: "/Assets",
      method: "get",
      requestSchema: z.object({
        query: z.object({
          status: AssetStatusQueryParamSchema,
          page: z.number().int().optional(),
          pageSize: z.number().int().optional(),
          orderBy: z.enum([
            "AssetType",
            "AssetName",
            "AssetNumber",
            "PurchaseDate",
            "PurchasePrice",
            "DisposalDate",
            "DisposalPrice",
          ]).optional(),
          sortDirection: z.enum(["asc", "desc"]).optional(),
          filterBy: z.string().optional(),
        }),
        headers: z.object({
          "xero-tenant-id": z.string(),
        }),
      }),
      responseSchema: {
        200: z.object({ body: AssetsSchema }),
        400: z.object({ body: z.unknown() }),
      },
    },
    request,
  ) as any;

/**
 * adds a fixed asset
 *
 * Adds an asset to the system
 */
export const createAsset = (config: OpenAPIClientConfig, request: {
  headers: {
    /** Xero identifier for Tenant */
    "xero-tenant-id": string;
    /** This allows you to safely retry requests without the risk of duplicate processing. 128 character max. */
    "Idempotency-Key"?: string;
  };
  body: Asset;
}): Promise<
  OpenAPIResponses<{
    /** return single object - create new asset */
    200: {
      body: Asset;
    };
    /** invalid input, object invalid */
    400: {
      body: {
        resourceValidationErrors: unknown[];
        fieldValidationErrors: {
          fieldName: string;
          valueProvided: string;
          localisedMessage: string;
          type: string;
          title: string;
          detail: string;
        }[];
        type: string;
        title: string;
        detail: string;
      };
    };
  }>
> =>
  openAPIFetch(
    config,
    {
      path: "/Assets",
      method: "post",
      requestSchema: z.object({
        headers: z.object({
          "xero-tenant-id": z.string(),
          "Idempotency-Key": z.string().optional(),
        }),
        body: AssetSchema,
      }),
      responseSchema: {
        200: z.object({ body: AssetSchema }),
        400: z.object({
          body: z.object({
            resourceValidationErrors: z.array(z.unknown()),
            fieldValidationErrors: z.array(z.object({
              fieldName: z.string(),
              valueProvided: z.string(),
              localisedMessage: z.string(),
              type: z.string(),
              title: z.string(),
              detail: z.string(),
            })),
            type: z.string(),
            title: z.string(),
            detail: z.string(),
          }),
        }),
      },
    },
    request,
  ) as any;

/**
 * Retrieves fixed asset by id
 *
 * By passing in the appropriate asset id, you can search for
 * a specific fixed asset in the system
 */
export const getAssetById = (config: OpenAPIClientConfig, request: {
  path: {
    /** fixed asset id for single object */
    id: string;
  };
  headers: {
    /** Xero identifier for Tenant */
    "xero-tenant-id": string;
  };
}): Promise<
  OpenAPIResponses<{
    /** search results matching criteria */
    200: {
      body: Asset;
    };
    /** bad input parameter */
    400: {
      body: unknown;
    };
  }>
> =>
  openAPIFetch(
    config,
    {
      path: "/Assets/{id}",
      method: "get",
      requestSchema: z.object({
        path: z.object({
          id: z.string(),
        }),
        headers: z.object({
          "xero-tenant-id": z.string(),
        }),
      }),
      responseSchema: {
        200: z.object({ body: AssetSchema }),
        400: z.object({ body: z.unknown() }),
      },
    },
    request,
  ) as any;

/**
 * searches fixed asset types
 *
 * By passing in the appropriate options, you can search for available fixed asset types in the system
 */
export const getAssetTypes = (config: OpenAPIClientConfig, request: {
  headers: {
    /** Xero identifier for Tenant */
    "xero-tenant-id": string;
  };
}): Promise<
  OpenAPIResponses<{
    /** search results matching criteria */
    200: {
      body: AssetType[];
    };
    /** bad input parameter */
    400: {
      body: unknown;
    };
  }>
> =>
  openAPIFetch(
    config,
    {
      path: "/AssetTypes",
      method: "get",
      requestSchema: z.object({
        headers: z.object({
          "xero-tenant-id": z.string(),
        }),
      }),
      responseSchema: {
        200: z.object({ body: z.array(AssetTypeSchema) }),
        400: z.object({ body: z.unknown() }),
      },
    },
    request,
  ) as any;

/**
 * adds a fixed asset type
 *
 * Adds an fixed asset type to the system
 */
export const createAssetType = (config: OpenAPIClientConfig, request: {
  headers: {
    /** Xero identifier for Tenant */
    "xero-tenant-id": string;
    /** This allows you to safely retry requests without the risk of duplicate processing. 128 character max. */
    "Idempotency-Key"?: string;
  };
  body: AssetType;
}): Promise<
  OpenAPIResponses<{
    /** results single object -  created fixed type */
    200: {
      body: AssetType;
    };
    /** invalid input, object invalid */
    400: {
      body: {
        resourceValidationErrors: unknown[];
        fieldValidationErrors: {
          fieldName: string;
          valueProvided: string;
          localisedMessage: string;
          type: string;
          title: string;
          detail: string;
        }[];
        type: string;
        title: string;
        detail: string;
      };
    };
    /** a type already exists */
    409: {
      body: unknown;
    };
  }>
> =>
  openAPIFetch(
    config,
    {
      path: "/AssetTypes",
      method: "post",
      requestSchema: z.object({
        headers: z.object({
          "xero-tenant-id": z.string(),
          "Idempotency-Key": z.string().optional(),
        }),
        body: AssetTypeSchema,
      }),
      responseSchema: {
        200: z.object({ body: AssetTypeSchema }),
        400: z.object({
          body: z.object({
            resourceValidationErrors: z.array(z.unknown()),
            fieldValidationErrors: z.array(z.object({
              fieldName: z.string(),
              valueProvided: z.string(),
              localisedMessage: z.string(),
              type: z.string(),
              title: z.string(),
              detail: z.string(),
            })),
            type: z.string(),
            title: z.string(),
            detail: z.string(),
          }),
        }),
        409: z.object({ body: z.unknown() }),
      },
    },
    request,
  ) as any;

/**
 * searches fixed asset settings
 *
 * By passing in the appropriate options, you can search for available fixed asset types in the system
 */
export const getAssetSettings = (config: OpenAPIClientConfig, request: {
  headers: {
    /** Xero identifier for Tenant */
    "xero-tenant-id": string;
  };
}): Promise<
  OpenAPIResponses<{
    /** search results matching criteria */
    200: {
      body: Setting;
    };
    /** bad input parameter */
    400: {
      body: unknown;
    };
  }>
> =>
  openAPIFetch(
    config,
    {
      path: "/Settings",
      method: "get",
      requestSchema: z.object({
        headers: z.object({
          "xero-tenant-id": z.string(),
        }),
      }),
      responseSchema: {
        200: z.object({ body: SettingSchema }),
        400: z.object({ body: z.unknown() }),
      },
    },
    request,
  ) as any;

export { createCustomClient } from "jsr:@brad-jones/deno-net-open-api-client@0.2.1";

/**
 * Create a client with all available operations.
 * This is convenient but will include all operations in your bundle.
 * For better tree-shaking, use createCustomClient() to select specific operations.
 */
export function createClient(config: OpenAPIClientConfig) {
  return createCustomClient(config, {
    getAssets,
    createAsset,
    getAssetById,
    getAssetTypes,
    createAssetType,
    getAssetSettings,
  });
}
