// deno-lint-ignore-file no-explicit-any
// This file was auto-generated by @brad-jones/open-api-client

import {
  type OpenAPIClientConfig,
  openAPIFetch,
  type OpenAPIResponses,
} from "jsr:@brad-jones/deno-net-open-api-client@0.2.2";
import { z } from "npm:zod@^4.1.12";

export type CountryCode =
  | "AD"
  | "AE"
  | "AF"
  | "AG"
  | "AI"
  | "AL"
  | "AM"
  | "AN"
  | "AO"
  | "AQ"
  | "AR"
  | "AS"
  | "AT"
  | "AU"
  | "AW"
  | "AZ"
  | "BA"
  | "BB"
  | "BD"
  | "BE"
  | "BF"
  | "BG"
  | "BH"
  | "BI"
  | "BJ"
  | "BL"
  | "BM"
  | "BN"
  | "BO"
  | "BR"
  | "BS"
  | "BT"
  | "BW"
  | "BY"
  | "BZ"
  | "CA"
  | "CC"
  | "CD"
  | "CF"
  | "CG"
  | "CH"
  | "CI"
  | "CK"
  | "CL"
  | "CM"
  | "CN"
  | "CO"
  | "CR"
  | "CU"
  | "CV"
  | "CW"
  | "CX"
  | "CY"
  | "CZ"
  | "DE"
  | "DJ"
  | "DK"
  | "DM"
  | "DO"
  | "DZ"
  | "EC"
  | "EE"
  | "EG"
  | "EH"
  | "ER"
  | "ES"
  | "ET"
  | "FI"
  | "FJ"
  | "FK"
  | "FM"
  | "FO"
  | "FR"
  | "GA"
  | "GB"
  | "GD"
  | "GE"
  | "GG"
  | "GH"
  | "GI"
  | "GL"
  | "GM"
  | "GN"
  | "GQ"
  | "GR"
  | "GT"
  | "GU"
  | "GW"
  | "GY"
  | "HK"
  | "HN"
  | "HR"
  | "HT"
  | "HU"
  | "ID"
  | "IE"
  | "IL"
  | "IM"
  | "IN"
  | "IO"
  | "IQ"
  | "IR"
  | "IS"
  | "IT"
  | "JE"
  | "JM"
  | "JO"
  | "JP"
  | "KE"
  | "KG"
  | "KH"
  | "KI"
  | "KM"
  | "KN"
  | "KP"
  | "KR"
  | "KW"
  | "KY"
  | "KZ"
  | "LA"
  | "LB"
  | "LC"
  | "LI"
  | "LK"
  | "LR"
  | "LS"
  | "LT"
  | "LU"
  | "LV"
  | "LY"
  | "MA"
  | "MC"
  | "MD"
  | "ME"
  | "MF"
  | "MG"
  | "MH"
  | "MK"
  | "ML"
  | "MM"
  | "MN"
  | "MO"
  | "MP"
  | "MR"
  | "MS"
  | "MT"
  | "MU"
  | "MV"
  | "MW"
  | "MX"
  | "MY"
  | "MZ"
  | "NA"
  | "NC"
  | "NE"
  | "NG"
  | "NI"
  | "NL"
  | "NO"
  | "NP"
  | "NR"
  | "NU"
  | "NZ"
  | "OM"
  | "PA"
  | "PE"
  | "PF"
  | "PG"
  | "PH"
  | "PK"
  | "PL"
  | "PM"
  | "PN"
  | "PR"
  | "PS"
  | "PT"
  | "PW"
  | "PY"
  | "QA"
  | "RE"
  | "RO"
  | "RS"
  | "RU"
  | "RW"
  | "SA"
  | "SB"
  | "SC"
  | "SD"
  | "SE"
  | "SG"
  | "SH"
  | "SI"
  | "SJ"
  | "SK"
  | "SL"
  | "SM"
  | "SN"
  | "SO"
  | "SR"
  | "SS"
  | "ST"
  | "SV"
  | "SX"
  | "SY"
  | "SZ"
  | "TC"
  | "TD"
  | "TG"
  | "TH"
  | "TJ"
  | "TK"
  | "TL"
  | "TM"
  | "TN"
  | "TO"
  | "TR"
  | "TT"
  | "TV"
  | "TW"
  | "TZ"
  | "UA"
  | "UG"
  | "US"
  | "UY"
  | "UZ"
  | "VA"
  | "VC"
  | "VE"
  | "VG"
  | "VI"
  | "VN"
  | "VU"
  | "WF"
  | "WS"
  | "XK"
  | "YE"
  | "YT"
  | "ZA"
  | "ZM"
  | "ZW";

export type CreditDebitIndicator = "CREDIT" | "DEBIT";

export type CurrencyCode =
  | "AED"
  | "AFN"
  | "ALL"
  | "AMD"
  | "ANG"
  | "AOA"
  | "ARS"
  | "AUD"
  | "AWG"
  | "AZN"
  | "BAM"
  | "BBD"
  | "BDT"
  | "BGN"
  | "BHD"
  | "BIF"
  | "BMD"
  | "BND"
  | "BOB"
  | "BRL"
  | "BSD"
  | "BTN"
  | "BWP"
  | "BYN"
  | "BZD"
  | "CAD"
  | "CDF"
  | "CHF"
  | "CLP"
  | "CNY"
  | "COP"
  | "CRC"
  | "CUC"
  | "CUP"
  | "CVE"
  | "CZK"
  | "DJF"
  | "DKK"
  | "DOP"
  | "DZD"
  | "EGP"
  | "ERN"
  | "ETB"
  | "EUR"
  | "FJD"
  | "FKP"
  | "GBP"
  | "GEL"
  | "GGP"
  | "GHS"
  | "GIP"
  | "GMD"
  | "GNF"
  | "GTQ"
  | "GYD"
  | "HKD"
  | "HNL"
  | "HRK"
  | "HTG"
  | "HUF"
  | "IDR"
  | "ILS"
  | "IMP"
  | "INR"
  | "IQD"
  | "IRR"
  | "ISK"
  | "JEP"
  | "JMD"
  | "JOD"
  | "JPY"
  | "KES"
  | "KGS"
  | "KHR"
  | "KMF"
  | "KPW"
  | "KRW"
  | "KWD"
  | "KYD"
  | "KZT"
  | "LAK"
  | "LBP"
  | "LKR"
  | "LRD"
  | "LSL"
  | "LYD"
  | "MAD"
  | "MDL"
  | "MGA"
  | "MKD"
  | "MMK"
  | "MNT"
  | "MOP"
  | "MRU"
  | "MUR"
  | "MVR"
  | "MWK"
  | "MXN"
  | "MYR"
  | "MZN"
  | "NAD"
  | "NGN"
  | "NIO"
  | "NOK"
  | "NPR"
  | "NZD"
  | "OMR"
  | "PAB"
  | "PEN"
  | "PGK"
  | "PHP"
  | "PKR"
  | "PLN"
  | "PYG"
  | "QAR"
  | "RON"
  | "RSD"
  | "RUB"
  | "RWF"
  | "SAR"
  | "SBD"
  | "SCR"
  | "SDG"
  | "SEK"
  | "SGD"
  | "SHP"
  | "SLL"
  | "SOS"
  | "SPL"
  | "SRD"
  | "STN"
  | "SVC"
  | "SYP"
  | "SZL"
  | "THB"
  | "TJS"
  | "TMT"
  | "TND"
  | "TOP"
  | "TRY"
  | "TTD"
  | "TVD"
  | "TWD"
  | "TZS"
  | "UAH"
  | "UGX"
  | "USD"
  | "UYU"
  | "UZS"
  | "VEF"
  | "VND"
  | "VUV"
  | "WST"
  | "XAF"
  | "XCD"
  | "XDR"
  | "XOF"
  | "XPF"
  | "YER"
  | "ZAR"
  | "ZMW"
  | "ZMK"
  | "ZWD";

/** The StartBalance plus all the Statement Line Amounts should be equal to the EndBalance Amount. */
export type EndBalance = {
  /** @format double */
  amount?: number;
  creditDebitIndicator?: CreditDebitIndicator;
};

/** On error, the API consumer will receive an HTTP response with a HTTP Status Code of 4xx or 5xx and a Content-Type of application/problem+json. */
export type Error = {
  /** Human readable high level error description. */
  title?: string;
  /** The numeric HTTP Status Code, e.g. 404 */
  status?: number;
  /** Human readable detailed error description. */
  detail?: string;
  type?:
    | "invalid-request"
    | "invalid-application"
    | "invalid-feed-connection"
    | "duplicate-statement"
    | "invalid-end-balance"
    | "invalid-start-and-end-date"
    | "invalid-start-date"
    | "internal-error"
    | "feed-already-connected-in-current-organisation"
    | "invalid-end-date"
    | "statement-not-found"
    | "feed-connected-in-different-organisation"
    | "feed-already-connected-in-different-organisation"
    | "bank-feed-not-found"
    | "invalid-country-specified"
    | "invalid-organisation-bank-feeds"
    | "invalid-organisation-multi-currency"
    | "invalid-feed-connection-for-organisation"
    | "invalid-user-role"
    | "account-not-valid"
    | "feed-not-found-or-already-deleted";
};

export type FeedConnection = {
  /**
   * GUID used to identify the Account.
   *
   * @format uuid
   */
  id?: string;
  /** This account identifier is generated by the financial institute (FI). This must be unique for your financial institute. */
  accountToken?: string;
  /** String(40) when AccountType is BANK String(4) when AccountType is CREDITCARD The Account Number is used to match the feed to a Xero Bank Account. The API will create a new Xero Bank Account if a match to an existing Xero Bank Account is not found. Only the last 4 digits must be supplied for Credit Card numbers. Must be included if AccountId is not specified. */
  accountNumber?: string;
  /** The Account Name will be used for the creation of a new Xero Bank Account if a matching Xero Bank Account is not found. */
  accountName?: string;
  /**
   * Xero identifier for a bank account in Xero. Must be included if AccountNumber is not specified.
   *
   * @format uuid
   */
  accountId?: string;
  accountType?: "BANK" | "CREDITCARD";
  currency?: CurrencyCode;
  country?: CountryCode;
  status?: "PENDING" | "REJECTED";
  error?: Error;
};

export type Pagination = {
  /** Page number which specifies the set of records to retrieve. Example - https://api.xero.com/bankfeeds.xro/1.0/Statements?page=2 to get the second set of the records. When page value is not a number or a negative number, by default, the first set of records is returned. */
  page?: number;
  /** Page size which specifies how many records per page will be returned (default 50). Example - https://api.xero.com/bankfeeds.xro/1.0/Statements?pageSize=100 to specify page size of 100. */
  pageSize?: number;
  /** Number of pages available */
  pageCount?: number;
  /** Number of items returned */
  itemCount?: number;
};

export type FeedConnections = {
  pagination?: Pagination;
  items?: FeedConnection[];
};

/** The starting balance of the statement */
export type StartBalance = {
  /**
   * decimal(19,4) unsigned Opening/closing balance amount.
   *
   * @format double
   */
  amount?: number;
  creditDebitIndicator?: CreditDebitIndicator;
};

/** the lines details for a statement */
export type StatementLine = {
  /**
   * The date that the transaction was processed or cleared as seen in internet banking ISO-8601 YYYY-MM-DD
   *
   * @format date
   */
  postedDate?: string;
  /** Transaction description */
  description?: string;
  /**
   * Transaction amount
   *
   * @format double
   */
  amount?: number;
  creditDebitIndicator?: CreditDebitIndicator;
  /** Financial institute's internal transaction identifier. If provided this field is factored into duplicate detection. */
  transactionId?: string;
  /** Typically the merchant or payee name */
  payeeName?: string;
  /** Optional field to enhance the Description */
  reference?: string;
  /** The cheque/check number */
  chequeNumber?: string;
  /** Descriptive transaction type */
  transactionType?: string;
};

export type StatementLines = StatementLine[];

export type Statement = {
  /**
   * GUID used to identify the Statement.
   *
   * @format uuid
   */
  id?: string;
  /**
   * The Xero generated feed connection Id that identifies the Xero Bank Account Container into which the statement should be delivered. This is obtained by calling GET FeedConnections.
   *
   * @format uuid
   */
  feedConnectionId?: string;
  status?: "PENDING" | "REJECTED" | "DELIVERED";
  /**
   * Opening balance date (can be no older than one year from the current date) ISO-8601 YYYY-MM-DD
   *
   * @format date
   */
  startDate?: string;
  /**
   * Closing balance date ISO-8601 YYYY-MM-DD
   *
   * @format date
   */
  endDate?: string;
  startBalance?: StartBalance;
  endBalance?: EndBalance;
  statementLines?: StatementLines;
  errors?: Error[];
  statementLineCount?: number;
};

export type Statements = {
  pagination?: Pagination;
  items?: Statement[];
};

export const CountryCodeSchema: z.ZodType<CountryCode> = z.enum([
  "AD",
  "AE",
  "AF",
  "AG",
  "AI",
  "AL",
  "AM",
  "AN",
  "AO",
  "AQ",
  "AR",
  "AS",
  "AT",
  "AU",
  "AW",
  "AZ",
  "BA",
  "BB",
  "BD",
  "BE",
  "BF",
  "BG",
  "BH",
  "BI",
  "BJ",
  "BL",
  "BM",
  "BN",
  "BO",
  "BR",
  "BS",
  "BT",
  "BW",
  "BY",
  "BZ",
  "CA",
  "CC",
  "CD",
  "CF",
  "CG",
  "CH",
  "CI",
  "CK",
  "CL",
  "CM",
  "CN",
  "CO",
  "CR",
  "CU",
  "CV",
  "CW",
  "CX",
  "CY",
  "CZ",
  "DE",
  "DJ",
  "DK",
  "DM",
  "DO",
  "DZ",
  "EC",
  "EE",
  "EG",
  "EH",
  "ER",
  "ES",
  "ET",
  "FI",
  "FJ",
  "FK",
  "FM",
  "FO",
  "FR",
  "GA",
  "GB",
  "GD",
  "GE",
  "GG",
  "GH",
  "GI",
  "GL",
  "GM",
  "GN",
  "GQ",
  "GR",
  "GT",
  "GU",
  "GW",
  "GY",
  "HK",
  "HN",
  "HR",
  "HT",
  "HU",
  "ID",
  "IE",
  "IL",
  "IM",
  "IN",
  "IO",
  "IQ",
  "IR",
  "IS",
  "IT",
  "JE",
  "JM",
  "JO",
  "JP",
  "KE",
  "KG",
  "KH",
  "KI",
  "KM",
  "KN",
  "KP",
  "KR",
  "KW",
  "KY",
  "KZ",
  "LA",
  "LB",
  "LC",
  "LI",
  "LK",
  "LR",
  "LS",
  "LT",
  "LU",
  "LV",
  "LY",
  "MA",
  "MC",
  "MD",
  "ME",
  "MF",
  "MG",
  "MH",
  "MK",
  "ML",
  "MM",
  "MN",
  "MO",
  "MP",
  "MR",
  "MS",
  "MT",
  "MU",
  "MV",
  "MW",
  "MX",
  "MY",
  "MZ",
  "NA",
  "NC",
  "NE",
  "NG",
  "NI",
  "NL",
  "NO",
  "NP",
  "NR",
  "NU",
  "NZ",
  "OM",
  "PA",
  "PE",
  "PF",
  "PG",
  "PH",
  "PK",
  "PL",
  "PM",
  "PN",
  "PR",
  "PS",
  "PT",
  "PW",
  "PY",
  "QA",
  "RE",
  "RO",
  "RS",
  "RU",
  "RW",
  "SA",
  "SB",
  "SC",
  "SD",
  "SE",
  "SG",
  "SH",
  "SI",
  "SJ",
  "SK",
  "SL",
  "SM",
  "SN",
  "SO",
  "SR",
  "SS",
  "ST",
  "SV",
  "SX",
  "SY",
  "SZ",
  "TC",
  "TD",
  "TG",
  "TH",
  "TJ",
  "TK",
  "TL",
  "TM",
  "TN",
  "TO",
  "TR",
  "TT",
  "TV",
  "TW",
  "TZ",
  "UA",
  "UG",
  "US",
  "UY",
  "UZ",
  "VA",
  "VC",
  "VE",
  "VG",
  "VI",
  "VN",
  "VU",
  "WF",
  "WS",
  "XK",
  "YE",
  "YT",
  "ZA",
  "ZM",
  "ZW",
]);

export const CreditDebitIndicatorSchema: z.ZodType<CreditDebitIndicator> = z.enum(["CREDIT", "DEBIT"]);

export const CurrencyCodeSchema: z.ZodType<CurrencyCode> = z.enum([
  "AED",
  "AFN",
  "ALL",
  "AMD",
  "ANG",
  "AOA",
  "ARS",
  "AUD",
  "AWG",
  "AZN",
  "BAM",
  "BBD",
  "BDT",
  "BGN",
  "BHD",
  "BIF",
  "BMD",
  "BND",
  "BOB",
  "BRL",
  "BSD",
  "BTN",
  "BWP",
  "BYN",
  "BZD",
  "CAD",
  "CDF",
  "CHF",
  "CLP",
  "CNY",
  "COP",
  "CRC",
  "CUC",
  "CUP",
  "CVE",
  "CZK",
  "DJF",
  "DKK",
  "DOP",
  "DZD",
  "EGP",
  "ERN",
  "ETB",
  "EUR",
  "FJD",
  "FKP",
  "GBP",
  "GEL",
  "GGP",
  "GHS",
  "GIP",
  "GMD",
  "GNF",
  "GTQ",
  "GYD",
  "HKD",
  "HNL",
  "HRK",
  "HTG",
  "HUF",
  "IDR",
  "ILS",
  "IMP",
  "INR",
  "IQD",
  "IRR",
  "ISK",
  "JEP",
  "JMD",
  "JOD",
  "JPY",
  "KES",
  "KGS",
  "KHR",
  "KMF",
  "KPW",
  "KRW",
  "KWD",
  "KYD",
  "KZT",
  "LAK",
  "LBP",
  "LKR",
  "LRD",
  "LSL",
  "LYD",
  "MAD",
  "MDL",
  "MGA",
  "MKD",
  "MMK",
  "MNT",
  "MOP",
  "MRU",
  "MUR",
  "MVR",
  "MWK",
  "MXN",
  "MYR",
  "MZN",
  "NAD",
  "NGN",
  "NIO",
  "NOK",
  "NPR",
  "NZD",
  "OMR",
  "PAB",
  "PEN",
  "PGK",
  "PHP",
  "PKR",
  "PLN",
  "PYG",
  "QAR",
  "RON",
  "RSD",
  "RUB",
  "RWF",
  "SAR",
  "SBD",
  "SCR",
  "SDG",
  "SEK",
  "SGD",
  "SHP",
  "SLL",
  "SOS",
  "SPL",
  "SRD",
  "STN",
  "SVC",
  "SYP",
  "SZL",
  "THB",
  "TJS",
  "TMT",
  "TND",
  "TOP",
  "TRY",
  "TTD",
  "TVD",
  "TWD",
  "TZS",
  "UAH",
  "UGX",
  "USD",
  "UYU",
  "UZS",
  "VEF",
  "VND",
  "VUV",
  "WST",
  "XAF",
  "XCD",
  "XDR",
  "XOF",
  "XPF",
  "YER",
  "ZAR",
  "ZMW",
  "ZMK",
  "ZWD",
]);

export const EndBalanceSchema: z.ZodType<EndBalance> = z.object({
  amount: z.number().optional(),
  creditDebitIndicator: CreditDebitIndicatorSchema.optional(),
});

export const ErrorSchema: z.ZodType<Error> = z.object({
  title: z.string().optional(),
  status: z.number().int().optional(),
  detail: z.string().optional(),
  type: z.enum([
    "invalid-request",
    "invalid-application",
    "invalid-feed-connection",
    "duplicate-statement",
    "invalid-end-balance",
    "invalid-start-and-end-date",
    "invalid-start-date",
    "internal-error",
    "feed-already-connected-in-current-organisation",
    "invalid-end-date",
    "statement-not-found",
    "feed-connected-in-different-organisation",
    "feed-already-connected-in-different-organisation",
    "bank-feed-not-found",
    "invalid-country-specified",
    "invalid-organisation-bank-feeds",
    "invalid-organisation-multi-currency",
    "invalid-feed-connection-for-organisation",
    "invalid-user-role",
    "account-not-valid",
    "feed-not-found-or-already-deleted",
  ]).optional(),
});

export const FeedConnectionSchema: z.ZodType<FeedConnection> = z.object({
  id: z.string().optional(),
  accountToken: z.string().optional(),
  accountNumber: z.string().optional(),
  accountName: z.string().optional(),
  accountId: z.string().optional(),
  accountType: z.enum(["BANK", "CREDITCARD"]).optional(),
  currency: CurrencyCodeSchema.optional(),
  country: CountryCodeSchema.optional(),
  status: z.enum(["PENDING", "REJECTED"]).optional(),
  error: ErrorSchema.optional(),
});

export const PaginationSchema: z.ZodType<Pagination> = z.object({
  page: z.number().int().optional(),
  pageSize: z.number().int().optional(),
  pageCount: z.number().int().optional(),
  itemCount: z.number().int().optional(),
});

export const FeedConnectionsSchema: z.ZodType<FeedConnections> = z.object({
  pagination: PaginationSchema.optional(),
  items: z.array(FeedConnectionSchema).optional(),
});

export const StartBalanceSchema: z.ZodType<StartBalance> = z.object({
  amount: z.number().optional(),
  creditDebitIndicator: CreditDebitIndicatorSchema.optional(),
});

export const StatementLineSchema: z.ZodType<StatementLine> = z.object({
  postedDate: z.string().optional(),
  description: z.string().optional(),
  amount: z.number().optional(),
  creditDebitIndicator: CreditDebitIndicatorSchema.optional(),
  transactionId: z.string().optional(),
  payeeName: z.string().optional(),
  reference: z.string().optional(),
  chequeNumber: z.string().optional(),
  transactionType: z.string().optional(),
});

export const StatementLinesSchema: z.ZodType<StatementLines> = z.array(StatementLineSchema);

export const StatementSchema: z.ZodType<Statement> = z.object({
  id: z.string().optional(),
  feedConnectionId: z.string().optional(),
  status: z.enum(["PENDING", "REJECTED", "DELIVERED"]).optional(),
  startDate: z.string().optional(),
  endDate: z.string().optional(),
  startBalance: StartBalanceSchema.optional(),
  endBalance: EndBalanceSchema.optional(),
  statementLines: StatementLinesSchema.optional(),
  errors: z.array(ErrorSchema).optional(),
  statementLineCount: z.number().int().optional(),
});

export const StatementsSchema: z.ZodType<Statements> = z.object({
  pagination: PaginationSchema.optional(),
  items: z.array(StatementSchema).optional(),
});

/**
 * API Client class with path-based access to all operations.
 * All methods are inline within the class.
 */
export class ApiClient {
  constructor(private readonly config: OpenAPIClientConfig) {}

  readonly "/FeedConnections" = {
    /**
     * Searches for feed connections
     *
     * By passing in the appropriate options, you can search for available feed connections in the system.
     */
    get: (request: {
      query?: {
        /** Page number which specifies the set of records to retrieve. By default the number of the records per set is 10. Example - https://api.xero.com/bankfeeds.xro/1.0/FeedConnections?page=1 to get the second set of the records. When page value is not a number or a negative number, by default, the first set of records is returned. */
        page?: number;
        /** Page size which specifies how many records per page will be returned (default 10). Example - https://api.xero.com/bankfeeds.xro/1.0/FeedConnections?pageSize=100 to specify page size of 100. */
        pageSize?: number;
      };
      headers: {
        /** Xero identifier for Tenant */
        "Xero-Tenant-Id": string;
      };
    }): Promise<
      OpenAPIResponses<{
        /** search results matching criteria returned with pagination and items array */
        202: {
          body: FeedConnections;
        };
        /** validation error response */
        400: {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/FeedConnections",
          method: "get",
          requestSchema: z.object({
            query: z.object({
              page: z.number().int().optional(),
              pageSize: z.number().int().optional(),
            }).optional(),
            headers: z.object({
              "Xero-Tenant-Id": z.string(),
            }),
          }),
          responseSchema: {
            202: z.object({ body: FeedConnectionsSchema }),
            400: z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
    /**
     * Create one or more new feed connection
     *
     * By passing in the FeedConnections array object in the body, you can create one or more new feed connections
     */
    post: (request: {
      headers: {
        /** Xero identifier for Tenant */
        "Xero-Tenant-Id": string;
        /** This allows you to safely retry requests without the risk of duplicate processing. 128 character max. */
        "Idempotency-Key"?: string;
      };
      body: FeedConnections;
    }): Promise<
      OpenAPIResponses<{
        /** success new feed connection(s)response */
        202: {
          body: FeedConnections;
        };
        /** failed to create new feed connection(s)response */
        400: {
          body: FeedConnections;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/FeedConnections",
          method: "post",
          requestSchema: z.object({
            headers: z.object({
              "Xero-Tenant-Id": z.string(),
              "Idempotency-Key": z.string().optional(),
            }),
            body: FeedConnectionsSchema,
          }),
          responseSchema: {
            202: z.object({ body: FeedConnectionsSchema }),
            400: z.object({ body: FeedConnectionsSchema }),
          },
        },
        request,
      ) as any,
  };

  readonly "/FeedConnections/{id}" = {
    /**
     * Retrieve single feed connection based on a unique id provided
     *
     * By passing in a FeedConnection Id options, you can search for matching feed connections
     */
    get: (request: {
      path: {
        /** Unique identifier for retrieving single object */
        id: string;
      };
      headers: {
        /** Xero identifier for Tenant */
        "Xero-Tenant-Id": string;
      };
    }): Promise<
      OpenAPIResponses<{
        /** success returns a FeedConnection object matching the id in response */
        200: {
          body: FeedConnection;
        };
        /** bad input parameter */
        400: {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/FeedConnections/{id}",
          method: "get",
          requestSchema: z.object({
            path: z.object({
              id: z.string(),
            }),
            headers: z.object({
              "Xero-Tenant-Id": z.string(),
            }),
          }),
          responseSchema: {
            200: z.object({ body: FeedConnectionSchema }),
            400: z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };

  readonly "/FeedConnections/DeleteRequests" = {
    /**
     * Delete an existing feed connection
     *
     * By passing in FeedConnections array object in the body, you can delete a feed connection.
     */
    post: (request: {
      headers: {
        /** Xero identifier for Tenant */
        "Xero-Tenant-Id": string;
        /** This allows you to safely retry requests without the risk of duplicate processing. 128 character max. */
        "Idempotency-Key"?: string;
      };
      body: FeedConnections;
    }): Promise<
      OpenAPIResponses<{
        /** Success response for deleted feed connection */
        202: {
          body: FeedConnections;
        };
        /** bad input parameter */
        400: {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/FeedConnections/DeleteRequests",
          method: "post",
          requestSchema: z.object({
            headers: z.object({
              "Xero-Tenant-Id": z.string(),
              "Idempotency-Key": z.string().optional(),
            }),
            body: FeedConnectionsSchema,
          }),
          responseSchema: {
            202: z.object({ body: FeedConnectionsSchema }),
            400: z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };

  readonly "/Statements" = {
    /**
     * Retrieve all statements
     *
     * By passing in parameters, you can search for matching statements
     */
    get: (request: {
      query?: {
        /** unique id for single object */
        page?: number;
        /** Page size which specifies how many records per page will be returned (default 10). Example - https://api.xero.com/bankfeeds.xro/1.0/Statements?pageSize=100 to specify page size of 100. */
        pageSize?: number;
      };
      headers: {
        /** Xero identifier for Tenant */
        "Xero-Tenant-Id": string;
        "Xero-Application-Id"?: string;
        "Xero-User-Id"?: string;
      };
    }): Promise<
      OpenAPIResponses<{
        /** success returns Statements array of objects response */
        200: {
          body: Statements;
        };
        /** bad input parameter */
        400: {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/Statements",
          method: "get",
          requestSchema: z.object({
            query: z.object({
              page: z.number().int().optional(),
              pageSize: z.number().int().optional(),
            }).optional(),
            headers: z.object({
              "Xero-Tenant-Id": z.string(),
              "Xero-Application-Id": z.string().default("00000000-0000-0000-0000-0000000010000").optional(),
              "Xero-User-Id": z.string().default("00000000-0000-0000-0000-0000030000000").optional(),
            }),
          }),
          responseSchema: {
            200: z.object({ body: StatementsSchema }),
            400: z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
    /**
     * Creates one or more new statements
     */
    post: (request: {
      headers: {
        /** Xero identifier for Tenant */
        "Xero-Tenant-Id": string;
        /** This allows you to safely retry requests without the risk of duplicate processing. 128 character max. */
        "Idempotency-Key"?: string;
      };
      body: Statements;
    }): Promise<
      OpenAPIResponses<{
        /** Success returns Statements array of objects in response */
        202: {
          body: Statements;
        };
        /** Statement failed validation */
        400: {
          body: unknown;
        };
        /** Invalid application or feed connection */
        403: {
          body: unknown;
        };
        /** Duplicate statement received */
        409: {
          body: unknown;
        };
        /** Statement exceeds size limit */
        413: {
          body: unknown;
        };
        /** Unprocessable Entity */
        422: {
          body: unknown;
        };
        /** Intermittent Xero Error */
        500: {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/Statements",
          method: "post",
          requestSchema: z.object({
            headers: z.object({
              "Xero-Tenant-Id": z.string(),
              "Idempotency-Key": z.string().optional(),
            }),
            body: StatementsSchema,
          }),
          responseSchema: {
            202: z.object({ body: StatementsSchema }),
            400: z.object({ body: z.unknown() }),
            403: z.object({ body: z.unknown() }),
            409: z.object({ body: z.unknown() }),
            413: z.object({ body: z.unknown() }),
            422: z.object({ body: z.unknown() }),
            500: z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };

  readonly "/Statements/{statementId}" = {
    /**
     * Retrieve single statement based on unique id provided
     *
     * By passing in a statement id, you can search for matching statements
     */
    get: (request: {
      path: {
        /** statement id for single object */
        statementId: string;
      };
      headers: {
        /** Xero identifier for Tenant */
        "Xero-Tenant-Id": string;
      };
    }): Promise<
      OpenAPIResponses<{
        /** search results matching id for single statement */
        200: {
          body: Statement;
        };
        /** Statement not found */
        404: {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/Statements/{statementId}",
          method: "get",
          requestSchema: z.object({
            path: z.object({
              statementId: z.string(),
            }),
            headers: z.object({
              "Xero-Tenant-Id": z.string(),
            }),
          }),
          responseSchema: {
            200: z.object({ body: StatementSchema }),
            404: z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };
}
