// deno-lint-ignore-file no-explicit-any
// This file was auto-generated by @brad-jones/open-api-client

import {
  createCustomClient,
  type OpenAPIClientConfig,
  openAPIFetch,
  type OpenAPIResponses,
} from "jsr:@brad-jones/deno-net-open-api-client@0.2.4";
import { z } from "npm:zod@^4.1.12";

export type AccessToken = {
  /** Xero unique identifier */
  id_token?: string;
  /** access token provided during authentication flow */
  access_token?: string;
  /**
   * time in seconds until access token expires.
   *
   * @format int64
   */
  expires_in?: number;
  /** type of token i.e. Bearer */
  token_type?: string;
  /** token used to refresh an expired access token */
  refresh_token?: string;
};

export type Connection = unknown;

export type RefreshToken = {
  /** Xero grant type */
  grant_type?: string;
  /** refresh token provided during authentication flow */
  refresh_token?: string;
  /** client id for Xero app */
  client_id?: string;
  /** client secret for Xero app 2 */
  client_secret?: string;
};

export const AccessTokenSchema: z.ZodType<AccessToken> = z.object({
  id_token: z.string().optional(),
  access_token: z.string().optional(),
  expires_in: z.number().int().optional(),
  token_type: z.string().optional(),
  refresh_token: z.string().optional(),
});

export const ConnectionSchema: z.ZodType<Connection> = z.unknown();

export const RefreshTokenSchema: z.ZodType<RefreshToken> = z.object({
  grant_type: z.string().optional(),
  refresh_token: z.string().optional(),
  client_id: z.string().optional(),
  client_secret: z.string().optional(),
});

/**
 * Retrieves the connections for this user
 *
 * Override the base server url that include version
 */
export const getConnections = (config: OpenAPIClientConfig, request?: {
  query?: {
    /** Filter by authEventId */
    authEventId?: string;
  };
}): Promise<
  OpenAPIResponses<{
    /** Success - return response of type Connections array with 0 to n Connection */
    200: {
      body: Connection[];
    };
  }>
> =>
  openAPIFetch(
    config,
    {
      path: "/Connections",
      method: "get",
      requestSchema: z.object({
        query: z.object({
          authEventId: z.string().optional(),
        }).optional(),
      }),
      responseSchema: {
        200: z.object({ body: z.array(ConnectionSchema) }),
      },
    },
    request,
  ) as any;

/**
 * Deletes a connection for this user (i.e. disconnect a tenant)
 *
 * Override the base server url that include version
 */
export const deleteConnection = (config: OpenAPIClientConfig, request: {
  path: {
    /** Unique identifier for retrieving single object */
    id: string;
  };
}): Promise<
  OpenAPIResponses<{
    /** Success - connection has been deleted no content returned */
    204: {
      body: unknown;
    };
    /** Resource not found */
    404: {
      body: unknown;
    };
  }>
> =>
  openAPIFetch(
    config,
    {
      path: "/Connections/{id}",
      method: "delete",
      requestSchema: z.object({
        path: z.object({
          id: z.string(),
        }),
      }),
      responseSchema: {
        204: z.object({ body: z.unknown() }),
        404: z.object({ body: z.unknown() }),
      },
    },
    request,
  ) as any;

export { createCustomClient } from "jsr:@brad-jones/deno-net-open-api-client@0.2.4";

/**
 * Create a client with all available operations.
 * This is convenient but will include all operations in your bundle.
 * For better tree-shaking, use createCustomClient() to select specific operations.
 */
export function createClient(config: OpenAPIClientConfig) {
  return createCustomClient(config, { getConnections, deleteConnection });
}
