/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NewLineKind = "auto" | "crlf" | "lf" | "system";
export type NewLineKind1 = string;
export type TextWrap = "always" | "maintain" | "never";
export type TextWrap1 = string;
export type EmphasisKind = "asterisks" | "underscores";
export type EmphasisKind1 = string;
export type StrongKind = "asterisks" | "underscores";
export type StrongKind1 = string;
export type Deno = boolean;
export type Deno1 = true | false;

export interface Schema {
  /**
   * Whether the configuration is not allowed to be overridden or extended.
   */
  locked?: boolean;
  /**
   * The width of a line the printer will try to stay under. Note that the printer may exceed this width in certain cases.
   */
  lineWidth?: number;
  /**
   * The kind of newline to use.
   */
  newLineKind?: NewLineKind & NewLineKind1;
  /**
   * Text wrapping possibilities.
   */
  textWrap?: TextWrap & TextWrap1;
  /**
   * The character to use for emphasis/italics.
   */
  emphasisKind?: EmphasisKind & EmphasisKind1;
  /**
   * The character to use for strong emphasis/bold.
   */
  strongKind?: StrongKind & StrongKind1;
  /**
   * Top level configuration that sets the configuration to what is used in Deno.
   */
  deno?: Deno & Deno1;
  /**
   * The text to use for an ignore directive (ex. `<!-- dprint-ignore -->`).
   */
  ignoreDirective?: string;
  /**
   * The text to use for an ignore file directive (ex. `<!-- dprint-ignore-file -->`).
   */
  ignoreFileDirective?: string;
  /**
   * The text to use for an ignore start directive (ex. `<!-- dprint-ignore-start -->`).
   */
  ignoreStartDirective?: string;
  /**
   * The text to use for an ignore end directive (ex. `<!-- dprint-ignore-end -->`).
   */
  ignoreEndDirective?: string;
}
