# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev
version: 3

dotenv: [".env"]
set: [pipefail]
shopt: [globstar]

tasks:
  run:
    cmds:
      - deno serve -A ./src/main.ts
