# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev
version: 3

dotenv: [".env"]
set: [pipefail]
shopt: [globstar]

tasks:
  build:
    cmds:
      - deno run -A ./src/main.ts

  start:
    cmds:
      - deno serve --host 127.0.0.1 --port 80 -A ./src/main.ts

  watch:
    cmds:
      - deno serve --watch --watch-exclude=deno.json --host 127.0.0.1 --port 80 -A ./src/main.ts
