// deno-lint-ignore-file no-explicit-any
// This file was auto-generated by @brad-jones/open-api-client

import {
  type OpenAPIClientConfig,
  openAPIFetch,
  type OpenAPIResponsePromise,
  type OpenAPIResponses,
} from "jsr:@brad-jones/deno-net-open-api-client@0.3.1";
import { z } from "npm:zod@^4.1.12";

export type _400 = unknown;

export type _401 = unknown;

export type _403 = unknown;

export type _404 = unknown;

export type _422 = unknown;

/**
 * The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional.<blockquote><strong>Note:</strong> The regular expression provides guidance but does not reject all invalid dates.</blockquote>
 *
 * @format ppaas_date_time_v3
 */
export type DateTime = string;

/** The request-related [HATEOAS link](/api/rest/responses/#hateoas-links) information. */
export type ErrorLinkDescription = {
  /** The complete target URL. To make the related call, combine the method with this [URI Template-formatted](https://tools.ietf.org/html/rfc6570) link. For pre-processing, include the `$`, `(`, and `)` characters. The `href` is the key HATEOAS component that links a completed call with a subsequent call. */
  href: string;
  /** The [link relation type](https://tools.ietf.org/html/rfc5988#section-4), which serves as an ID for a link that unambiguously describes the semantics of the link. See [Link Relations](https://www.iana.org/assignments/link-relations/link-relations.xhtml). */
  rel: string;
  method?: "GET" | "POST" | "PUT" | "DELETE" | "PATCH";
};

/** This is either a system or application error, and generally indicates that although the client appeared to provide a correct request, something unexpected has gone wrong on the server. */
export type Error500 = {
  name?: "INTERNAL_SERVER_ERROR";
  message?: "An internal server error occurred.";
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** The server is temporarily unable to handle the request, for example, because of planned maintenance or downtime. */
export type Error503 = {
  name?: "SERVICE_UNAVAILABLE";
  message?: "Service Unavailable.";
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

export type ErrorLocation = "body" | "path" | "query";

/** The error details. Required for client-side `4XX` errors. */
export type ErrorDetails = {
  /** The field that caused the error. If this field is in the body, set this value to the field's JSON pointer value. Required for client-side errors. */
  field?: string;
  /** The value of the field that caused the error. */
  value?: string;
  location?: ErrorLocation;
  /** The unique, fine-grained application-level error code. */
  issue: string;
  /** The human-readable description for an issue. The description can change over the lifetime of an API, so clients must not depend on this value. */
  description?: string;
};

/** Request is not well-formed, syntactically incorrect, or violates schema. */
export type Error400 = {
  name?: "INVALID_REQUEST";
  message?: "Request is not well-formed, syntactically incorrect, or violates schema.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** Authentication failed due to missing Authorization header, or invalid authentication credentials. */
export type Error401 = {
  name?: "AUTHENTICATION_FAILURE";
  message?: "Authentication failed due to missing authorization header, or invalid authentication credentials.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** The client is not authorized to access this resource, although it may have valid credentials.  */
export type Error403 = {
  name?: "NOT_AUTHORIZED";
  message?: "Authorization failed due to insufficient permissions.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** The server has not found anything matching the request URI. This either means that the URI is incorrect or the resource is not available. */
export type Error404 = {
  name?: "RESOURCE_NOT_FOUND";
  message?: "The specified resource does not exist.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** The server has detected a conflict while processing this request. */
export type Error409 = {
  name?: "RESOURCE_CONFLICT";
  message?: "The server has detected a conflict while processing this request.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** The server does not support the request payload's media type. */
export type Error415 = {
  name?: "UNSUPPORTED_MEDIA_TYPE";
  message?: "The server does not support the request payload's media type.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** The requested action cannot be performed and may require interaction with APIs or processes outside of the current request. This is distinct from a 500 response in that there are no systemic problems limiting the API from performing the request. */
export type Error422 = {
  name?: "UNPROCESSABLE_ENTITY";
  message?: "The requested action could not be performed, semantically incorrect, or failed business validation.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

export type ErrorDefault =
  | Error400
  | Error401
  | Error403
  | Error404
  | Error409
  | Error415
  | Error422
  | Error500
  | Error503;

/** The request-related [HATEOAS link](/docs/api/reference/api-responses/#hateoas-links) information. */
export type LinkDescription = {
  /** The complete target URL. To make the related call, combine the method with this [URI Template-formatted](https://tools.ietf.org/html/rfc6570) link. For pre-processing, include the `$`, `(`, and `)` characters. The `href` is the key HATEOAS component that links a completed call with a subsequent call. */
  href: string;
  /** The [link relation type](https://tools.ietf.org/html/rfc5988#section-4), which serves as an ID for a link that unambiguously describes the semantics of the link. See [Link Relations](https://www.iana.org/assignments/link-relations/link-relations.xhtml). */
  rel: string;
  method?: "GET" | "POST" | "PUT" | "DELETE" | "HEAD" | "CONNECT" | "OPTIONS" | "PATCH";
};

/** An array of request-related [HATEOAS links](/docs/api/overview/#hateoas-links). */
export type LinkDescriptionList = LinkDescription[];

/** The JSON patch object to apply partial updates to resources. */
export type Patch = {
  op: "add" | "remove" | "replace" | "move" | "copy" | "test";
  /** The <a href="https://tools.ietf.org/html/rfc6901">JSON Pointer</a> to the target document location at which to complete the operation. */
  path?: string;
  /** The value to apply. The <code>remove</code> operation does not require a value. */
  value?:
    | number
    | /** The value to apply. The <code>remove</code> operation does not require a value. */ number
    | /** The value to apply. The <code>remove</code> operation does not require a value. */ string
    | /** The value to apply. The <code>remove</code> operation does not require a value. */ boolean
    | /** The value to apply. The <code>remove</code> operation does not require a value. */ null
    | /** The value to apply. The <code>remove</code> operation does not require a value. */ unknown[]
    | /** The value to apply. The <code>remove</code> operation does not require a value. */ Record<string, never>;
  /** The <a href="https://tools.ietf.org/html/rfc6901">JSON Pointer</a> to the target document location from which to move the value. Required for the <code>move</code> operation. */
  from?: string;
};

/** An array of JSON patch objects to apply partial updates to resources. */
export type PatchRequest = Patch[];

export type ProductCategory =
  | "AC_REFRIGERATION_REPAIR"
  | "ACADEMIC_SOFTWARE"
  | "ACCESSORIES"
  | "ACCOUNTING"
  | "ADULT"
  | "ADVERTISING"
  | "AFFILIATED_AUTO_RENTAL"
  | "AGENCIES"
  | "AGGREGATORS"
  | "AGRICULTURAL_COOPERATIVE_FOR_MAIL_ORDER"
  | "AIR_CARRIERS_AIRLINES"
  | "AIRLINES"
  | "AIRPORTS_FLYING_FIELDS"
  | "ALCOHOLIC_BEVERAGES"
  | "AMUSEMENT_PARKS_CARNIVALS"
  | "ANIMATION"
  | "ANTIQUES"
  | "APPLIANCES"
  | "AQUARIAMS_SEAQUARIUMS_DOLPHINARIUMS"
  | "ARCHITECTURAL_ENGINEERING_AND_SURVEYING_SERVICES"
  | "ART_AND_CRAFT_SUPPLIES"
  | "ART_DEALERS_AND_GALLERIES"
  | "ARTIFACTS_GRAVE_RELATED_AND_NATIVE_AMERICAN_CRAFTS"
  | "ARTS_AND_CRAFTS"
  | "ARTS_CRAFTS_AND_COLLECTIBLES"
  | "AUDIO_BOOKS"
  | "AUTO_ASSOCIATIONS_CLUBS"
  | "AUTO_DEALER_USED_ONLY"
  | "AUTO_RENTALS"
  | "AUTO_SERVICE"
  | "AUTOMATED_FUEL_DISPENSERS"
  | "AUTOMOBILE_ASSOCIATIONS"
  | "AUTOMOTIVE"
  | "AUTOMOTIVE_REPAIR_SHOPS_NON_DEALER"
  | "AUTOMOTIVE_TOP_AND_BODY_SHOPS"
  | "AVIATION"
  | "BABIES_CLOTHING_AND_SUPPLIES"
  | "BABY"
  | "BANDS_ORCHESTRAS_ENTERTAINERS"
  | "BARBIES"
  | "BATH_AND_BODY"
  | "BATTERIES"
  | "BEAN_BABIES"
  | "BEAUTY"
  | "BEAUTY_AND_FRAGRANCES"
  | "BED_AND_BATH"
  | "BICYCLE_SHOPS_SALES_AND_SERVICE"
  | "BICYCLES_AND_ACCESSORIES"
  | "BILLIARD_POOL_ESTABLISHMENTS"
  | "BOAT_DEALERS"
  | "BOAT_RENTALS_AND_LEASING"
  | "BOATING_SAILING_AND_ACCESSORIES"
  | "BOOKS"
  | "BOOKS_AND_MAGAZINES"
  | "BOOKS_MANUSCRIPTS"
  | "BOOKS_PERIODICALS_AND_NEWSPAPERS"
  | "BOWLING_ALLEYS"
  | "BULLETIN_BOARD"
  | "BUS_LINE"
  | "BUS_LINES_CHARTERS_TOUR_BUSES"
  | "BUSINESS"
  | "BUSINESS_AND_SECRETARIAL_SCHOOLS"
  | "BUYING_AND_SHOPPING_SERVICES_AND_CLUBS"
  | "CABLE_SATELLITE_AND_OTHER_PAY_TELEVISION_AND_RADIO_SERVICES"
  | "CABLE_SATELLITE_AND_OTHER_PAY_TV_AND_RADIO"
  | "CAMERA_AND_PHOTOGRAPHIC_SUPPLIES"
  | "CAMERAS"
  | "CAMERAS_AND_PHOTOGRAPHY"
  | "CAMPER_RECREATIONAL_AND_UTILITY_TRAILER_DEALERS"
  | "CAMPING_AND_OUTDOORS"
  | "CAMPING_AND_SURVIVAL"
  | "CAR_AND_TRUCK_DEALERS"
  | "CAR_AND_TRUCK_DEALERS_USED_ONLY"
  | "CAR_AUDIO_AND_ELECTRONICS"
  | "CAR_RENTAL_AGENCY"
  | "CATALOG_MERCHANT"
  | "CATALOG_RETAIL_MERCHANT"
  | "CATERING_SERVICES"
  | "CHARITY"
  | "CHECK_CASHIER"
  | "CHILD_CARE_SERVICES"
  | "CHILDREN_BOOKS"
  | "CHIROPODISTS_PODIATRISTS"
  | "CHIROPRACTORS"
  | "CIGAR_STORES_AND_STANDS"
  | "CIVIC_SOCIAL_FRATERNAL_ASSOCIATIONS"
  | "CIVIL_SOCIAL_FRAT_ASSOCIATIONS"
  | "CLOTHING"
  | "CLOTHING_ACCESSORIES_AND_SHOES"
  | "CLOTHING_RENTAL"
  | "COFFEE_AND_TEA"
  | "COIN_OPERATED_BANKS_AND_CASINOS"
  | "COLLECTIBLES"
  | "COLLECTION_AGENCY"
  | "COLLEGES_AND_UNIVERSITIES"
  | "COMMERCIAL_EQUIPMENT"
  | "COMMERCIAL_FOOTWEAR"
  | "COMMERCIAL_PHOTOGRAPHY"
  | "COMMERCIAL_PHOTOGRAPHY_ART_AND_GRAPHICS"
  | "COMMERCIAL_SPORTS_PROFESSIONA"
  | "COMMODITIES_AND_FUTURES_EXCHANGE"
  | "COMPUTER_AND_DATA_PROCESSING_SERVICES"
  | "COMPUTER_HARDWARE_AND_SOFTWARE"
  | "COMPUTER_MAINTENANCE_REPAIR_AND_SERVICES_NOT_ELSEWHERE_CLAS"
  | "CONSTRUCTION"
  | "CONSTRUCTION_MATERIALS_NOT_ELSEWHERE_CLASSIFIED"
  | "CONSULTING_SERVICES"
  | "CONSUMER_CREDIT_REPORTING_AGENCIES"
  | "CONVALESCENT_HOMES"
  | "COSMETIC_STORES"
  | "COUNSELING_SERVICES_DEBT_MARRIAGE_PERSONAL"
  | "COUNTERFEIT_CURRENCY_AND_STAMPS"
  | "COUNTERFEIT_ITEMS"
  | "COUNTRY_CLUBS"
  | "COURIER_SERVICES"
  | "COURIER_SERVICES_AIR_AND_GROUND_AND_FREIGHT_FORWARDERS"
  | "COURT_COSTS_ALIMNY_CHILD_SUPT"
  | "COURT_COSTS_INCLUDING_ALIMONY_AND_CHILD_SUPPORT_COURTS_OF_LAW"
  | "CREDIT_CARDS"
  | "CREDIT_UNION"
  | "CULTURE_AND_RELIGION"
  | "DAIRY_PRODUCTS_STORES"
  | "DANCE_HALLS_STUDIOS_AND_SCHOOLS"
  | "DECORATIVE"
  | "DENTAL"
  | "DENTISTS_AND_ORTHODONTISTS"
  | "DEPARTMENT_STORES"
  | "DESKTOP_PCS"
  | "DEVICES"
  | "DIECAST_TOYS_VEHICLES"
  | "DIGITAL_GAMES"
  | "DIGITAL_MEDIA_BOOKS_MOVIES_MUSIC"
  | "DIRECT_MARKETING"
  | "DIRECT_MARKETING_CATALOG_MERCHANT"
  | "DIRECT_MARKETING_INBOUND_TELE"
  | "DIRECT_MARKETING_OUTBOUND_TELE"
  | "DIRECT_MARKETING_SUBSCRIPTION"
  | "DISCOUNT_STORES"
  | "DOOR_TO_DOOR_SALES"
  | "DRAPERY_WINDOW_COVERING_AND_UPHOLSTERY"
  | "DRINKING_PLACES"
  | "DRUGSTORE"
  | "DURABLE_GOODS"
  | "ECOMMERCE_DEVELOPMENT"
  | "ECOMMERCE_SERVICES"
  | "EDUCATIONAL_AND_TEXTBOOKS"
  | "ELECTRIC_RAZOR_STORES"
  | "ELECTRICAL_AND_SMALL_APPLIANCE_REPAIR"
  | "ELECTRICAL_CONTRACTORS"
  | "ELECTRICAL_PARTS_AND_EQUIPMENT"
  | "ELECTRONIC_CASH"
  | "ELEMENTARY_AND_SECONDARY_SCHOOLS"
  | "EMPLOYMENT"
  | "ENTERTAINERS"
  | "ENTERTAINMENT_AND_MEDIA"
  | "EQUIP_TOOL_FURNITURE_AND_APPLIANCE_RENTAL_AND_LEASING"
  | "ESCROW"
  | "EVENT_AND_WEDDING_PLANNING"
  | "EXERCISE_AND_FITNESS"
  | "EXERCISE_EQUIPMENT"
  | "EXTERMINATING_AND_DISINFECTING_SERVICES"
  | "FABRICS_AND_SEWING"
  | "FAMILY_CLOTHING_STORES"
  | "FASHION_JEWELRY"
  | "FAST_FOOD_RESTAURANTS"
  | "FICTION_AND_NONFICTION"
  | "FINANCE_COMPANY"
  | "FINANCIAL_AND_INVESTMENT_ADVICE"
  | "FINANCIAL_INSTITUTIONS_MERCHANDISE_AND_SERVICES"
  | "FIREARM_ACCESSORIES"
  | "FIREARMS_WEAPONS_AND_KNIVES"
  | "FIREPLACE_AND_FIREPLACE_SCREENS"
  | "FIREWORKS"
  | "FISHING"
  | "FLORISTS"
  | "FLOWERS"
  | "FOOD_DRINK_AND_NUTRITION"
  | "FOOD_PRODUCTS"
  | "FOOD_RETAIL_AND_SERVICE"
  | "FRAGRANCES_AND_PERFUMES"
  | "FREEZER_AND_LOCKER_MEAT_PROVISIONERS"
  | "FUEL_DEALERS_FUEL_OIL_WOOD_AND_COAL"
  | "FUEL_DEALERS_NON_AUTOMOTIVE"
  | "FUNERAL_SERVICES_AND_CREMATORIES"
  | "FURNISHING_AND_DECORATING"
  | "FURNITURE"
  | "FURRIERS_AND_FUR_SHOPS"
  | "GADGETS_AND_OTHER_ELECTRONICS"
  | "GAMBLING"
  | "GAME_SOFTWARE"
  | "GAMES"
  | "GARDEN_SUPPLIES"
  | "GENERAL"
  | "GENERAL_CONTRACTORS"
  | "GENERAL_GOVERNMENT"
  | "GENERAL_SOFTWARE"
  | "GENERAL_TELECOM"
  | "GIFTS_AND_FLOWERS"
  | "GLASS_PAINT_AND_WALLPAPER_STORES"
  | "GLASSWARE_CRYSTAL_STORES"
  | "GOVERNMENT"
  | "GOVERNMENT_IDS_AND_LICENSES"
  | "GOVERNMENT_LICENSED_ON_LINE_CASINOS_ON_LINE_GAMBLING"
  | "GOVERNMENT_OWNED_LOTTERIES"
  | "GOVERNMENT_SERVICES"
  | "GRAPHIC_AND_COMMERCIAL_DESIGN"
  | "GREETING_CARDS"
  | "GROCERY_STORES_AND_SUPERMARKETS"
  | "HARDWARE_AND_TOOLS"
  | "HARDWARE_EQUIPMENT_AND_SUPPLIES"
  | "HAZARDOUS_RESTRICTED_AND_PERISHABLE_ITEMS"
  | "HEALTH_AND_BEAUTY_SPAS"
  | "HEALTH_AND_NUTRITION"
  | "HEALTH_AND_PERSONAL_CARE"
  | "HEARING_AIDS_SALES_AND_SUPPLIES"
  | "HEATING_PLUMBING_AC"
  | "HIGH_RISK_MERCHANT"
  | "HIRING_SERVICES"
  | "HOBBIES_TOYS_AND_GAMES"
  | "HOME_AND_GARDEN"
  | "HOME_AUDIO"
  | "HOME_DECOR"
  | "HOME_ELECTRONICS"
  | "HOSPITALS"
  | "HOTELS_MOTELS_INNS_RESORTS"
  | "HOUSEWARES"
  | "HUMAN_PARTS_AND_REMAINS"
  | "HUMOROUS_GIFTS_AND_NOVELTIES"
  | "HUNTING"
  | "IDS_LICENSES_AND_PASSPORTS"
  | "ILLEGAL_DRUGS_AND_PARAPHERNALIA"
  | "INDUSTRIAL"
  | "INDUSTRIAL_AND_MANUFACTURING_SUPPLIES"
  | "INSURANCE_AUTO_AND_HOME"
  | "INSURANCE_DIRECT"
  | "INSURANCE_LIFE_AND_ANNUITY"
  | "INSURANCE_SALES_UNDERWRITING"
  | "INSURANCE_UNDERWRITING_PREMIUMS"
  | "INTERNET_AND_NETWORK_SERVICES"
  | "INTRA_COMPANY_PURCHASES"
  | "LABORATORIES_DENTAL_MEDICAL"
  | "LANDSCAPING"
  | "LANDSCAPING_AND_HORTICULTURAL_SERVICES"
  | "LAUNDRY_CLEANING_SERVICES"
  | "LEGAL"
  | "LEGAL_SERVICES_AND_ATTORNEYS"
  | "LOCAL_DELIVERY_SERVICE"
  | "LOCKSMITH"
  | "LODGING_AND_ACCOMMODATIONS"
  | "LOTTERY_AND_CONTESTS"
  | "LUGGAGE_AND_LEATHER_GOODS"
  | "LUMBER_AND_BUILDING_MATERIALS"
  | "MAGAZINES"
  | "MAINTENANCE_AND_REPAIR_SERVICES"
  | "MAKEUP_AND_COSMETICS"
  | "MANUAL_CASH_DISBURSEMENTS"
  | "MASSAGE_PARLORS"
  | "MEDICAL"
  | "MEDICAL_AND_PHARMACEUTICAL"
  | "MEDICAL_CARE"
  | "MEDICAL_EQUIPMENT_AND_SUPPLIES"
  | "MEDICAL_SERVICES"
  | "MEETING_PLANNERS"
  | "MEMBERSHIP_CLUBS_AND_ORGANIZATIONS"
  | "MEMBERSHIP_COUNTRY_CLUBS_GOLF"
  | "MEMORABILIA"
  | "MEN_AND_BOY_CLOTHING_AND_ACCESSORY_STORES"
  | "MEN_CLOTHING"
  | "MERCHANDISE"
  | "METAPHYSICAL"
  | "MILITARIA"
  | "MILITARY_AND_CIVIL_SERVICE_UNIFORMS"
  | "MISC._AUTOMOTIVE_AIRCRAFT_AND_FARM_EQUIPMENT_DEALERS"
  | "MISC._GENERAL_MERCHANDISE"
  | "MISCELLANEOUS_GENERAL_SERVICES"
  | "MISCELLANEOUS_REPAIR_SHOPS_AND_RELATED_SERVICES"
  | "MODEL_KITS"
  | "MONEY_TRANSFER_MEMBER_FINANCIAL_INSTITUTION"
  | "MONEY_TRANSFER_MERCHANT"
  | "MOTION_PICTURE_THEATERS"
  | "MOTOR_FREIGHT_CARRIERS_AND_TRUCKING"
  | "MOTOR_HOME_AND_RECREATIONAL_VEHICLE_RENTAL"
  | "MOTOR_HOMES_DEALERS"
  | "MOTOR_VEHICLE_SUPPLIES_AND_NEW_PARTS"
  | "MOTORCYCLE_DEALERS"
  | "MOTORCYCLES"
  | "MOVIE"
  | "MOVIE_TICKETS"
  | "MOVING_AND_STORAGE"
  | "MULTI_LEVEL_MARKETING"
  | "MUSIC_CDS_CASSETTES_AND_ALBUMS"
  | "MUSIC_STORE_INSTRUMENTS_AND_SHEET_MUSIC"
  | "NETWORKING"
  | "NEW_AGE"
  | "NEW_PARTS_AND_SUPPLIES_MOTOR_VEHICLE"
  | "NEWS_DEALERS_AND_NEWSTANDS"
  | "NON_DURABLE_GOODS"
  | "NON_FICTION"
  | "NON_PROFIT_POLITICAL_AND_RELIGION"
  | "NONPROFIT"
  | "NOVELTIES"
  | "OEM_SOFTWARE"
  | "OFFICE_SUPPLIES_AND_EQUIPMENT"
  | "ONLINE_DATING"
  | "ONLINE_GAMING"
  | "ONLINE_GAMING_CURRENCY"
  | "ONLINE_SERVICES"
  | "OOUTBOUND_TELEMARKETING_MERCH"
  | "OPHTHALMOLOGISTS_OPTOMETRIST"
  | "OPTICIANS_AND_DISPENSING"
  | "ORTHOPEDIC_GOODS_PROSTHETICS"
  | "OSTEOPATHS"
  | "OTHER"
  | "PACKAGE_TOUR_OPERATORS"
  | "PAINTBALL"
  | "PAINTS_VARNISHES_AND_SUPPLIES"
  | "PARKING_LOTS_AND_GARAGES"
  | "PARTS_AND_ACCESSORIES"
  | "PAWN_SHOPS"
  | "PAYCHECK_LENDER_OR_CASH_ADVANCE"
  | "PERIPHERALS"
  | "PERSONALIZED_GIFTS"
  | "PET_SHOPS_PET_FOOD_AND_SUPPLIES"
  | "PETROLEUM_AND_PETROLEUM_PRODUCTS"
  | "PETS_AND_ANIMALS"
  | "PHOTOFINISHING_LABORATORIES_PHOTO_DEVELOPING"
  | "PHOTOGRAPHIC_STUDIOS_PORTRAITS"
  | "PHOTOGRAPHY"
  | "PHYSICAL_GOOD"
  | "PICTURE_VIDEO_PRODUCTION"
  | "PIECE_GOODS_NOTIONS_AND_OTHER_DRY_GOODS"
  | "PLANTS_AND_SEEDS"
  | "PLUMBING_AND_HEATING_EQUIPMENTS_AND_SUPPLIES"
  | "POLICE_RELATED_ITEMS"
  | "POLITICAL_ORGANIZATIONS"
  | "POSTAL_SERVICES_GOVERNMENT_ONLY"
  | "POSTERS"
  | "PREPAID_AND_STORED_VALUE_CARDS"
  | "PRESCRIPTION_DRUGS"
  | "PROMOTIONAL_ITEMS"
  | "PUBLIC_WAREHOUSING_AND_STORAGE"
  | "PUBLISHING_AND_PRINTING"
  | "PUBLISHING_SERVICES"
  | "RADAR_DECTORS"
  | "RADIO_TELEVISION_AND_STEREO_REPAIR"
  | "REAL_ESTATE"
  | "REAL_ESTATE_AGENT"
  | "REAL_ESTATE_AGENTS_AND_MANAGERS_RENTALS"
  | "RELIGION_AND_SPIRITUALITY_FOR_PROFIT"
  | "RELIGIOUS"
  | "RELIGIOUS_ORGANIZATIONS"
  | "REMITTANCE"
  | "RENTAL_PROPERTY_MANAGEMENT"
  | "RESIDENTIAL"
  | "RETAIL"
  | "RETAIL_FINE_JEWELRY_AND_WATCHES"
  | "REUPHOLSTERY_AND_FURNITURE_REPAIR"
  | "RINGS"
  | "ROOFING_SIDING_SHEET_METAL"
  | "RUGS_AND_CARPETS"
  | "SCHOOLS_AND_COLLEGES"
  | "SCIENCE_FICTION"
  | "SCRAPBOOKING"
  | "SCULPTURES"
  | "SECURITIES_BROKERS_AND_DEALERS"
  | "SECURITY_AND_SURVEILLANCE"
  | "SECURITY_AND_SURVEILLANCE_EQUIPMENT"
  | "SECURITY_BROKERS_AND_DEALERS"
  | "SEMINARS"
  | "SERVICE_STATIONS"
  | "SERVICES"
  | "SEWING_NEEDLEWORK_FABRIC_AND_PIECE_GOODS_STORES"
  | "SHIPPING_AND_PACKING"
  | "SHOE_REPAIR_HAT_CLEANING"
  | "SHOE_STORES"
  | "SHOES"
  | "SNOWMOBILE_DEALERS"
  | "SOFTWARE"
  | "SPECIALTY_AND_MISC._FOOD_STORES"
  | "SPECIALTY_CLEANING_POLISHING_AND_SANITATION_PREPARATIONS"
  | "SPECIALTY_OR_RARE_PETS"
  | "SPORT_GAMES_AND_TOYS"
  | "SPORTING_AND_RECREATIONAL_CAMPS"
  | "SPORTING_GOODS"
  | "SPORTS_AND_OUTDOORS"
  | "SPORTS_AND_RECREATION"
  | "STAMP_AND_COIN"
  | "STATIONARY_PRINTING_AND_WRITING_PAPER"
  | "STENOGRAPHIC_AND_SECRETARIAL_SUPPORT_SERVICES"
  | "STOCKS_BONDS_SECURITIES_AND_RELATED_CERTIFICATES"
  | "STORED_VALUE_CARDS"
  | "SUPPLIES"
  | "SUPPLIES_AND_TOYS"
  | "SURVEILLANCE_EQUIPMENT"
  | "SWIMMING_POOLS_AND_SPAS"
  | "SWIMMING_POOLS_SALES_SUPPLIES_SERVICES"
  | "TAILORS_AND_ALTERATIONS"
  | "TAX_PAYMENTS"
  | "TAX_PAYMENTS_GOVERNMENT_AGENCIES"
  | "TAXICABS_AND_LIMOUSINES"
  | "TELECOMMUNICATION_SERVICES"
  | "TELEPHONE_CARDS"
  | "TELEPHONE_EQUIPMENT"
  | "TELEPHONE_SERVICES"
  | "THEATER"
  | "TIRE_RETREADING_AND_REPAIR"
  | "TOLL_OR_BRIDGE_FEES"
  | "TOOLS_AND_EQUIPMENT"
  | "TOURIST_ATTRACTIONS_AND_EXHIBITS"
  | "TOWING_SERVICE"
  | "TOYS_AND_GAMES"
  | "TRADE_AND_VOCATIONAL_SCHOOLS"
  | "TRADEMARK_INFRINGEMENT"
  | "TRAILER_PARKS_AND_CAMPGROUNDS"
  | "TRAINING_SERVICES"
  | "TRANSPORTATION_SERVICES"
  | "TRAVEL"
  | "TRUCK_AND_UTILITY_TRAILER_RENTALS"
  | "TRUCK_STOP"
  | "TYPESETTING_PLATE_MAKING_AND_RELATED_SERVICES"
  | "USED_MERCHANDISE_AND_SECONDHAND_STORES"
  | "USED_PARTS_MOTOR_VEHICLE"
  | "UTILITIES"
  | "UTILITIES_ELECTRIC_GAS_WATER_SANITARY"
  | "VARIETY_STORES"
  | "VEHICLE_SALES"
  | "VEHICLE_SERVICE_AND_ACCESSORIES"
  | "VIDEO_EQUIPMENT"
  | "VIDEO_GAME_ARCADES_ESTABLISH"
  | "VIDEO_GAMES_AND_SYSTEMS"
  | "VIDEO_TAPE_RENTAL_STORES"
  | "VINTAGE_AND_COLLECTIBLE_VEHICLES"
  | "VINTAGE_AND_COLLECTIBLES"
  | "VITAMINS_AND_SUPPLEMENTS"
  | "VOCATIONAL_AND_TRADE_SCHOOLS"
  | "WATCH_CLOCK_AND_JEWELRY_REPAIR"
  | "WEB_HOSTING_AND_DESIGN"
  | "WELDING_REPAIR"
  | "WHOLESALE_CLUBS"
  | "WHOLESALE_FLORIST_SUPPLIERS"
  | "WHOLESALE_PRESCRIPTION_DRUGS"
  | "WILDLIFE_PRODUCTS"
  | "WIRE_TRANSFER"
  | "WIRE_TRANSFER_AND_MONEY_ORDER"
  | "WOMEN_ACCESSORY_SPECIALITY"
  | "WOMEN_CLOTHING";

/** The product details. */
export type Product = {
  /** The ID of the product. */
  id?: string;
  /** The product name. */
  name?: string;
  /** The product description. */
  description?: string;
  type?: "PHYSICAL" | "DIGITAL" | "SERVICE";
  category?: ProductCategory;
  /**
   * The image URL for the product.
   *
   * @format uri
   */
  image_url?: string;
  /**
   * The home page URL for the product.
   *
   * @format uri
   */
  home_url?: string;
  create_time?: DateTime;
  update_time?: DateTime;
  links?: LinkDescriptionList;
};

/** The details for a product in the collection response. */
export type ProductCollectionElement = {
  /** The ID of the product. */
  id?: string;
  /** The product name. */
  name?: string;
  /** The product description. */
  description?: string;
  create_time?: DateTime;
  links?: LinkDescriptionList;
};

/** An array of products. */
export type ProductCollectionElementList = ProductCollectionElement[];

/** The list of products, with details. */
export type ProductCollection = {
  products?: ProductCollectionElementList;
  /** The total number of items. */
  total_items?: number;
  /** The total number of pages. */
  total_pages?: number;
  links?: LinkDescriptionList;
};

/** The create product request details. */
export type ProductRequestPost = {
  /** The ID of the product. You can specify the SKU for the product. If you omit the ID, the system generates it. System-generated IDs have the `PROD-` prefix. */
  id?: string;
  /** The product name. */
  name: string;
  /** The product description. */
  description?: string;
  type: "PHYSICAL" | "DIGITAL" | "SERVICE";
  category?: ProductCategory;
  /**
   * The image URL for the product.
   *
   * @format uri
   */
  image_url?: string;
  /**
   * The home page URL for the product.
   *
   * @format uri
   */
  home_url?: string;
};

export type ProductsCreate400 = unknown;

export type ProductsPatch400 = unknown;

export type ProductsPatch422 = unknown;

export const _400Schema: z.ZodType<_400> = z.unknown();

export const _401Schema: z.ZodType<_401> = z.unknown();

export const _403Schema: z.ZodType<_403> = z.unknown();

export const _404Schema: z.ZodType<_404> = z.unknown();

export const _422Schema: z.ZodType<_422> = z.unknown();

export const DateTimeSchema: z.ZodType<DateTime> = z.string().regex(
  new RegExp(
    "^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])[T,t]([0-1][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)([.][0-9]+)?([Zz]|[+-][0-9]{2}:[0-9]{2})$",
  ),
).min(20).max(64);

export const ErrorLinkDescriptionSchema: z.ZodType<ErrorLinkDescription> = z.object({
  href: z.string().regex(new RegExp("^.*$")).min(0).max(20000),
  rel: z.string().regex(new RegExp("^.*$")).min(0).max(100),
  method: z.enum(["GET", "POST", "PUT", "DELETE", "PATCH"]).optional(),
});

export const Error500Schema: z.ZodType<Error500> = z.object({
  name: z.enum(["INTERNAL_SERVER_ERROR"]).optional(),
  message: z.enum(["An internal server error occurred."]).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error503Schema: z.ZodType<Error503> = z.object({
  name: z.enum(["SERVICE_UNAVAILABLE"]).optional(),
  message: z.enum(["Service Unavailable."]).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const ErrorLocationSchema: z.ZodType<ErrorLocation> = z.enum(["body", "path", "query"]);

export const ErrorDetailsSchema: z.ZodType<ErrorDetails> = z.object({
  field: z.string().optional(),
  value: z.string().optional(),
  location: ErrorLocationSchema.optional(),
  issue: z.string(),
  description: z.string().optional(),
});

export const Error400Schema: z.ZodType<Error400> = z.object({
  name: z.enum(["INVALID_REQUEST"]).optional(),
  message: z.enum(["Request is not well-formed, syntactically incorrect, or violates schema."]).optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error401Schema: z.ZodType<Error401> = z.object({
  name: z.enum(["AUTHENTICATION_FAILURE"]).optional(),
  message: z.enum(["Authentication failed due to missing authorization header, or invalid authentication credentials."])
    .optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error403Schema: z.ZodType<Error403> = z.object({
  name: z.enum(["NOT_AUTHORIZED"]).optional(),
  message: z.enum(["Authorization failed due to insufficient permissions."]).optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error404Schema: z.ZodType<Error404> = z.object({
  name: z.enum(["RESOURCE_NOT_FOUND"]).optional(),
  message: z.enum(["The specified resource does not exist."]).optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error409Schema: z.ZodType<Error409> = z.object({
  name: z.enum(["RESOURCE_CONFLICT"]).optional(),
  message: z.enum(["The server has detected a conflict while processing this request."]).optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error415Schema: z.ZodType<Error415> = z.object({
  name: z.enum(["UNSUPPORTED_MEDIA_TYPE"]).optional(),
  message: z.enum(["The server does not support the request payload's media type."]).optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error422Schema: z.ZodType<Error422> = z.object({
  name: z.enum(["UNPROCESSABLE_ENTITY"]).optional(),
  message: z.enum([
    "The requested action could not be performed, semantically incorrect, or failed business validation.",
  ]).optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const ErrorDefaultSchema: z.ZodType<ErrorDefault> = z.union([
  Error400Schema,
  Error401Schema,
  Error403Schema,
  Error404Schema,
  Error409Schema,
  Error415Schema,
  Error422Schema,
  Error500Schema,
  Error503Schema,
]);

export const LinkDescriptionSchema: z.ZodType<LinkDescription> = z.object({
  href: z.string(),
  rel: z.string(),
  method: z.enum(["GET", "POST", "PUT", "DELETE", "HEAD", "CONNECT", "OPTIONS", "PATCH"]).optional(),
});

export const LinkDescriptionListSchema: z.ZodType<LinkDescriptionList> = z.array(LinkDescriptionSchema);

export const PatchSchema: z.ZodType<Patch> = z.object({
  op: z.enum(["add", "remove", "replace", "move", "copy", "test"]),
  path: z.string().optional(),
  value: z.union([z.number(), z.number().int(), z.string(), z.boolean(), z.null(), z.array(z.unknown()), z.object({})])
    .optional(),
  from: z.string().optional(),
});

export const PatchRequestSchema: z.ZodType<PatchRequest> = z.array(PatchSchema);

export const ProductCategorySchema: z.ZodType<ProductCategory> = z.enum([
  "AC_REFRIGERATION_REPAIR",
  "ACADEMIC_SOFTWARE",
  "ACCESSORIES",
  "ACCOUNTING",
  "ADULT",
  "ADVERTISING",
  "AFFILIATED_AUTO_RENTAL",
  "AGENCIES",
  "AGGREGATORS",
  "AGRICULTURAL_COOPERATIVE_FOR_MAIL_ORDER",
  "AIR_CARRIERS_AIRLINES",
  "AIRLINES",
  "AIRPORTS_FLYING_FIELDS",
  "ALCOHOLIC_BEVERAGES",
  "AMUSEMENT_PARKS_CARNIVALS",
  "ANIMATION",
  "ANTIQUES",
  "APPLIANCES",
  "AQUARIAMS_SEAQUARIUMS_DOLPHINARIUMS",
  "ARCHITECTURAL_ENGINEERING_AND_SURVEYING_SERVICES",
  "ART_AND_CRAFT_SUPPLIES",
  "ART_DEALERS_AND_GALLERIES",
  "ARTIFACTS_GRAVE_RELATED_AND_NATIVE_AMERICAN_CRAFTS",
  "ARTS_AND_CRAFTS",
  "ARTS_CRAFTS_AND_COLLECTIBLES",
  "AUDIO_BOOKS",
  "AUTO_ASSOCIATIONS_CLUBS",
  "AUTO_DEALER_USED_ONLY",
  "AUTO_RENTALS",
  "AUTO_SERVICE",
  "AUTOMATED_FUEL_DISPENSERS",
  "AUTOMOBILE_ASSOCIATIONS",
  "AUTOMOTIVE",
  "AUTOMOTIVE_REPAIR_SHOPS_NON_DEALER",
  "AUTOMOTIVE_TOP_AND_BODY_SHOPS",
  "AVIATION",
  "BABIES_CLOTHING_AND_SUPPLIES",
  "BABY",
  "BANDS_ORCHESTRAS_ENTERTAINERS",
  "BARBIES",
  "BATH_AND_BODY",
  "BATTERIES",
  "BEAN_BABIES",
  "BEAUTY",
  "BEAUTY_AND_FRAGRANCES",
  "BED_AND_BATH",
  "BICYCLE_SHOPS_SALES_AND_SERVICE",
  "BICYCLES_AND_ACCESSORIES",
  "BILLIARD_POOL_ESTABLISHMENTS",
  "BOAT_DEALERS",
  "BOAT_RENTALS_AND_LEASING",
  "BOATING_SAILING_AND_ACCESSORIES",
  "BOOKS",
  "BOOKS_AND_MAGAZINES",
  "BOOKS_MANUSCRIPTS",
  "BOOKS_PERIODICALS_AND_NEWSPAPERS",
  "BOWLING_ALLEYS",
  "BULLETIN_BOARD",
  "BUS_LINE",
  "BUS_LINES_CHARTERS_TOUR_BUSES",
  "BUSINESS",
  "BUSINESS_AND_SECRETARIAL_SCHOOLS",
  "BUYING_AND_SHOPPING_SERVICES_AND_CLUBS",
  "CABLE_SATELLITE_AND_OTHER_PAY_TELEVISION_AND_RADIO_SERVICES",
  "CABLE_SATELLITE_AND_OTHER_PAY_TV_AND_RADIO",
  "CAMERA_AND_PHOTOGRAPHIC_SUPPLIES",
  "CAMERAS",
  "CAMERAS_AND_PHOTOGRAPHY",
  "CAMPER_RECREATIONAL_AND_UTILITY_TRAILER_DEALERS",
  "CAMPING_AND_OUTDOORS",
  "CAMPING_AND_SURVIVAL",
  "CAR_AND_TRUCK_DEALERS",
  "CAR_AND_TRUCK_DEALERS_USED_ONLY",
  "CAR_AUDIO_AND_ELECTRONICS",
  "CAR_RENTAL_AGENCY",
  "CATALOG_MERCHANT",
  "CATALOG_RETAIL_MERCHANT",
  "CATERING_SERVICES",
  "CHARITY",
  "CHECK_CASHIER",
  "CHILD_CARE_SERVICES",
  "CHILDREN_BOOKS",
  "CHIROPODISTS_PODIATRISTS",
  "CHIROPRACTORS",
  "CIGAR_STORES_AND_STANDS",
  "CIVIC_SOCIAL_FRATERNAL_ASSOCIATIONS",
  "CIVIL_SOCIAL_FRAT_ASSOCIATIONS",
  "CLOTHING",
  "CLOTHING_ACCESSORIES_AND_SHOES",
  "CLOTHING_RENTAL",
  "COFFEE_AND_TEA",
  "COIN_OPERATED_BANKS_AND_CASINOS",
  "COLLECTIBLES",
  "COLLECTION_AGENCY",
  "COLLEGES_AND_UNIVERSITIES",
  "COMMERCIAL_EQUIPMENT",
  "COMMERCIAL_FOOTWEAR",
  "COMMERCIAL_PHOTOGRAPHY",
  "COMMERCIAL_PHOTOGRAPHY_ART_AND_GRAPHICS",
  "COMMERCIAL_SPORTS_PROFESSIONA",
  "COMMODITIES_AND_FUTURES_EXCHANGE",
  "COMPUTER_AND_DATA_PROCESSING_SERVICES",
  "COMPUTER_HARDWARE_AND_SOFTWARE",
  "COMPUTER_MAINTENANCE_REPAIR_AND_SERVICES_NOT_ELSEWHERE_CLAS",
  "CONSTRUCTION",
  "CONSTRUCTION_MATERIALS_NOT_ELSEWHERE_CLASSIFIED",
  "CONSULTING_SERVICES",
  "CONSUMER_CREDIT_REPORTING_AGENCIES",
  "CONVALESCENT_HOMES",
  "COSMETIC_STORES",
  "COUNSELING_SERVICES_DEBT_MARRIAGE_PERSONAL",
  "COUNTERFEIT_CURRENCY_AND_STAMPS",
  "COUNTERFEIT_ITEMS",
  "COUNTRY_CLUBS",
  "COURIER_SERVICES",
  "COURIER_SERVICES_AIR_AND_GROUND_AND_FREIGHT_FORWARDERS",
  "COURT_COSTS_ALIMNY_CHILD_SUPT",
  "COURT_COSTS_INCLUDING_ALIMONY_AND_CHILD_SUPPORT_COURTS_OF_LAW",
  "CREDIT_CARDS",
  "CREDIT_UNION",
  "CULTURE_AND_RELIGION",
  "DAIRY_PRODUCTS_STORES",
  "DANCE_HALLS_STUDIOS_AND_SCHOOLS",
  "DECORATIVE",
  "DENTAL",
  "DENTISTS_AND_ORTHODONTISTS",
  "DEPARTMENT_STORES",
  "DESKTOP_PCS",
  "DEVICES",
  "DIECAST_TOYS_VEHICLES",
  "DIGITAL_GAMES",
  "DIGITAL_MEDIA_BOOKS_MOVIES_MUSIC",
  "DIRECT_MARKETING",
  "DIRECT_MARKETING_CATALOG_MERCHANT",
  "DIRECT_MARKETING_INBOUND_TELE",
  "DIRECT_MARKETING_OUTBOUND_TELE",
  "DIRECT_MARKETING_SUBSCRIPTION",
  "DISCOUNT_STORES",
  "DOOR_TO_DOOR_SALES",
  "DRAPERY_WINDOW_COVERING_AND_UPHOLSTERY",
  "DRINKING_PLACES",
  "DRUGSTORE",
  "DURABLE_GOODS",
  "ECOMMERCE_DEVELOPMENT",
  "ECOMMERCE_SERVICES",
  "EDUCATIONAL_AND_TEXTBOOKS",
  "ELECTRIC_RAZOR_STORES",
  "ELECTRICAL_AND_SMALL_APPLIANCE_REPAIR",
  "ELECTRICAL_CONTRACTORS",
  "ELECTRICAL_PARTS_AND_EQUIPMENT",
  "ELECTRONIC_CASH",
  "ELEMENTARY_AND_SECONDARY_SCHOOLS",
  "EMPLOYMENT",
  "ENTERTAINERS",
  "ENTERTAINMENT_AND_MEDIA",
  "EQUIP_TOOL_FURNITURE_AND_APPLIANCE_RENTAL_AND_LEASING",
  "ESCROW",
  "EVENT_AND_WEDDING_PLANNING",
  "EXERCISE_AND_FITNESS",
  "EXERCISE_EQUIPMENT",
  "EXTERMINATING_AND_DISINFECTING_SERVICES",
  "FABRICS_AND_SEWING",
  "FAMILY_CLOTHING_STORES",
  "FASHION_JEWELRY",
  "FAST_FOOD_RESTAURANTS",
  "FICTION_AND_NONFICTION",
  "FINANCE_COMPANY",
  "FINANCIAL_AND_INVESTMENT_ADVICE",
  "FINANCIAL_INSTITUTIONS_MERCHANDISE_AND_SERVICES",
  "FIREARM_ACCESSORIES",
  "FIREARMS_WEAPONS_AND_KNIVES",
  "FIREPLACE_AND_FIREPLACE_SCREENS",
  "FIREWORKS",
  "FISHING",
  "FLORISTS",
  "FLOWERS",
  "FOOD_DRINK_AND_NUTRITION",
  "FOOD_PRODUCTS",
  "FOOD_RETAIL_AND_SERVICE",
  "FRAGRANCES_AND_PERFUMES",
  "FREEZER_AND_LOCKER_MEAT_PROVISIONERS",
  "FUEL_DEALERS_FUEL_OIL_WOOD_AND_COAL",
  "FUEL_DEALERS_NON_AUTOMOTIVE",
  "FUNERAL_SERVICES_AND_CREMATORIES",
  "FURNISHING_AND_DECORATING",
  "FURNITURE",
  "FURRIERS_AND_FUR_SHOPS",
  "GADGETS_AND_OTHER_ELECTRONICS",
  "GAMBLING",
  "GAME_SOFTWARE",
  "GAMES",
  "GARDEN_SUPPLIES",
  "GENERAL",
  "GENERAL_CONTRACTORS",
  "GENERAL_GOVERNMENT",
  "GENERAL_SOFTWARE",
  "GENERAL_TELECOM",
  "GIFTS_AND_FLOWERS",
  "GLASS_PAINT_AND_WALLPAPER_STORES",
  "GLASSWARE_CRYSTAL_STORES",
  "GOVERNMENT",
  "GOVERNMENT_IDS_AND_LICENSES",
  "GOVERNMENT_LICENSED_ON_LINE_CASINOS_ON_LINE_GAMBLING",
  "GOVERNMENT_OWNED_LOTTERIES",
  "GOVERNMENT_SERVICES",
  "GRAPHIC_AND_COMMERCIAL_DESIGN",
  "GREETING_CARDS",
  "GROCERY_STORES_AND_SUPERMARKETS",
  "HARDWARE_AND_TOOLS",
  "HARDWARE_EQUIPMENT_AND_SUPPLIES",
  "HAZARDOUS_RESTRICTED_AND_PERISHABLE_ITEMS",
  "HEALTH_AND_BEAUTY_SPAS",
  "HEALTH_AND_NUTRITION",
  "HEALTH_AND_PERSONAL_CARE",
  "HEARING_AIDS_SALES_AND_SUPPLIES",
  "HEATING_PLUMBING_AC",
  "HIGH_RISK_MERCHANT",
  "HIRING_SERVICES",
  "HOBBIES_TOYS_AND_GAMES",
  "HOME_AND_GARDEN",
  "HOME_AUDIO",
  "HOME_DECOR",
  "HOME_ELECTRONICS",
  "HOSPITALS",
  "HOTELS_MOTELS_INNS_RESORTS",
  "HOUSEWARES",
  "HUMAN_PARTS_AND_REMAINS",
  "HUMOROUS_GIFTS_AND_NOVELTIES",
  "HUNTING",
  "IDS_LICENSES_AND_PASSPORTS",
  "ILLEGAL_DRUGS_AND_PARAPHERNALIA",
  "INDUSTRIAL",
  "INDUSTRIAL_AND_MANUFACTURING_SUPPLIES",
  "INSURANCE_AUTO_AND_HOME",
  "INSURANCE_DIRECT",
  "INSURANCE_LIFE_AND_ANNUITY",
  "INSURANCE_SALES_UNDERWRITING",
  "INSURANCE_UNDERWRITING_PREMIUMS",
  "INTERNET_AND_NETWORK_SERVICES",
  "INTRA_COMPANY_PURCHASES",
  "LABORATORIES_DENTAL_MEDICAL",
  "LANDSCAPING",
  "LANDSCAPING_AND_HORTICULTURAL_SERVICES",
  "LAUNDRY_CLEANING_SERVICES",
  "LEGAL",
  "LEGAL_SERVICES_AND_ATTORNEYS",
  "LOCAL_DELIVERY_SERVICE",
  "LOCKSMITH",
  "LODGING_AND_ACCOMMODATIONS",
  "LOTTERY_AND_CONTESTS",
  "LUGGAGE_AND_LEATHER_GOODS",
  "LUMBER_AND_BUILDING_MATERIALS",
  "MAGAZINES",
  "MAINTENANCE_AND_REPAIR_SERVICES",
  "MAKEUP_AND_COSMETICS",
  "MANUAL_CASH_DISBURSEMENTS",
  "MASSAGE_PARLORS",
  "MEDICAL",
  "MEDICAL_AND_PHARMACEUTICAL",
  "MEDICAL_CARE",
  "MEDICAL_EQUIPMENT_AND_SUPPLIES",
  "MEDICAL_SERVICES",
  "MEETING_PLANNERS",
  "MEMBERSHIP_CLUBS_AND_ORGANIZATIONS",
  "MEMBERSHIP_COUNTRY_CLUBS_GOLF",
  "MEMORABILIA",
  "MEN_AND_BOY_CLOTHING_AND_ACCESSORY_STORES",
  "MEN_CLOTHING",
  "MERCHANDISE",
  "METAPHYSICAL",
  "MILITARIA",
  "MILITARY_AND_CIVIL_SERVICE_UNIFORMS",
  "MISC._AUTOMOTIVE_AIRCRAFT_AND_FARM_EQUIPMENT_DEALERS",
  "MISC._GENERAL_MERCHANDISE",
  "MISCELLANEOUS_GENERAL_SERVICES",
  "MISCELLANEOUS_REPAIR_SHOPS_AND_RELATED_SERVICES",
  "MODEL_KITS",
  "MONEY_TRANSFER_MEMBER_FINANCIAL_INSTITUTION",
  "MONEY_TRANSFER_MERCHANT",
  "MOTION_PICTURE_THEATERS",
  "MOTOR_FREIGHT_CARRIERS_AND_TRUCKING",
  "MOTOR_HOME_AND_RECREATIONAL_VEHICLE_RENTAL",
  "MOTOR_HOMES_DEALERS",
  "MOTOR_VEHICLE_SUPPLIES_AND_NEW_PARTS",
  "MOTORCYCLE_DEALERS",
  "MOTORCYCLES",
  "MOVIE",
  "MOVIE_TICKETS",
  "MOVING_AND_STORAGE",
  "MULTI_LEVEL_MARKETING",
  "MUSIC_CDS_CASSETTES_AND_ALBUMS",
  "MUSIC_STORE_INSTRUMENTS_AND_SHEET_MUSIC",
  "NETWORKING",
  "NEW_AGE",
  "NEW_PARTS_AND_SUPPLIES_MOTOR_VEHICLE",
  "NEWS_DEALERS_AND_NEWSTANDS",
  "NON_DURABLE_GOODS",
  "NON_FICTION",
  "NON_PROFIT_POLITICAL_AND_RELIGION",
  "NONPROFIT",
  "NOVELTIES",
  "OEM_SOFTWARE",
  "OFFICE_SUPPLIES_AND_EQUIPMENT",
  "ONLINE_DATING",
  "ONLINE_GAMING",
  "ONLINE_GAMING_CURRENCY",
  "ONLINE_SERVICES",
  "OOUTBOUND_TELEMARKETING_MERCH",
  "OPHTHALMOLOGISTS_OPTOMETRIST",
  "OPTICIANS_AND_DISPENSING",
  "ORTHOPEDIC_GOODS_PROSTHETICS",
  "OSTEOPATHS",
  "OTHER",
  "PACKAGE_TOUR_OPERATORS",
  "PAINTBALL",
  "PAINTS_VARNISHES_AND_SUPPLIES",
  "PARKING_LOTS_AND_GARAGES",
  "PARTS_AND_ACCESSORIES",
  "PAWN_SHOPS",
  "PAYCHECK_LENDER_OR_CASH_ADVANCE",
  "PERIPHERALS",
  "PERSONALIZED_GIFTS",
  "PET_SHOPS_PET_FOOD_AND_SUPPLIES",
  "PETROLEUM_AND_PETROLEUM_PRODUCTS",
  "PETS_AND_ANIMALS",
  "PHOTOFINISHING_LABORATORIES_PHOTO_DEVELOPING",
  "PHOTOGRAPHIC_STUDIOS_PORTRAITS",
  "PHOTOGRAPHY",
  "PHYSICAL_GOOD",
  "PICTURE_VIDEO_PRODUCTION",
  "PIECE_GOODS_NOTIONS_AND_OTHER_DRY_GOODS",
  "PLANTS_AND_SEEDS",
  "PLUMBING_AND_HEATING_EQUIPMENTS_AND_SUPPLIES",
  "POLICE_RELATED_ITEMS",
  "POLITICAL_ORGANIZATIONS",
  "POSTAL_SERVICES_GOVERNMENT_ONLY",
  "POSTERS",
  "PREPAID_AND_STORED_VALUE_CARDS",
  "PRESCRIPTION_DRUGS",
  "PROMOTIONAL_ITEMS",
  "PUBLIC_WAREHOUSING_AND_STORAGE",
  "PUBLISHING_AND_PRINTING",
  "PUBLISHING_SERVICES",
  "RADAR_DECTORS",
  "RADIO_TELEVISION_AND_STEREO_REPAIR",
  "REAL_ESTATE",
  "REAL_ESTATE_AGENT",
  "REAL_ESTATE_AGENTS_AND_MANAGERS_RENTALS",
  "RELIGION_AND_SPIRITUALITY_FOR_PROFIT",
  "RELIGIOUS",
  "RELIGIOUS_ORGANIZATIONS",
  "REMITTANCE",
  "RENTAL_PROPERTY_MANAGEMENT",
  "RESIDENTIAL",
  "RETAIL",
  "RETAIL_FINE_JEWELRY_AND_WATCHES",
  "REUPHOLSTERY_AND_FURNITURE_REPAIR",
  "RINGS",
  "ROOFING_SIDING_SHEET_METAL",
  "RUGS_AND_CARPETS",
  "SCHOOLS_AND_COLLEGES",
  "SCIENCE_FICTION",
  "SCRAPBOOKING",
  "SCULPTURES",
  "SECURITIES_BROKERS_AND_DEALERS",
  "SECURITY_AND_SURVEILLANCE",
  "SECURITY_AND_SURVEILLANCE_EQUIPMENT",
  "SECURITY_BROKERS_AND_DEALERS",
  "SEMINARS",
  "SERVICE_STATIONS",
  "SERVICES",
  "SEWING_NEEDLEWORK_FABRIC_AND_PIECE_GOODS_STORES",
  "SHIPPING_AND_PACKING",
  "SHOE_REPAIR_HAT_CLEANING",
  "SHOE_STORES",
  "SHOES",
  "SNOWMOBILE_DEALERS",
  "SOFTWARE",
  "SPECIALTY_AND_MISC._FOOD_STORES",
  "SPECIALTY_CLEANING_POLISHING_AND_SANITATION_PREPARATIONS",
  "SPECIALTY_OR_RARE_PETS",
  "SPORT_GAMES_AND_TOYS",
  "SPORTING_AND_RECREATIONAL_CAMPS",
  "SPORTING_GOODS",
  "SPORTS_AND_OUTDOORS",
  "SPORTS_AND_RECREATION",
  "STAMP_AND_COIN",
  "STATIONARY_PRINTING_AND_WRITING_PAPER",
  "STENOGRAPHIC_AND_SECRETARIAL_SUPPORT_SERVICES",
  "STOCKS_BONDS_SECURITIES_AND_RELATED_CERTIFICATES",
  "STORED_VALUE_CARDS",
  "SUPPLIES",
  "SUPPLIES_AND_TOYS",
  "SURVEILLANCE_EQUIPMENT",
  "SWIMMING_POOLS_AND_SPAS",
  "SWIMMING_POOLS_SALES_SUPPLIES_SERVICES",
  "TAILORS_AND_ALTERATIONS",
  "TAX_PAYMENTS",
  "TAX_PAYMENTS_GOVERNMENT_AGENCIES",
  "TAXICABS_AND_LIMOUSINES",
  "TELECOMMUNICATION_SERVICES",
  "TELEPHONE_CARDS",
  "TELEPHONE_EQUIPMENT",
  "TELEPHONE_SERVICES",
  "THEATER",
  "TIRE_RETREADING_AND_REPAIR",
  "TOLL_OR_BRIDGE_FEES",
  "TOOLS_AND_EQUIPMENT",
  "TOURIST_ATTRACTIONS_AND_EXHIBITS",
  "TOWING_SERVICE",
  "TOYS_AND_GAMES",
  "TRADE_AND_VOCATIONAL_SCHOOLS",
  "TRADEMARK_INFRINGEMENT",
  "TRAILER_PARKS_AND_CAMPGROUNDS",
  "TRAINING_SERVICES",
  "TRANSPORTATION_SERVICES",
  "TRAVEL",
  "TRUCK_AND_UTILITY_TRAILER_RENTALS",
  "TRUCK_STOP",
  "TYPESETTING_PLATE_MAKING_AND_RELATED_SERVICES",
  "USED_MERCHANDISE_AND_SECONDHAND_STORES",
  "USED_PARTS_MOTOR_VEHICLE",
  "UTILITIES",
  "UTILITIES_ELECTRIC_GAS_WATER_SANITARY",
  "VARIETY_STORES",
  "VEHICLE_SALES",
  "VEHICLE_SERVICE_AND_ACCESSORIES",
  "VIDEO_EQUIPMENT",
  "VIDEO_GAME_ARCADES_ESTABLISH",
  "VIDEO_GAMES_AND_SYSTEMS",
  "VIDEO_TAPE_RENTAL_STORES",
  "VINTAGE_AND_COLLECTIBLE_VEHICLES",
  "VINTAGE_AND_COLLECTIBLES",
  "VITAMINS_AND_SUPPLEMENTS",
  "VOCATIONAL_AND_TRADE_SCHOOLS",
  "WATCH_CLOCK_AND_JEWELRY_REPAIR",
  "WEB_HOSTING_AND_DESIGN",
  "WELDING_REPAIR",
  "WHOLESALE_CLUBS",
  "WHOLESALE_FLORIST_SUPPLIERS",
  "WHOLESALE_PRESCRIPTION_DRUGS",
  "WILDLIFE_PRODUCTS",
  "WIRE_TRANSFER",
  "WIRE_TRANSFER_AND_MONEY_ORDER",
  "WOMEN_ACCESSORY_SPECIALITY",
  "WOMEN_CLOTHING",
]);

export const ProductSchema: z.ZodType<Product> = z.object({
  id: z.string().min(6).max(50).optional(),
  name: z.string().min(1).max(127).optional(),
  description: z.string().min(1).max(256).optional(),
  type: z.enum(["PHYSICAL", "DIGITAL", "SERVICE"]).optional(),
  category: ProductCategorySchema.optional(),
  image_url: z.string().min(1).max(2000).optional(),
  home_url: z.string().min(1).max(2000).optional(),
  create_time: DateTimeSchema.optional(),
  update_time: DateTimeSchema.optional(),
  links: LinkDescriptionListSchema.optional(),
});

export const ProductCollectionElementSchema: z.ZodType<ProductCollectionElement> = z.object({
  id: z.string().min(6).max(50).optional(),
  name: z.string().min(1).max(127).optional(),
  description: z.string().min(1).max(256).optional(),
  create_time: DateTimeSchema.optional(),
  links: LinkDescriptionListSchema.optional(),
});

export const ProductCollectionElementListSchema: z.ZodType<ProductCollectionElementList> = z.array(
  ProductCollectionElementSchema,
).min(1).max(32767);

export const ProductCollectionSchema: z.ZodType<ProductCollection> = z.object({
  products: ProductCollectionElementListSchema.optional(),
  total_items: z.number().int().min(0).max(500000000).optional(),
  total_pages: z.number().int().min(0).max(100000000).optional(),
  links: LinkDescriptionListSchema.optional(),
});

export const ProductRequestPostSchema: z.ZodType<ProductRequestPost> = z.object({
  id: z.string().min(6).max(50).optional(),
  name: z.string().min(1).max(127),
  description: z.string().min(1).max(256).optional(),
  type: z.enum(["PHYSICAL", "DIGITAL", "SERVICE"]),
  category: ProductCategorySchema.optional(),
  image_url: z.string().min(1).max(2000).optional(),
  home_url: z.string().min(1).max(2000).optional(),
});

export const ProductsCreate400Schema: z.ZodType<ProductsCreate400> = z.unknown();

export const ProductsPatch400Schema: z.ZodType<ProductsPatch400> = z.unknown();

export const ProductsPatch422Schema: z.ZodType<ProductsPatch422> = z.unknown();

/**
 * API Client class with path-based access to all operations.
 * All methods are inline within the class.
 */
export class ApiClient {
  constructor(private readonly config?: OpenAPIClientConfig) {}

  readonly "/v1/catalogs/products" = {
    /**
     * List products
     *
     * Lists products.
     */
    get: (request?: {
      query?: {
        /** The number of items to return in the response. */
        page_size?: number;
        /** A non-zero integer which is the start index of the entire list of items that are returned in the response. So, the combination of `page=1` and `page_size=20` returns the first 20 items. The combination of `page=2` and `page_size=20` returns the next 20 items. */
        page?: number;
        /** Indicates whether to show the total items and total pages in the response. */
        total_required?: boolean;
      };
    }): OpenAPIResponsePromise<
      OpenAPIResponses<{
        /** A successful request returns the HTTP `200 OK` status code and a JSON response body that lists products with details. */
        200: {
          body: ProductCollection;
        };
        /** Bad Request. Request is not well-formed, syntactically incorrect, or violates schema. */
        400: {
          body: Error400 & _400;
        };
        /** Authentication failed due to missing authorization header, or invalid authentication credentials. */
        401: {
          body: Error401 & _401;
        };
        /** Authorization failed due to insufficient permissions. */
        403: {
          body: Error403 & _403;
        };
        /** An internal server error has occurred. */
        500: {
          body: Error500;
        };
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/v1/catalogs/products",
          method: "get",
          requestSchema: z.object({
            query: z.object({
              page_size: z.number().int().min(1).max(20).default(10).optional(),
              page: z.number().int().min(1).max(100000).default(1).optional(),
              total_required: z.boolean().optional(),
            }).optional(),
          }),
          responseSchema: {
            200: z.object({ body: ProductCollectionSchema }),
            400: z.object({ body: Error400Schema.and(_400Schema) }),
            401: z.object({ body: Error401Schema.and(_401Schema) }),
            403: z.object({ body: Error403Schema.and(_403Schema) }),
            500: z.object({ body: Error500Schema }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
    /**
     * Create product
     *
     * Creates a product.
     */
    post: (request: {
      headers?: {
        /** The preferred server response upon successful completion of the request. Value is:<ul><li><code>return=minimal</code>. The server returns a minimal response to optimize communication between the API caller and the server. A minimal response includes the <code>id</code>, <code>status</code> and HATEOAS links.</li><li><code>return=representation</code>. The server returns a complete resource representation, including the current state of the resource.</li></ul> */
        Prefer?: string;
        /** The server stores keys for 72 hours. */
        "PayPal-Request-Id"?: string;
      };
      body: ProductRequestPost;
    }): OpenAPIResponsePromise<
      OpenAPIResponses<{
        /** A successful request returns the HTTP `200 OK` status code and a JSON response body that shows product details. */
        200: {
          body: Product;
        };
        /** A successful request returns the HTTP `201 Created` status code and a JSON response body that shows product details. */
        201: {
          body: Product;
        };
        /** Bad Request. Request is not well-formed, syntactically incorrect, or violates schema. */
        400: {
          body: Error400 & ProductsCreate400;
        };
        /** Authentication failed due to missing authorization header, or invalid authentication credentials. */
        401: {
          body: Error401 & _401;
        };
        /** Authorization failed due to insufficient permissions. */
        403: {
          body: Error403 & _403;
        };
        /** The requested action could not be performed, semantically incorrect, or failed business validation. */
        422: {
          body: Error422 & _422;
        };
        /** An internal server error has occurred. */
        500: {
          body: Error500;
        };
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/v1/catalogs/products",
          method: "post",
          requestSchema: z.object({
            headers: z.object({
              Prefer: z.string().default("return=minimal").optional(),
              "PayPal-Request-Id": z.string().optional(),
            }).optional(),
            body: ProductRequestPostSchema,
          }),
          responseSchema: {
            200: z.object({ body: ProductSchema }),
            201: z.object({ body: ProductSchema }),
            400: z.object({ body: Error400Schema.and(ProductsCreate400Schema) }),
            401: z.object({ body: Error401Schema.and(_401Schema) }),
            403: z.object({ body: Error403Schema.and(_403Schema) }),
            422: z.object({ body: Error422Schema.and(_422Schema) }),
            500: z.object({ body: Error500Schema }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };

  readonly "/v1/catalogs/products/{product_id}" = {
    /**
     * Show product details
     *
     * Shows details for a product, by ID.
     */
    get: (request: {
      path: {
        /** The product ID. */
        product_id: string;
      };
    }): OpenAPIResponsePromise<
      OpenAPIResponses<{
        /** A successful request returns the HTTP `200 OK` status code and a JSON response body that shows product details. */
        200: {
          body: Product;
        };
        /** Authentication failed due to missing authorization header, or invalid authentication credentials. */
        401: {
          body: Error401 & _401;
        };
        /** Authorization failed due to insufficient permissions. */
        403: {
          body: Error403 & _403;
        };
        /** The specified resource does not exist. */
        404: {
          body: Error404 & _404;
        };
        /** An internal server error has occurred. */
        500: {
          body: Error500;
        };
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/v1/catalogs/products/{product_id}",
          method: "get",
          requestSchema: z.object({
            path: z.object({
              product_id: z.string(),
            }),
          }),
          responseSchema: {
            200: z.object({ body: ProductSchema }),
            401: z.object({ body: Error401Schema.and(_401Schema) }),
            403: z.object({ body: Error403Schema.and(_403Schema) }),
            404: z.object({ body: Error404Schema.and(_404Schema) }),
            500: z.object({ body: Error500Schema }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
    /**
     * Update product
     *
     * Updates a product, by ID. You can patch these attributes and objects:<table><thead><tr><th>Attribute or object</th><th>Operations</th></tr></thead><tbody><tr><td><code>description</code></td><td>add, replace, remove</td></tr><tr><td><code>category</code></td><td>add, replace, remove</td></tr><tr><td><code>image_url</code></td><td>add, replace, remove</td></tr><tr><td><code>home_url</code></td><td>add, replace, remove</td></tr></tbody></table>
     */
    patch: (request: {
      path: {
        /** The product ID. */
        product_id: string;
      };
      body: PatchRequest;
    }): OpenAPIResponsePromise<
      OpenAPIResponses<{
        /** A successful request returns the HTTP `204 No Content` status code with no JSON response body. */
        204: {
          body: unknown;
        };
        /** Bad Request. Request is not well-formed, syntactically incorrect, or violates schema. */
        400: {
          body: Error400 & ProductsPatch400;
        };
        /** Authentication failed due to missing authorization header, or invalid authentication credentials. */
        401: {
          body: Error401 & _401;
        };
        /** Authorization failed due to insufficient permissions. */
        403: {
          body: Error403 & _403;
        };
        /** The specified resource does not exist. */
        404: {
          body: Error404 & _404;
        };
        /** The requested action could not be performed, semantically incorrect, or failed business validation. */
        422: {
          body: Error422 & ProductsPatch422;
        };
        /** An internal server error has occurred. */
        500: {
          body: Error500;
        };
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/v1/catalogs/products/{product_id}",
          method: "patch",
          requestSchema: z.object({
            path: z.object({
              product_id: z.string(),
            }),
            body: PatchRequestSchema,
          }),
          responseSchema: {
            204: z.object({ body: z.unknown() }),
            400: z.object({ body: Error400Schema.and(ProductsPatch400Schema) }),
            401: z.object({ body: Error401Schema.and(_401Schema) }),
            403: z.object({ body: Error403Schema.and(_403Schema) }),
            404: z.object({ body: Error404Schema.and(_404Schema) }),
            422: z.object({ body: Error422Schema.and(ProductsPatch422Schema) }),
            500: z.object({ body: Error500Schema }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };
}
