// deno-lint-ignore-file no-explicit-any
// This file was auto-generated by @brad-jones/open-api-client

import {
  createCustomClient,
  type OpenAPIClientConfig,
  openAPIFetch,
  type OpenAPIResponsePromise,
  type OpenAPIResponses,
} from "jsr:@brad-jones/deno-net-open-api-client@0.2.5";
import { z } from "npm:zod@^4.1.12";

/** Metadata for Venmo transactions. */
export type ApplicationContext = {
  /** This attribute controls the privacy of a payout transaction in recipient’s feed. PUBLIC, FRIENDS_ONLY & PRIVATE are the values that can be used. PUBLIC - The payment displays on the recipient's public Venmo feed. FRIENDS_ONLY - The payment displays only to the recipient's Venmo friends. PRIVATE - The payment displays only on the recipient's personal feed. Defaults to `PRIVATE` if left blank. */
  social_feed_privacy?: string;
  /**
   * Link to a Holler sticker. For Venmo recipients, the sticker displays with the payout message. The maximum URL length is 151.
   *
   * @format uri
   */
  holler_url?: string;
  /**
   * Link to a logo that displays as the sender's profile image in the recipient's Venmo feed. Used to add or update the business profile image. Max image size: 1024 x 1024 pixels. The image should be square and maximum URL length is 2000.
   *
   * @format uri
   */
  logo_url?: string;
};

export type BatchEnum = "DENIED" | "PENDING" | "PROCESSING" | "SUCCESS" | "CANCELED";

/** The currency and amount for a financial transaction, such as a balance or payment due. */
export type Currency = {
  /** The [three-character ISO-4217 currency code](/docs/integration/direct/rest/currency-codes/). */
  currency: string;
  /** The value, which might be:<ul><li>An integer for currencies like `JPY` that are not typically fractional.</li><li>A decimal fraction for currencies like `TND` that are subdivided into thousandths.</li></ul>For the required number of decimal places for a currency code, see [Currency codes - ISO 4217](https://www.iso.org/iso-4217-currency-codes.html). */
  value: string;
};

/** The error details. Required for client-side `4XX` errors. */
export type ErrorDetails2 = {
  /** The field that caused the error. If this field is in the body, set this value to the field's JSON pointer value. Required for client-side errors. */
  field?: string;
  /** The value of the field that caused the error. */
  value?: string;
  /** The location of the field that caused the error. Value is `body`, `path`, or `query`. */
  location?: string;
  /** The unique, fine-grained application-level error code. */
  issue: string;
  /** The human-readable description for an issue. The description can change over the lifetime of an API, so clients must not depend on this value. */
  description?: string;
};

/** An array of additional details about the error. */
export type ErrorDetailsList = ErrorDetails2[];

/** The request-related [HATEOAS link](/api/rest/responses/#hateoas-links) information. */
export type ErrorLinkDescription = {
  /** The complete target URL. To make the related call, combine the method with this [URI Template-formatted](https://tools.ietf.org/html/rfc6570) link. For pre-processing, include the `$`, `(`, and `)` characters. The `href` is the key HATEOAS component that links a completed call with a subsequent call. */
  href: string;
  /** The [link relation type](https://tools.ietf.org/html/rfc5988#section-4), which serves as an ID for a link that unambiguously describes the semantics of the link. See [Link Relations](https://www.iana.org/assignments/link-relations/link-relations.xhtml). */
  rel: string;
  method?: "GET" | "POST" | "PUT" | "DELETE" | "PATCH";
};

/** This is either a system or application error, and generally indicates that although the client appeared to provide a correct request, something unexpected has gone wrong on the server. */
export type Error500 = {
  name?: "INTERNAL_SERVER_ERROR";
  message?: "An internal server error occurred.";
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** The server is temporarily unable to handle the request, for example, because of planned maintenance or downtime. */
export type Error503 = {
  name?: "SERVICE_UNAVAILABLE";
  message?: "Service Unavailable.";
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

export type ErrorLocation = "body" | "path" | "query";

/** The error details. Required for client-side `4XX` errors. */
export type ErrorDetails = {
  /** The field that caused the error. If this field is in the body, set this value to the field's JSON pointer value. Required for client-side errors. */
  field?: string;
  /** The value of the field that caused the error. */
  value?: string;
  location?: ErrorLocation;
  /** The unique, fine-grained application-level error code. */
  issue: string;
  /** The human-readable description for an issue. The description can change over the lifetime of an API, so clients must not depend on this value. */
  description?: string;
};

/** Request is not well-formed, syntactically incorrect, or violates schema. */
export type Error400 = {
  name?: "INVALID_REQUEST";
  message?: "Request is not well-formed, syntactically incorrect, or violates schema.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** Authentication failed due to missing Authorization header, or invalid authentication credentials. */
export type Error401 = {
  name?: "AUTHENTICATION_FAILURE";
  message?: "Authentication failed due to missing authorization header, or invalid authentication credentials.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** The client is not authorized to access this resource, although it may have valid credentials.  */
export type Error403 = {
  name?: "NOT_AUTHORIZED";
  message?: "Authorization failed due to insufficient permissions.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** The server has not found anything matching the request URI. This either means that the URI is incorrect or the resource is not available. */
export type Error404 = {
  name?: "RESOURCE_NOT_FOUND";
  message?: "The specified resource does not exist.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** The server has detected a conflict while processing this request. */
export type Error409 = {
  name?: "RESOURCE_CONFLICT";
  message?: "The server has detected a conflict while processing this request.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** The server does not support the request payload's media type. */
export type Error415 = {
  name?: "UNSUPPORTED_MEDIA_TYPE";
  message?: "The server does not support the request payload's media type.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** The requested action cannot be performed and may require interaction with APIs or processes outside of the current request. This is distinct from a 500 response in that there are no systemic problems limiting the API from performing the request. */
export type Error422 = {
  name?: "UNPROCESSABLE_ENTITY";
  message?: "The requested action could not be performed, semantically incorrect, or failed business validation.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

export type ErrorDefault =
  | Error400
  | Error401
  | Error403
  | Error404
  | Error409
  | Error415
  | Error422
  | Error500
  | Error503;

export type FundingSource = "BALANCE";

/**
 * The [language tag](https://tools.ietf.org/html/bcp47#section-2) for the language in which to localize the error-related strings, such as messages, issues, and suggested actions. The tag is made up of the [ISO 639-2 language code](https://www.loc.gov/standards/iso639-2/php/code_list.php), the optional [ISO-15924 script tag](https://www.unicode.org/iso15924/codelists.html), and the [ISO-3166 alpha-2 country code](/docs/integration/direct/rest/country-codes/).
 *
 * @format ppaas_common_language_v3
 */
export type Language = string;

/** The request-related [HATEOAS link](/docs/api/reference/api-responses/#hateoas-links) information. */
export type LinkDescription = {
  /** The complete target URL. To make the related call, combine the method with this [URI Template-formatted](https://tools.ietf.org/html/rfc6570) link. For pre-processing, include the `$`, `(`, and `)` characters. The `href` is the key HATEOAS component that links a completed call with a subsequent call. */
  href: string;
  /** The [link relation type](https://tools.ietf.org/html/rfc5988#section-4), which serves as an ID for a link that unambiguously describes the semantics of the link. See [Link Relations](https://www.iana.org/assignments/link-relations/link-relations.xhtml). */
  rel: string;
  method?: "GET" | "POST" | "PUT" | "DELETE" | "HEAD" | "CONNECT" | "OPTIONS" | "PATCH";
};

/** An array of request-related [HATEOAS links](/api/rest/responses/#hateoas-links). */
export type DefinitionsLinkDescriptionList = LinkDescription[];

/** An array of request-related [HATEOAS links](/docs/api/reference/api-responses/#hateoas-links). */
export type LinkDescriptionList = LinkDescription[];

/** The error details. */
export type Error = {
  /** The human-readable, unique name of the error. */
  name: string;
  /** The message that describes the error. */
  message: string;
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id: string;
  /** The information link, or URI, that shows detailed information about this error for the developer. */
  information_link?: string;
  details?: ErrorDetailsList;
  links?: LinkDescriptionList;
};

/** The name of the party. */
export type Name = {
  /** The prefix, or title, to the party's name. */
  prefix?: string;
  /** When the party is a person, the party's given, or first, name. */
  given_name?: string;
  /** When the party is a person, the party's surname or family name. Also known as the last name. Required when the party is a person. Use also to store multiple surnames including the matronymic, or mother's, surname. */
  surname?: string;
  /** When the party is a person, the party's middle name. Use also to store multiple middle names including the patronymic, or father's, middle name. */
  middle_name?: string;
  /** The suffix for the party's name. */
  suffix?: string;
  /** DEPRECATED. The party's alternate name. Can be a business name, nickname, or any other name that cannot be split into first, last name. Required when the party is a business. */
  alternate_full_name?: string;
  /** When the party is a person, the party's full name. */
  full_name?: string;
};

/** An array of request-related [HATEOAS links](/api/rest/responses/#hateoas-links). */
export type PayoutBatchDefinitionsLinkDescriptionList = LinkDescription[];

/** An array of request-related [HATEOAS links](/api/rest/responses/#hateoas-links). */
export type PayoutBatchItemsDefinitionsLinkDescriptionList = LinkDescription[];

/** The currency conversion resource. */
export type PayoutCurrencyConversion = {
  from_amount?: Currency;
  to_amount?: Currency;
  /** The exchange rate that is applied for this payout. */
  exchange_rate?: string;
};

/** An array of request-related [HATEOAS links](/api/rest/responses/#hateoas-links). */
export type PayoutItemDefinitionsLinkDescriptionList = LinkDescription[];

/** The phone number in its canonical international [E.164 numbering plan format](https://www.itu.int/rec/T-REC-E.164/en). */
export type Phone = {
  /** The country calling code (CC), in its canonical international [E.164 numbering plan format](https://www.itu.int/rec/T-REC-E.164/en). The combined length of the CC and the national number must not be greater than 15 digits. The national number consists of a national destination code (NDC) and subscriber number (SN). */
  country_code: string;
  /** The national number, in its canonical international [E.164 numbering plan format](https://www.itu.int/rec/T-REC-E.164/en). The combined length of the country calling code (CC) and the national number must not be greater than 15 digits. The national number consists of a national destination code (NDC) and subscriber number (SN). */
  national_number: string;
  /** The extension number. */
  extension_number?: string;
};

/** Captures additional notification modes to reach out to the receiver regarding this payment. */
export type AlternateNotificationMethod = {
  phone?: Phone;
};

export type PurposeEnum =
  | "AWARDS"
  | "PRIZES"
  | "DONATIONS"
  | "GOODS"
  | "SERVICES"
  | "REBATES"
  | "CASHBACK"
  | "DISCOUNTS"
  | "NON_GOODS_OR_SERVICES";

/** The sender-created payout to a recipient. */
export type PayoutItemRequest = {
  /** The recipient type. Value is:<ul><li><p><code>EMAIL</code>. The unencrypted email. Value is a string of up to 127 single-byte characters.</p></li><li><p><code>PHONE</code>. The unencrypted phone number.</p><blockquote><strong>Note:</strong> The PayPal sandbox does not support the <code>PHONE</code> recipient type.</blockquote></li><li><p><code>PAYPAL_ID</code>. The encrypted PayPal account number.</p></li><li><p><code>USER_HANDLE</code>. User handle (or) Username associated with Venmo account.</p></li></ul><br/>If the <code>sender_batch_header</code> includes the <code>recipient_type</code> attribute, payout items use the <code>recipient_type</code> of the <code>sender_batch_header</code>, unless a payout item has its own <code>recipient_type</code> attribute. If the <code>sender_batch_header</code> omits the <code>recipient_type</code> attribute, each payout item must include its own <code>recipient_type</code> value. */
  recipient_type?: string;
  amount: Currency;
  /** The sender-specified note for notifications. Supports up to 4000 ASCII characters and 1000 non-ASCII characters. */
  note?: string;
  /** The receiver of the payment. Corresponds to the `recipient_type` value in the request. Max value of up to 127 single-byte characters. */
  receiver: string;
  /** The sender-specified ID number. Tracks the payout in an accounting system. */
  sender_item_id?: string;
  /** The recipient wallet. */
  recipient_wallet?: string;
  alternate_notification_method?: AlternateNotificationMethod;
  notification_language?: Language;
  application_context?: ApplicationContext;
  purpose?: PurposeEnum;
};

/** An array of individual payout items. */
export type PayoutItemRequestList = PayoutItemRequest[];

export type RecipientEnum = "EMAIL" | "PHONE" | "PAYPAL_ID";

/** The sender-provided header for a payout request. */
export type PayoutSenderBatchHeader = {
  /** The sender-specified ID number. Tracks the payout in an accounting system.<blockquote><strong>Note:</strong> <p>PayPal does not process duplicate payouts. If you specify a <code>sender_batch_id</code> that was used in the last 30 days, the API rejects the request with an error message that shows the duplicate <code>sender_batch_id</code> and includes a HATEOAS link to the original payout with the same <code>sender_batch_id</code>.</p><p>If you receive an HTTP <code>5<i>nn</i></code> status code, you can safely retry the request with the same <code>sender_batch_id</code>. The API completes a payment only once for a <code>sender_batch_id</code> that is used within 30 days.</p></blockquote> */
  sender_batch_id?: string;
  recipient_type?: RecipientEnum;
  /** The subject line for the email that PayPal sends when payment for a payout item completes. The subject line is the same for all recipients. Value is an alphanumeric string with a maximum length of 255 single-byte characters. */
  email_subject?: string;
  /** The email message that PayPal sends when the payout item completes. The message is the same for all recipients. */
  email_message?: string;
};

/** The payout header that is returned in response to a payout header request. Shows details for an entire payout request. */
export type PayoutBatchHeader = {
  /** The PayPal-generated ID for a payout. */
  payout_batch_id: string;
  batch_status: BatchEnum;
  /**
   * The date and time when processing for the payout began, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6).
   *
   * @format date-time
   */
  time_created?: string;
  /**
   * The date and time when processing for the payout was completed, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6).
   *
   * @format date-time
   */
  time_completed?: string;
  /**
   * The date and time when the payout was closed, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). A payout is considered closed when all items in a batch are processed and the available balance from the temporary hold is released.
   *
   * @format date-time
   */
  time_closed?: string;
  sender_batch_header: PayoutSenderBatchHeader;
  funding_source?: FundingSource;
  amount?: Currency;
  fees?: Currency;
};

/** The payout header that is returned in response to a payout header request. Shows details for an entire payout request. */
export type PayoutHeader = {
  /** The PayPal-generated ID for a payout. */
  payout_batch_id: string;
  batch_status: BatchEnum;
  /**
   * The date and time when processing for the payout began, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6).
   *
   * @format date-time
   */
  time_created?: string;
  sender_batch_header: PayoutSenderBatchHeader;
};

/** The create payout response. */
export type Payout = {
  batch_header?: PayoutHeader;
  links?: DefinitionsLinkDescriptionList;
};

export type RecipientWalletEnum = "PAYPAL" | "VENMO";

/** The details for a sender-created payout to a single recipient. */
export type PayoutItemDetail = {
  recipient_type?: RecipientEnum;
  amount: Currency;
  /** The sender-specified note for notifications. Supports up to 4000 ASCII characters and 1000 non-ASCII characters. */
  note?: string;
  /** The receiver of the payment. Corresponds to the `recipient_type` value in the request. */
  receiver: string;
  /** A sender-specified ID number. Tracks the payout in an accounting system. */
  sender_item_id?: string;
  recipient_name?: Name;
  recipient_wallet?: RecipientWalletEnum;
  purpose?: PurposeEnum;
};

/** The sender-provided payout header for a payout request. */
export type SenderBatchHeader = {
  /** A sender-specified ID number. Tracks the payout in an accounting system.<blockquote><strong>Note:</strong> <p>PayPal does not process duplicate payouts. If you specify a <code>sender_batch_id</code> that was used in the last 30 days, the API rejects the request with an error message that shows the duplicate <code>sender_batch_id</code> and includes a HATEOAS link to the original payout with the same <code>sender_batch_id</code>.</p><p>If you receive an HTTP <code>5<i>nn</i></code> status code, you can safely retry the request with the same <code>sender_batch_id</code>. The API completes a payment only once for a <code>sender_batch_id</code> that is used within 30 days.</p></blockquote> */
  sender_batch_id?: string;
  /** The ID type that identifies the recipient of the payment. For example, <code>EMAIL</code>. */
  recipient_type?: string;
  /** The subject line for the email that PayPal sends when payment for a payout item completes. The subject line is the same for all recipients. Value is an alphanumeric string of up to 255 single-byte characters. */
  email_subject?: string;
  /** The email message that PayPal sends when the payout item completes. The message is the same for all recipients. */
  email_message?: string;
  /** The payouts and item-level notes are concatenated in the email. The maximum combined length of the notes is 1000 characters. */
  note?: string;
};

/** The create payout request. */
export type CreatePayoutRequest = {
  sender_batch_header: SenderBatchHeader;
  items: PayoutItemRequestList;
};

export type TransactionEnum =
  | "SUCCESS"
  | "FAILED"
  | "PENDING"
  | "UNCLAIMED"
  | "RETURNED"
  | "ONHOLD"
  | "BLOCKED"
  | "REFUNDED"
  | "REVERSED";

/** The payout item status and other details. */
export type PayoutBatchItems = {
  /** The ID for the payout item. Viewable when you show details for a payout. */
  payout_item_id: string;
  /** The PayPal-generated ID for the transaction. */
  transaction_id?: string;
  /** The unique PayPal-generated common ID created to link sender side and receiver side transaction. Used for tracking. */
  activity_id?: string;
  transaction_status?: TransactionEnum;
  payout_item_fee?: Currency;
  /** The PayPal-generated ID for the payout. */
  payout_batch_id: string;
  payout_item: PayoutItemDetail;
  currency_conversion?: PayoutCurrencyConversion;
  /**
   * The date and time when this item was last processed, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6).
   *
   * @format date-time
   */
  time_processed?: string;
  errors?: Error;
  links?: PayoutBatchItemsDefinitionsLinkDescriptionList;
};

/** An array of individual items. */
export type PayoutBatchItemsList = PayoutBatchItems[];

/** The PayPal-generated batch status. */
export type PayoutBatch = {
  /** The total number of items in the full result list. */
  total_items?: number;
  /** The total number of pages. */
  total_pages?: number;
  batch_header?: PayoutBatchHeader;
  items?: PayoutBatchItemsList;
  links?: PayoutBatchDefinitionsLinkDescriptionList;
};

/** The payout item status and other details. A <code>payout_item_id</code> helps you identify denied payments. If a payment is denied, you can use the <code>payout_item_id</code> to identify the payment even if it lacks a <code>transaction_id</code>. */
export type PayoutItem = {
  /** The ID for the payout item. Visible when you show details for a payout. */
  payout_item_id: string;
  /** The PayPal-generated ID for the transaction. */
  transaction_id?: string;
  /** The unique PayPal-generated common ID that links the sender- and receiver-side transactions. Used for tracking. */
  activity_id?: string;
  transaction_status?: TransactionEnum;
  payout_item_fee?: Currency;
  /** The PayPal-generated ID for the payout batch. */
  payout_batch_id: string;
  /** A sender-specified ID. Tracks the payout in an accounting system. Should be unique within 30 days. */
  sender_batch_id?: string;
  payout_item: PayoutItemDetail;
  currency_conversion?: PayoutCurrencyConversion;
  /**
   * The date and time when this item was last processed, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6).
   *
   * @format date-time
   */
  time_processed?: string;
  errors?: Error;
  links?: PayoutItemDefinitionsLinkDescriptionList;
};

export const ApplicationContextSchema: z.ZodType<ApplicationContext> = z.object({
  social_feed_privacy: z.string().regex(new RegExp("^.*$")).min(1).max(15).default("PRIVATE").optional(),
  holler_url: z.string().min(1).max(1000).optional(),
  logo_url: z.string().min(0).max(1000).optional(),
});

export const BatchEnumSchema: z.ZodType<BatchEnum> = z.enum(["DENIED", "PENDING", "PROCESSING", "SUCCESS", "CANCELED"]);

export const CurrencySchema: z.ZodType<Currency> = z.object({
  currency: z.string(),
  value: z.string(),
});

export const ErrorDetails2Schema: z.ZodType<ErrorDetails2> = z.object({
  field: z.string().optional(),
  value: z.string().optional(),
  location: z.string().default("body").optional(),
  issue: z.string(),
  description: z.string().optional(),
});

export const ErrorDetailsListSchema: z.ZodType<ErrorDetailsList> = z.array(ErrorDetails2Schema);

export const ErrorLinkDescriptionSchema: z.ZodType<ErrorLinkDescription> = z.object({
  href: z.string().regex(new RegExp("^.*$")).min(0).max(20000),
  rel: z.string().regex(new RegExp("^.*$")).min(0).max(100),
  method: z.enum(["GET", "POST", "PUT", "DELETE", "PATCH"]).optional(),
});

export const Error500Schema: z.ZodType<Error500> = z.object({
  name: z.enum(["INTERNAL_SERVER_ERROR"]).optional(),
  message: z.enum(["An internal server error occurred."]).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error503Schema: z.ZodType<Error503> = z.object({
  name: z.enum(["SERVICE_UNAVAILABLE"]).optional(),
  message: z.enum(["Service Unavailable."]).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const ErrorLocationSchema: z.ZodType<ErrorLocation> = z.enum(["body", "path", "query"]);

export const ErrorDetailsSchema: z.ZodType<ErrorDetails> = z.object({
  field: z.string().optional(),
  value: z.string().optional(),
  location: ErrorLocationSchema.optional(),
  issue: z.string(),
  description: z.string().optional(),
});

export const Error400Schema: z.ZodType<Error400> = z.object({
  name: z.enum(["INVALID_REQUEST"]).optional(),
  message: z.enum(["Request is not well-formed, syntactically incorrect, or violates schema."]).optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error401Schema: z.ZodType<Error401> = z.object({
  name: z.enum(["AUTHENTICATION_FAILURE"]).optional(),
  message: z.enum(["Authentication failed due to missing authorization header, or invalid authentication credentials."])
    .optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error403Schema: z.ZodType<Error403> = z.object({
  name: z.enum(["NOT_AUTHORIZED"]).optional(),
  message: z.enum(["Authorization failed due to insufficient permissions."]).optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error404Schema: z.ZodType<Error404> = z.object({
  name: z.enum(["RESOURCE_NOT_FOUND"]).optional(),
  message: z.enum(["The specified resource does not exist."]).optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error409Schema: z.ZodType<Error409> = z.object({
  name: z.enum(["RESOURCE_CONFLICT"]).optional(),
  message: z.enum(["The server has detected a conflict while processing this request."]).optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error415Schema: z.ZodType<Error415> = z.object({
  name: z.enum(["UNSUPPORTED_MEDIA_TYPE"]).optional(),
  message: z.enum(["The server does not support the request payload's media type."]).optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error422Schema: z.ZodType<Error422> = z.object({
  name: z.enum(["UNPROCESSABLE_ENTITY"]).optional(),
  message: z.enum([
    "The requested action could not be performed, semantically incorrect, or failed business validation.",
  ]).optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const ErrorDefaultSchema: z.ZodType<ErrorDefault> = z.union([
  Error400Schema,
  Error401Schema,
  Error403Schema,
  Error404Schema,
  Error409Schema,
  Error415Schema,
  Error422Schema,
  Error500Schema,
  Error503Schema,
]);

export const FundingSourceSchema: z.ZodType<FundingSource> = z.enum(["BALANCE"]);

export const LanguageSchema: z.ZodType<Language> = z.string().regex(
  new RegExp("^[a-z]{2}(?:-[A-Z][a-z]{3})?(?:-(?:[A-Z]{2}))?$"),
).min(2).max(10);

export const LinkDescriptionSchema: z.ZodType<LinkDescription> = z.object({
  href: z.string(),
  rel: z.string(),
  method: z.enum(["GET", "POST", "PUT", "DELETE", "HEAD", "CONNECT", "OPTIONS", "PATCH"]).optional(),
});

export const DefinitionsLinkDescriptionListSchema: z.ZodType<DefinitionsLinkDescriptionList> = z.array(
  LinkDescriptionSchema,
).min(1).max(15000);

export const LinkDescriptionListSchema: z.ZodType<LinkDescriptionList> = z.array(LinkDescriptionSchema);

export const ErrorSchema: z.ZodType<Error> = z.object({
  name: z.string(),
  message: z.string(),
  debug_id: z.string(),
  information_link: z.string().optional(),
  details: ErrorDetailsListSchema.optional(),
  links: LinkDescriptionListSchema.optional(),
});

export const NameSchema: z.ZodType<Name> = z.object({
  prefix: z.string().max(140).optional(),
  given_name: z.string().max(140).optional(),
  surname: z.string().max(140).optional(),
  middle_name: z.string().max(140).optional(),
  suffix: z.string().max(140).optional(),
  alternate_full_name: z.string().max(300).optional(),
  full_name: z.string().max(300).optional(),
});

export const PayoutBatchDefinitionsLinkDescriptionListSchema: z.ZodType<PayoutBatchDefinitionsLinkDescriptionList> = z
  .array(LinkDescriptionSchema).min(0).max(15000);

export const PayoutBatchItemsDefinitionsLinkDescriptionListSchema: z.ZodType<
  PayoutBatchItemsDefinitionsLinkDescriptionList
> = z.array(LinkDescriptionSchema).min(0).max(15000);

export const PayoutCurrencyConversionSchema: z.ZodType<PayoutCurrencyConversion> = z.object({
  from_amount: CurrencySchema.optional(),
  to_amount: CurrencySchema.optional(),
  exchange_rate: z.string().regex(new RegExp("^.*$")).min(0).max(30).optional(),
});

export const PayoutItemDefinitionsLinkDescriptionListSchema: z.ZodType<PayoutItemDefinitionsLinkDescriptionList> = z
  .array(LinkDescriptionSchema).min(0).max(15000);

export const PhoneSchema: z.ZodType<Phone> = z.object({
  country_code: z.string().regex(new RegExp("^[0-9]{1,3}?$")).min(1).max(3),
  national_number: z.string().regex(new RegExp("^[0-9]{1,14}?$")).min(1).max(14),
  extension_number: z.string().regex(new RegExp("^[0-9]{1,15}?$")).min(1).max(15).optional(),
});

export const AlternateNotificationMethodSchema: z.ZodType<AlternateNotificationMethod> = z.object({
  phone: PhoneSchema.optional(),
});

export const PurposeEnumSchema: z.ZodType<PurposeEnum> = z.enum([
  "AWARDS",
  "PRIZES",
  "DONATIONS",
  "GOODS",
  "SERVICES",
  "REBATES",
  "CASHBACK",
  "DISCOUNTS",
  "NON_GOODS_OR_SERVICES",
]);

export const PayoutItemRequestSchema: z.ZodType<PayoutItemRequest> = z.object({
  recipient_type: z.string().regex(new RegExp("^.*$")).min(0).max(13).optional(),
  amount: CurrencySchema,
  note: z.string().regex(new RegExp("^.*$")).min(0).max(4000).optional(),
  receiver: z.string().regex(new RegExp("^.*$")).min(0).max(127),
  sender_item_id: z.string().regex(new RegExp("^.*$")).min(0).max(63).optional(),
  recipient_wallet: z.string().regex(new RegExp("^.*$")).min(0).max(36).default("PAYPAL").optional(),
  alternate_notification_method: AlternateNotificationMethodSchema.optional(),
  notification_language: LanguageSchema.optional(),
  application_context: ApplicationContextSchema.optional(),
  purpose: PurposeEnumSchema.optional(),
});

export const PayoutItemRequestListSchema: z.ZodType<PayoutItemRequestList> = z.array(PayoutItemRequestSchema).min(1)
  .max(15000);

export const RecipientEnumSchema: z.ZodType<RecipientEnum> = z.enum(["EMAIL", "PHONE", "PAYPAL_ID"]);

export const PayoutSenderBatchHeaderSchema: z.ZodType<PayoutSenderBatchHeader> = z.object({
  sender_batch_id: z.string().regex(new RegExp("^.*$")).min(0).max(256).optional(),
  recipient_type: RecipientEnumSchema.optional(),
  email_subject: z.string().regex(new RegExp("^.*$")).min(0).max(255).optional(),
  email_message: z.string().regex(new RegExp("^.*$")).min(0).max(1000).optional(),
});

export const PayoutBatchHeaderSchema: z.ZodType<PayoutBatchHeader> = z.object({
  payout_batch_id: z.string().regex(new RegExp("^.*$")).min(0).max(30),
  batch_status: BatchEnumSchema,
  time_created: z.string().min(0).max(100).optional(),
  time_completed: z.string().min(0).max(100).optional(),
  time_closed: z.string().min(0).max(100).optional(),
  sender_batch_header: PayoutSenderBatchHeaderSchema,
  funding_source: FundingSourceSchema.optional(),
  amount: CurrencySchema.optional(),
  fees: CurrencySchema.optional(),
});

export const PayoutHeaderSchema: z.ZodType<PayoutHeader> = z.object({
  payout_batch_id: z.string().regex(new RegExp("^.*$")).min(0).max(30),
  batch_status: BatchEnumSchema,
  time_created: z.string().min(0).max(100).optional(),
  sender_batch_header: PayoutSenderBatchHeaderSchema,
});

export const PayoutSchema: z.ZodType<Payout> = z.object({
  batch_header: PayoutHeaderSchema.optional(),
  links: DefinitionsLinkDescriptionListSchema.optional(),
});

export const RecipientWalletEnumSchema: z.ZodType<RecipientWalletEnum> = z.enum(["PAYPAL", "VENMO"]);

export const PayoutItemDetailSchema: z.ZodType<PayoutItemDetail> = z.object({
  recipient_type: RecipientEnumSchema.optional(),
  amount: CurrencySchema,
  note: z.string().regex(new RegExp("^.*$")).min(0).max(4000).optional(),
  receiver: z.string().regex(new RegExp("^.*$")).min(0).max(127),
  sender_item_id: z.string().regex(new RegExp("^.*$")).min(0).max(63).optional(),
  recipient_name: NameSchema.optional(),
  recipient_wallet: RecipientWalletEnumSchema.optional(),
  purpose: PurposeEnumSchema.optional(),
});

export const SenderBatchHeaderSchema: z.ZodType<SenderBatchHeader> = z.object({
  sender_batch_id: z.string().regex(new RegExp("^.*$")).min(0).max(256).optional(),
  recipient_type: z.string().regex(new RegExp("^.*$")).min(0).max(13).optional(),
  email_subject: z.string().regex(new RegExp("^.*$")).min(0).max(255).optional(),
  email_message: z.string().regex(new RegExp("^.*$")).min(0).max(1000).optional(),
  note: z.string().regex(new RegExp("^.*$")).min(0).max(1000).optional(),
});

export const CreatePayoutRequestSchema: z.ZodType<CreatePayoutRequest> = z.object({
  sender_batch_header: SenderBatchHeaderSchema,
  items: PayoutItemRequestListSchema,
});

export const TransactionEnumSchema: z.ZodType<TransactionEnum> = z.enum([
  "SUCCESS",
  "FAILED",
  "PENDING",
  "UNCLAIMED",
  "RETURNED",
  "ONHOLD",
  "BLOCKED",
  "REFUNDED",
  "REVERSED",
]);

export const PayoutBatchItemsSchema: z.ZodType<PayoutBatchItems> = z.object({
  payout_item_id: z.string().regex(new RegExp("^.*$")).min(0).max(30),
  transaction_id: z.string().regex(new RegExp("^.*$")).min(0).max(30).optional(),
  activity_id: z.string().regex(new RegExp("^.*$")).min(0).max(30).optional(),
  transaction_status: TransactionEnumSchema.optional(),
  payout_item_fee: CurrencySchema.optional(),
  payout_batch_id: z.string().regex(new RegExp("^.*$")).min(0).max(30),
  payout_item: PayoutItemDetailSchema,
  currency_conversion: PayoutCurrencyConversionSchema.optional(),
  time_processed: z.string().min(0).max(100).optional(),
  errors: ErrorSchema.optional(),
  links: PayoutBatchItemsDefinitionsLinkDescriptionListSchema.optional(),
});

export const PayoutBatchItemsListSchema: z.ZodType<PayoutBatchItemsList> = z.array(PayoutBatchItemsSchema).min(0).max(
  15000,
);

export const PayoutBatchSchema: z.ZodType<PayoutBatch> = z.object({
  total_items: z.number().int().min(0).max(15000).optional(),
  total_pages: z.number().int().min(0).max(1000).optional(),
  batch_header: PayoutBatchHeaderSchema.optional(),
  items: PayoutBatchItemsListSchema.optional(),
  links: PayoutBatchDefinitionsLinkDescriptionListSchema.optional(),
});

export const PayoutItemSchema: z.ZodType<PayoutItem> = z.object({
  payout_item_id: z.string().regex(new RegExp("^.*$")).min(0).max(30),
  transaction_id: z.string().regex(new RegExp("^.*$")).min(0).max(30).optional(),
  activity_id: z.string().regex(new RegExp("^.*$")).min(0).max(30).optional(),
  transaction_status: TransactionEnumSchema.optional(),
  payout_item_fee: CurrencySchema.optional(),
  payout_batch_id: z.string().regex(new RegExp("^.*$")).min(0).max(30),
  sender_batch_id: z.string().regex(new RegExp("^.*$")).min(0).max(256).optional(),
  payout_item: PayoutItemDetailSchema,
  currency_conversion: PayoutCurrencyConversionSchema.optional(),
  time_processed: z.string().min(1).max(100).optional(),
  errors: ErrorSchema.optional(),
  links: PayoutItemDefinitionsLinkDescriptionListSchema.optional(),
});

/**
 * Create batch payout
 *
 * Creates a batch payout. In the JSON request body, pass a `sender_batch_header` and an `items` array. The `sender_batch_header` defines how to handle the payout. The `items` array defines the payout items.<br/>You can make payouts to one or more recipients.<blockquote><strong>Notes:</strong> <ul><li><p>PayPal does not process duplicate payouts. If you specify a <code>sender_batch_id</code> that was used in the last 30 days, the API rejects the request with an error message that shows the duplicate <code>sender_batch_id</code> and includes a HATEOAS link to the original payout with the same <code>sender_batch_id</code>.</p><p>If you receive an HTTP <code>5<i>nn</i></code> status code, you can safely retry the request with the same <code>sender_batch_id</code>.</p></li><li><p>The Payouts API does not support build notation (BN) codes. In a future Payouts release, you can optionally provide BN codes in the <code>PayPal-Partner-Attribution-Id</code> request header.</p><p>For information about the <code>PayPal-Partner-Attribution-Id</code> header, see <a href="/api/rest/requests/#http-request-headers">HTTP request headers</a>. To learn about or request a BN code, contact your partner manager or see <a href="https://www.paypal.com/us/webapps/mpp/partner-program">PayPal Partner Program</a>.</p></li></ul></blockquote>
 */
export const payoutsPost = (config: OpenAPIClientConfig, request: {
  headers?: {
    /** The server stores keys for 30 days. */
    "PayPal-Request-Id"?: string;
  };
  body: CreatePayoutRequest;
}): OpenAPIResponsePromise<
  OpenAPIResponses<{
    /** A successful request returns the HTTP <code>201 Created</code> status code and a JSON response body that shows the ID for the payout and payout details. To show payout status, use the <code>payout_batch_id</code> value that appears in the response. If the initial scan that checks for syntax errors, missing or duplicated keywords, and more succeeds, the <code>batch_status</code> is <code>PENDING</code>. The initial scan checks for syntax errors and missing or duplicated keywords. The API does not immediately validate some payout item values, such as the receiver phone numbers. */
    201: {
      body: Payout;
    };
    /** Request is not well-formed, syntactically incorrect, or violates schema. */
    400: {
      body: Error;
    };
    /** Authorization failed due to insufficient permissions. */
    403: {
      body: Error;
    };
    /** An internal server error has occurred. */
    500: {
      body: Error;
    };
    /** The error response. */
    "default": {
      body: Error;
    };
  }>
> =>
  openAPIFetch(
    config,
    {
      path: "/v1/payments/payouts",
      method: "post",
      requestSchema: z.object({
        headers: z.object({
          "PayPal-Request-Id": z.string().regex(new RegExp("^.*$")).min(1).max(1000).optional(),
        }).optional(),
        body: CreatePayoutRequestSchema,
      }),
      responseSchema: {
        201: z.object({ body: PayoutSchema }),
        400: z.object({ body: ErrorSchema }),
        403: z.object({ body: ErrorSchema }),
        500: z.object({ body: ErrorSchema }),
        "default": z.object({ body: ErrorSchema }),
      },
    },
    request,
  ) as any;

/**
 * Show payout batch details
 *
 * Shows the latest status of a batch payout. Includes the transaction status and other data for individual payout items.
 */
export const payoutsGet = (config: OpenAPIClientConfig, request: {
  path: {
    /** The ID of the payout for which to show details. */
    id: string;
  };
  query?: {
    /** Shows details for only the specified fields. */
    fields?: string;
    /** A non-zero integer representing the page of the results. */
    page?: number;
    /** The maximum number of results to return at one time. Value is a non-negative, non-zero integer. If the user chooses pagination, the maximum page is `1000`. */
    page_size?: number;
    /** Indicates whether to show the total items and total pages count in the response. */
    total_required?: boolean;
  };
}): OpenAPIResponsePromise<
  OpenAPIResponses<{
    /** A successful request returns the HTTP `200 OK` status code and a JSON response body that shows batch payout details. */
    200: {
      body: PayoutBatch;
    };
    /** Resource Not Found. */
    404: {
      body: Error;
    };
    /** An internal server error has occurred. */
    500: {
      body: Error;
    };
    /** The error response. */
    "default": {
      body: Error;
    };
  }>
> =>
  openAPIFetch(
    config,
    {
      path: "/v1/payments/payouts/{id}",
      method: "get",
      requestSchema: z.object({
        path: z.object({
          id: z.string().regex(new RegExp("^.*$")).min(1).max(1000),
        }),
        query: z.object({
          fields: z.string().regex(new RegExp("^.*$")).min(1).max(1000).optional(),
          page: z.number().int().min(0).max(1000).default(1).optional(),
          page_size: z.number().int().min(0).max(1000).optional(),
          total_required: z.boolean().optional(),
        }).optional(),
      }),
      responseSchema: {
        200: z.object({ body: PayoutBatchSchema }),
        404: z.object({ body: ErrorSchema }),
        500: z.object({ body: ErrorSchema }),
        "default": z.object({ body: ErrorSchema }),
      },
    },
    request,
  ) as any;

/**
 * Show payout item details
 *
 * Shows details for a payout item, by ID. A <code>payout_item_id</code> helps you identify denied payments. If a payment is denied, you can use the <code>payout_item_id</code> to identify the payment even if it lacks a <code>transaction_id</code>.
 */
export const payoutsItemGet = (config: OpenAPIClientConfig, request: {
  path: {
    /** The ID of the payout item to cancel. */
    payout_item_id: string;
  };
}): OpenAPIResponsePromise<
  OpenAPIResponses<{
    /** A successful request returns the HTTP <code>200 OK</code> status code and a JSON response body with a <code>payout_item_details</code> object, which contains data about a payout item including the transaction status. */
    200: {
      body: PayoutItem;
    };
    /** Resource Not Found. */
    404: {
      body: Error;
    };
    /** An internal server error has occurred. */
    500: {
      body: Error;
    };
    /** The error response. */
    "default": {
      body: Error;
    };
  }>
> =>
  openAPIFetch(
    config,
    {
      path: "/v1/payments/payouts-item/{payout_item_id}",
      method: "get",
      requestSchema: z.object({
        path: z.object({
          payout_item_id: z.string().regex(new RegExp("^.*$")).min(1).max(32),
        }),
      }),
      responseSchema: {
        200: z.object({ body: PayoutItemSchema }),
        404: z.object({ body: ErrorSchema }),
        500: z.object({ body: ErrorSchema }),
        "default": z.object({ body: ErrorSchema }),
      },
    },
    request,
  ) as any;

/**
 * Cancel unclaimed payout item
 *
 * Cancels an unclaimed payout item, by ID. If no one claims the unclaimed item within 30 days, the API automatically returns the funds to the sender. Use this call to cancel the unclaimed item before the automatic 30-day refund. You can cancel payout items with a <code>transaction_status</code> of <code>UNCLAIMED</code>.
 */
export const payoutsItemCancel = (config: OpenAPIClientConfig, request: {
  path: {
    /** The ID of the payout item to cancel. */
    payout_item_id: string;
  };
}): OpenAPIResponsePromise<
  OpenAPIResponses<{
    /** A successful request returns the HTTP `200 OK` status code with a JSON response body that shows payout item details. */
    200: {
      body: PayoutItem;
    };
    /** Request is not well-formed, syntactically incorrect, or violates schema. */
    400: {
      body: Error;
    };
    /** Resource Not Found. */
    404: {
      body: Error;
    };
    /** An internal server error has occurred. */
    500: {
      body: Error;
    };
    /** The error response. */
    "default": {
      body: Error;
    };
  }>
> =>
  openAPIFetch(
    config,
    {
      path: "/v1/payments/payouts-item/{payout_item_id}/cancel",
      method: "post",
      requestSchema: z.object({
        path: z.object({
          payout_item_id: z.string().regex(new RegExp("^.*$")).min(1).max(32),
        }),
      }),
      responseSchema: {
        200: z.object({ body: PayoutItemSchema }),
        400: z.object({ body: ErrorSchema }),
        404: z.object({ body: ErrorSchema }),
        500: z.object({ body: ErrorSchema }),
        "default": z.object({ body: ErrorSchema }),
      },
    },
    request,
  ) as any;

export { createCustomClient } from "jsr:@brad-jones/deno-net-open-api-client@0.2.5";

/**
 * Create a client with all available operations.
 * This is convenient but will include all operations in your bundle.
 * For better tree-shaking, use createCustomClient() to select specific operations.
 */
export function createClient(config: OpenAPIClientConfig) {
  return createCustomClient(config, { payoutsPost, payoutsGet, payoutsItemGet, payoutsItemCancel });
}
