// deno-lint-ignore-file no-explicit-any
// This file was auto-generated by @brad-jones/open-api-client

import {
  type OpenAPIClientConfig,
  openAPIFetch,
  type OpenAPIResponses,
} from "jsr:@brad-jones/deno-net-open-api-client@0.2.2";
import { z } from "npm:zod@^4.1.12";

/** Captures either a portion or the full authorized amount of an authorized payment. */
export type _2 = Record<string, never>;

export type _400 = unknown;

export type _401 = unknown;

export type _403 = unknown;

export type _404 = unknown;

export type _409 = unknown;

export type _422 = unknown;

/**
 * The account identifier for a PayPal account.
 *
 * @format ppaas_payer_id_v3
 */
export type AccountId = string;

/** The details of the authorized payment status. */
export type AuthorizationStatusDetails = {
  reason?: "PENDING_REVIEW" | "DECLINED_BY_RISK_FRAUD_FILTERS";
};

/** The status fields and status details for an authorized payment. */
export type AuthorizationStatus = {
  status?: "CREATED" | "CAPTURED" | "DENIED" | "PARTIALLY_CAPTURED" | "VOIDED" | "PENDING";
  status_details?: AuthorizationStatusDetails;
};

export type AuthorizationsReauthorize400 = unknown;

export type AuthorizationsReauthorize422 = unknown;

export type AuthorizationsVoid422 = unknown;

/** The details of the captured payment status. */
export type CaptureStatusDetails = {
  reason?:
    | "BUYER_COMPLAINT"
    | "CHARGEBACK"
    | "ECHECK"
    | "INTERNATIONAL_WITHDRAWAL"
    | "OTHER"
    | "PENDING_REVIEW"
    | "RECEIVING_PREFERENCE_MANDATES_MANUAL_ACTION"
    | "REFUNDED"
    | "TRANSACTION_APPROVED_AWAITING_FUNDING"
    | "UNILATERAL"
    | "VERIFICATION_REQUIRED"
    | "DECLINED_BY_RISK_FRAUD_FILTERS";
};

/** The status and status details of a captured payment. */
export type CaptureStatus = {
  status?: "COMPLETED" | "DECLINED" | "PARTIALLY_REFUNDED" | "PENDING" | "REFUNDED" | "FAILED";
  status_details?: CaptureStatusDetails;
};

export type CapturesRefund400 = unknown;

export type CapturesRefund422 = unknown;

export type CardBrand =
  | "VISA"
  | "MASTERCARD"
  | "DISCOVER"
  | "AMEX"
  | "SOLO"
  | "JCB"
  | "STAR"
  | "DELTA"
  | "SWITCH"
  | "MAESTRO"
  | "CB_NATIONALE"
  | "CONFIGOGA"
  | "CONFIDIS"
  | "ELECTRON"
  | "CETELEM"
  | "CHINA_UNION_PAY"
  | "DINERS"
  | "ELO"
  | "HIPER"
  | "HIPERCARD"
  | "RUPAY"
  | "GE"
  | "SYNCHRONY"
  | "EFTPOS"
  | "UNKNOWN";

/** The [three-character ISO-4217 currency code](/api/rest/reference/currency-codes/) that identifies the currency. */
export type CurrencyCode = string;

/**
 * The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional.<blockquote><strong>Note:</strong> The regular expression provides guidance but does not reject all invalid dates.</blockquote>
 *
 * @format ppaas_date_time_v3
 */
export type DateTime = string;

/** The date and time stamps that are common to authorized payment, captured payment, and refund transactions. */
export type ActivityTimestamps = {
  create_time?: DateTime;
  update_time?: DateTime;
};

export type DisbursementMode = "INSTANT" | "DELAYED";

export type DisputeCategories = "ITEM_NOT_RECEIVED" | "UNAUTHORIZED_TRANSACTION";

/** An array of conditions that are covered for the transaction. */
export type DisputeCategoriesList = DisputeCategories[];

/**
 * The internationalized email address.<blockquote><strong>Note:</strong> Up to 64 characters are allowed before and 255 characters are allowed after the <code>@</code> sign. However, the generally accepted maximum length for an email address is 254 characters. The pattern verifies that an unquoted <code>@</code> sign exists.</blockquote>
 *
 * @format merchant_common_email_address_v2
 */
export type Email = string;

/** The request-related [HATEOAS link](/api/rest/responses/#hateoas-links) information. */
export type ErrorLinkDescription = {
  /** The complete target URL. To make the related call, combine the method with this [URI Template-formatted](https://tools.ietf.org/html/rfc6570) link. For pre-processing, include the `$`, `(`, and `)` characters. The `href` is the key HATEOAS component that links a completed call with a subsequent call. */
  href: string;
  /** The [link relation type](https://tools.ietf.org/html/rfc5988#section-4), which serves as an ID for a link that unambiguously describes the semantics of the link. See [Link Relations](https://www.iana.org/assignments/link-relations/link-relations.xhtml). */
  rel: string;
  method?: "GET" | "POST" | "PUT" | "DELETE" | "PATCH";
};

/** This is either a system or application error, and generally indicates that although the client appeared to provide a correct request, something unexpected has gone wrong on the server. */
export type Error500 = {
  name?: "INTERNAL_SERVER_ERROR";
  message?: "An internal server error occurred.";
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** The server is temporarily unable to handle the request, for example, because of planned maintenance or downtime. */
export type Error503 = {
  name?: "SERVICE_UNAVAILABLE";
  message?: "Service Unavailable.";
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

export type ErrorLocation = "body" | "path" | "query";

/** The error details. Required for client-side `4XX` errors. */
export type ErrorDetails = {
  /** The field that caused the error. If this field is in the body, set this value to the field's JSON pointer value. Required for client-side errors. */
  field?: string;
  /** The value of the field that caused the error. */
  value?: string;
  location?: ErrorLocation;
  /** The unique, fine-grained application-level error code. */
  issue: string;
  /** The human-readable description for an issue. The description can change over the lifetime of an API, so clients must not depend on this value. */
  description?: string;
};

/** Request is not well-formed, syntactically incorrect, or violates schema. */
export type Error400 = {
  name?: "INVALID_REQUEST";
  message?: "Request is not well-formed, syntactically incorrect, or violates schema.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** Authentication failed due to missing Authorization header, or invalid authentication credentials. */
export type Error401 = {
  name?: "AUTHENTICATION_FAILURE";
  message?: "Authentication failed due to missing authorization header, or invalid authentication credentials.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** The client is not authorized to access this resource, although it may have valid credentials.  */
export type Error403 = {
  name?: "NOT_AUTHORIZED";
  message?: "Authorization failed due to insufficient permissions.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** The server has not found anything matching the request URI. This either means that the URI is incorrect or the resource is not available. */
export type Error404 = {
  name?: "RESOURCE_NOT_FOUND";
  message?: "The specified resource does not exist.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** The server has detected a conflict while processing this request. */
export type Error409 = {
  name?: "RESOURCE_CONFLICT";
  message?: "The server has detected a conflict while processing this request.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** The server does not support the request payload's media type. */
export type Error415 = {
  name?: "UNSUPPORTED_MEDIA_TYPE";
  message?: "The server does not support the request payload's media type.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** The requested action cannot be performed and may require interaction with APIs or processes outside of the current request. This is distinct from a 500 response in that there are no systemic problems limiting the API from performing the request. */
export type Error422 = {
  name?: "UNPROCESSABLE_ENTITY";
  message?: "The requested action could not be performed, semantically incorrect, or failed business validation.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

export type ErrorDefault =
  | Error400
  | Error401
  | Error403
  | Error404
  | Error409
  | Error415
  | Error422
  | Error500
  | Error503;

/** The exchange rate that determines the amount to convert from one currency to another currency. */
export type ExchangeRate = {
  source_currency?: CurrencyCode;
  target_currency?: CurrencyCode;
  /** The target currency amount. Equivalent to one unit of the source currency. Formatted as integer or decimal value with one to 15 digits to the right of the decimal point. */
  value?: string;
};

/** The request-related [HATEOAS link](/api/rest/responses/#hateoas-links) information. */
export type LinkDescription = {
  /** The complete target URL. To make the related call, combine the method with this [URI Template-formatted](https://tools.ietf.org/html/rfc6570) link. For pre-processing, include the `$`, `(`, and `)` characters. The `href` is the key HATEOAS component that links a completed call with a subsequent call. */
  href: string;
  /** The [link relation type](https://tools.ietf.org/html/rfc5988#section-4), which serves as an ID for a link that unambiguously describes the semantics of the link. See [Link Relations](https://www.iana.org/assignments/link-relations/link-relations.xhtml). */
  rel: string;
  method?: "GET" | "POST" | "PUT" | "DELETE" | "HEAD" | "CONNECT" | "OPTIONS" | "PATCH";
};

/** An array of related [HATEOAS links](/docs/api/reference/api-responses/#hateoas-links). */
export type LinkDescriptionList = LinkDescription[];

/** The currency and amount for a financial transaction, such as a balance or payment due. */
export type Money = {
  currency_code: CurrencyCode;
  /** The value, which might be:<ul><li>An integer for currencies like `JPY` that are not typically fractional.</li><li>A decimal fraction for currencies like `TND` that are subdivided into thousandths.</li></ul>For the required number of decimal places for a currency code, see [Currency Codes](/api/rest/reference/currency-codes/). */
  value: string;
};

/** The platform or partner fee, commission, or brokerage fee that is associated with the transaction. Not a separate or isolated transaction leg from the external perspective. The platform fee is limited in scope and is always associated with the original payment for the purchase unit. */
export type DefinitionsPlatformFee = {
  amount: Money;
};

/** Specifies the amount that the API caller will contribute to the refund being processed. The amount needs to be lower than platform_fees amount originally captured or the amount that is remaining if multiple refunds have been processed. This field is only applicable to merchants that have been enabled for PayPal Commerce Platform for Marketplaces and Platforms capability. Please speak to your account manager if you want to use this capability. */
export type DefinitionsPlatformFeeList = DefinitionsPlatformFee[];

/** The net amount. Returned when the currency of the refund is different from the currency of the PayPal account where the merchant holds their funds. */
export type NetAmountBreakdownItem = {
  payable_amount?: Money;
  converted_amount?: Money;
  exchange_rate?: ExchangeRate;
};

/** An array of breakdown values for the net amount. Returned when the currency of the refund is different from the currency of the PayPal account where the payee holds their funds. */
export type NetAmountBreakdownItemList = NetAmountBreakdownItem[];

/** Reference values used by the card network to identify a transaction. */
export type NetworkTransactionReference = {
  /** Transaction reference id returned by the scheme. For Visa and Amex, this is the "Tran id" field in response. For MasterCard, this is the "BankNet reference id" field in response. For Discover, this is the "NRID" field in response. The pattern we expect for this field from Visa/Amex/CB/Discover is numeric, Mastercard/BNPP is alphanumeric and Paysecure is alphanumeric with special character -. */
  id: string;
  /** The date that the transaction was authorized by the scheme. This field may not be returned for all networks. MasterCard refers to this field as "BankNet reference date. */
  date?: string;
  network?: CardBrand;
  /** Reference ID issued for the card transaction. This ID can be used to track the transaction across processors, card brands and issuing banks. */
  acquirer_reference_number?: string;
};

/** The details for the merchant who receives the funds and fulfills the order. The merchant is also known as the payee. */
export type PayeeBase = {
  email_address?: Email;
  merchant_id?: AccountId;
};

/** Any additional payments instructions during refund payment processing. This object is only applicable to merchants that have been enabled for PayPal Commerce Platform for Marketplaces and Platforms capability. Please speak to your account manager if you want to use this capability. */
export type PaymentInstruction2 = {
  platform_fees?: DefinitionsPlatformFeeList;
};

/** The platform or partner fee, commission, or brokerage fee that is associated with the transaction. Not a separate or isolated transaction leg from the external perspective. The platform fee is limited in scope and is always associated with the original payment for the purchase unit. */
export type PlatformFee = {
  amount: Money;
  payee?: PayeeBase;
};

/** An array of various fees, commissions, tips, or donations. This field is only applicable to merchants that been enabled for PayPal Complete Payments Platform for Marketplaces and Platforms capability. */
export type PaymentInstructionDefinitionPlatformFeeList = PlatformFee[];

/** Any additional payment instructions to be consider during payment processing. This processing instruction is applicable for Capturing an order or Authorizing an Order. */
export type PaymentInstruction = {
  platform_fees?: PaymentInstructionDefinitionPlatformFeeList;
  disbursement_mode?: DisbursementMode;
  /** FX identifier generated returned by PayPal to be used for payment processing in order to honor FX rate (for eligible integrations) to be used when amount is settled/received into the payee account. */
  payee_receivable_fx_rate_id?: string;
};

/** An array of platform or partner fees, commissions, or brokerage fees that associated with the captured payment. */
export type PlatformFeeList = PlatformFee[];

/** The processor response information for payment requests, such as direct credit card transactions. */
export type ProcessorResponse = {
  avs_code?:
    | "A"
    | "B"
    | "C"
    | "D"
    | "E"
    | "F"
    | "G"
    | "I"
    | "M"
    | "N"
    | "P"
    | "R"
    | "S"
    | "U"
    | "W"
    | "X"
    | "Y"
    | "Z"
    | "Null"
    | "0"
    | "1"
    | "2"
    | "3"
    | "4";
  cvv_code?: "E" | "I" | "M" | "N" | "P" | "S" | "U" | "X" | "All others" | "0" | "1" | "2" | "3" | "4";
  response_code?:
    | "0000"
    | "00N7"
    | "0100"
    | "0390"
    | "0500"
    | "0580"
    | "0800"
    | "0880"
    | "0890"
    | "0960"
    | "0R00"
    | "1000"
    | "10BR"
    | "1300"
    | "1310"
    | "1312"
    | "1317"
    | "1320"
    | "1330"
    | "1335"
    | "1340"
    | "1350"
    | "1352"
    | "1360"
    | "1370"
    | "1380"
    | "1382"
    | "1384"
    | "1390"
    | "1393"
    | "5100"
    | "5110"
    | "5120"
    | "5130"
    | "5135"
    | "5140"
    | "5150"
    | "5160"
    | "5170"
    | "5180"
    | "5190"
    | "5200"
    | "5210"
    | "5400"
    | "5500"
    | "5650"
    | "5700"
    | "5710"
    | "5800"
    | "5900"
    | "5910"
    | "5920"
    | "5930"
    | "5950"
    | "6300"
    | "7600"
    | "7700"
    | "7710"
    | "7800"
    | "7900"
    | "8000"
    | "8010"
    | "8020"
    | "8030"
    | "8100"
    | "8110"
    | "8220"
    | "9100"
    | "9500"
    | "9510"
    | "9520"
    | "9530"
    | "9540"
    | "9600"
    | "PCNR"
    | "PCVV"
    | "PP06"
    | "PPRN"
    | "PPAD"
    | "PPAB"
    | "PPAE"
    | "PPAG"
    | "PPAI"
    | "PPAR"
    | "PPAU"
    | "PPAV"
    | "PPAX"
    | "PPBG"
    | "PPC2"
    | "PPCE"
    | "PPCO"
    | "PPCR"
    | "PPCT"
    | "PPCU"
    | "PPD3"
    | "PPDC"
    | "PPDI"
    | "PPDV"
    | "PPDT"
    | "PPEF"
    | "PPEL"
    | "PPER"
    | "PPEX"
    | "PPFE"
    | "PPFI"
    | "PPFR"
    | "PPFV"
    | "PPGR"
    | "PPH1"
    | "PPIF"
    | "PPII"
    | "PPIM"
    | "PPIT"
    | "PPLR"
    | "PPLS"
    | "PPMB"
    | "PPMC"
    | "PPMD"
    | "PPNC"
    | "PPNL"
    | "PPNM"
    | "PPNT"
    | "PPPH"
    | "PPPI"
    | "PPPM"
    | "PPQC"
    | "PPRE"
    | "PPRF"
    | "PPRR"
    | "PPS0"
    | "PPS1"
    | "PPS2"
    | "PPS3"
    | "PPS4"
    | "PPS5"
    | "PPS6"
    | "PPSC"
    | "PPSD"
    | "PPSE"
    | "PPTE"
    | "PPTF"
    | "PPTI"
    | "PPTR"
    | "PPTT"
    | "PPTV"
    | "PPUA"
    | "PPUC"
    | "PPUE"
    | "PPUI"
    | "PPUP"
    | "PPUR"
    | "PPVC"
    | "PPVE"
    | "PPVT";
  payment_advice_code?:
    | "01"
    | "02"
    | "03"
    | "04"
    | "21"
    | "22"
    | "24"
    | "25"
    | "26"
    | "27"
    | "28"
    | "29"
    | "30"
    | "40"
    | "43";
};

/** Reauthorizes an authorized PayPal account payment, by ID. To ensure that funds are still available, reauthorize a payment after its initial three-day honor period expires. You can reauthorize a payment only once from days four to 29.<br/><br/>If 30 days have transpired since the date of the original authorization, you must create an authorized payment instead of reauthorizing the original authorized payment.<br/><br/>A reauthorized payment itself has a new honor period of three days.<br/><br/>You can reauthorize an authorized payment once. The allowed amount depends on context and geography, for example in US it is up to 115% of the original authorized amount, not to exceed an increase of $75 USD.<br/><br/>Supports only the `amount` request parameter. */
export type ReauthorizeRequest = {
  amount?: Money;
};

/** An array of platform or partner fees, commissions, or brokerage fees for the refund. */
export type RefundDefinitionsPlatformFeeList = PlatformFee[];

/** Refunds a captured payment, by ID. For a full refund, include an empty request body. For a partial refund, include an <code>amount</code> object in the request body. */
export type RefundRequest = {
  amount?: Money;
  /** The API caller-provided external ID. Used to reconcile API caller-initiated transactions with PayPal transactions. Appears in transaction and settlement reports. The pattern is defined by an external party and supports Unicode. */
  custom_id?: string;
  /** The API caller-provided external invoice ID for this order. The pattern is defined by an external party and supports Unicode. */
  invoice_id?: string;
  /** The reason for the refund. Appears in both the payer's transaction history and the emails that the payer receives. The pattern is defined by an external party and supports Unicode. */
  note_to_payer?: string;
  payment_instruction?: PaymentInstruction2;
};

/** The details of the refund status. */
export type RefundStatusDetails = {
  reason?: "ECHECK";
};

/** The refund status with details. */
export type RefundStatus = {
  status?: "CANCELLED" | "FAILED" | "PENDING" | "COMPLETED";
  status_details?: RefundStatusDetails;
};

/** Identifiers related to a specific resource. */
export type RelatedIds = {
  /** Order ID related to the resource. */
  order_id?: string;
  /** Authorization ID related to the resource. */
  authorization_id?: string;
  /** Capture ID related to the resource. */
  capture_id?: string;
};

/** The breakdown of the refund. */
export type SellerPayableBreakdown = {
  gross_amount?: Money;
  paypal_fee?: Money;
  paypal_fee_in_receivable_currency?: Money;
  net_amount?: Money;
  net_amount_in_receivable_currency?: Money;
  platform_fees?: RefundDefinitionsPlatformFeeList;
  net_amount_breakdown?: NetAmountBreakdownItemList;
  total_refunded_amount?: Money;
};

export type Refund = RefundStatus & unknown & ActivityTimestamps;

/** The level of protection offered as defined by [PayPal Seller Protection for Merchants](https://www.paypal.com/us/webapps/mpp/security/seller-protection). */
export type SellerProtection = {
  status?: "ELIGIBLE" | "PARTIALLY_ELIGIBLE" | "NOT_ELIGIBLE";
  dispute_categories?: DisputeCategoriesList;
};

export type Authorization = AuthorizationStatus & unknown & ActivityTimestamps;

/** The detailed breakdown of the capture activity. This is not available for transactions that are in pending state. */
export type SellerReceivableBreakdown = {
  gross_amount: Money;
  paypal_fee?: Money;
  paypal_fee_in_receivable_currency?: Money;
  net_amount?: Money;
  receivable_amount?: Money;
  exchange_rate?: ExchangeRate;
  platform_fees?: PlatformFeeList;
};

export type Capture = CaptureStatus & unknown & ActivityTimestamps;

/** The supplementary data. */
export type SupplementaryData = {
  related_ids?: RelatedIds;
};

export type Authorization2 = Authorization & unknown;

export type Capture2 = Capture & unknown;

/** The capture identification-related fields. Includes the invoice ID, custom ID, note to payer, and soft descriptor. */
export type SupplementaryPurchaseData = {
  /** The API caller-provided external invoice number for this order. Appears in both the payer's transaction history and the emails that the payer receives. */
  invoice_id?: string;
  /** An informational note about this settlement. Appears in both the payer's transaction history and the emails that the payer receives. */
  note_to_payer?: string;
};

export type CaptureRequest = SupplementaryPurchaseData & unknown & _2;

export const _2Schema: z.ZodType<_2> = z.object({});

export const _400Schema: z.ZodType<_400> = z.unknown();

export const _401Schema: z.ZodType<_401> = z.unknown();

export const _403Schema: z.ZodType<_403> = z.unknown();

export const _404Schema: z.ZodType<_404> = z.unknown();

export const _409Schema: z.ZodType<_409> = z.unknown();

export const _422Schema: z.ZodType<_422> = z.unknown();

export const AccountIdSchema: z.ZodType<AccountId> = z.string().regex(new RegExp("^[2-9A-HJ-NP-Z]{13}$")).min(13).max(
  13,
);

export const AuthorizationStatusDetailsSchema: z.ZodType<AuthorizationStatusDetails> = z.object({
  reason: z.enum(["PENDING_REVIEW", "DECLINED_BY_RISK_FRAUD_FILTERS"]).optional(),
});

export const AuthorizationStatusSchema: z.ZodType<AuthorizationStatus> = z.object({
  status: z.enum(["CREATED", "CAPTURED", "DENIED", "PARTIALLY_CAPTURED", "VOIDED", "PENDING"]).optional(),
  status_details: AuthorizationStatusDetailsSchema.optional(),
});

export const AuthorizationsReauthorize400Schema: z.ZodType<AuthorizationsReauthorize400> = z.unknown();

export const AuthorizationsReauthorize422Schema: z.ZodType<AuthorizationsReauthorize422> = z.unknown();

export const AuthorizationsVoid422Schema: z.ZodType<AuthorizationsVoid422> = z.unknown();

export const CaptureStatusDetailsSchema: z.ZodType<CaptureStatusDetails> = z.object({
  reason: z.enum([
    "BUYER_COMPLAINT",
    "CHARGEBACK",
    "ECHECK",
    "INTERNATIONAL_WITHDRAWAL",
    "OTHER",
    "PENDING_REVIEW",
    "RECEIVING_PREFERENCE_MANDATES_MANUAL_ACTION",
    "REFUNDED",
    "TRANSACTION_APPROVED_AWAITING_FUNDING",
    "UNILATERAL",
    "VERIFICATION_REQUIRED",
    "DECLINED_BY_RISK_FRAUD_FILTERS",
  ]).optional(),
});

export const CaptureStatusSchema: z.ZodType<CaptureStatus> = z.object({
  status: z.enum(["COMPLETED", "DECLINED", "PARTIALLY_REFUNDED", "PENDING", "REFUNDED", "FAILED"]).optional(),
  status_details: CaptureStatusDetailsSchema.optional(),
});

export const CapturesRefund400Schema: z.ZodType<CapturesRefund400> = z.unknown();

export const CapturesRefund422Schema: z.ZodType<CapturesRefund422> = z.unknown();

export const CardBrandSchema: z.ZodType<CardBrand> = z.enum([
  "VISA",
  "MASTERCARD",
  "DISCOVER",
  "AMEX",
  "SOLO",
  "JCB",
  "STAR",
  "DELTA",
  "SWITCH",
  "MAESTRO",
  "CB_NATIONALE",
  "CONFIGOGA",
  "CONFIDIS",
  "ELECTRON",
  "CETELEM",
  "CHINA_UNION_PAY",
  "DINERS",
  "ELO",
  "HIPER",
  "HIPERCARD",
  "RUPAY",
  "GE",
  "SYNCHRONY",
  "EFTPOS",
  "UNKNOWN",
]);

export const CurrencyCodeSchema: z.ZodType<CurrencyCode> = z.string().min(3).max(3);

export const DateTimeSchema: z.ZodType<DateTime> = z.string().regex(
  new RegExp(
    "^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])[T,t]([0-1][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)([.][0-9]+)?([Zz]|[+-][0-9]{2}:[0-9]{2})$",
  ),
).min(20).max(64);

export const ActivityTimestampsSchema: z.ZodType<ActivityTimestamps> = z.object({
  create_time: DateTimeSchema.optional(),
  update_time: DateTimeSchema.optional(),
});

export const DisbursementModeSchema: z.ZodType<DisbursementMode> = z.enum(["INSTANT", "DELAYED"]);

export const DisputeCategoriesSchema: z.ZodType<DisputeCategories> = z.enum([
  "ITEM_NOT_RECEIVED",
  "UNAUTHORIZED_TRANSACTION",
]);

export const DisputeCategoriesListSchema: z.ZodType<DisputeCategoriesList> = z.array(DisputeCategoriesSchema);

export const EmailSchema: z.ZodType<Email> = z.string().regex(
  new RegExp(
    "(?:[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+)*|(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\")@(?:(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?\\.)+[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?|\\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-zA-Z0-9-]*[a-zA-Z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])",
  ),
).min(3).max(254);

export const ErrorLinkDescriptionSchema: z.ZodType<ErrorLinkDescription> = z.object({
  href: z.string().regex(new RegExp("^.*$")).min(0).max(20000),
  rel: z.string().regex(new RegExp("^.*$")).min(0).max(100),
  method: z.enum(["GET", "POST", "PUT", "DELETE", "PATCH"]).optional(),
});

export const Error500Schema: z.ZodType<Error500> = z.object({
  name: z.enum(["INTERNAL_SERVER_ERROR"]).optional(),
  message: z.enum(["An internal server error occurred."]).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error503Schema: z.ZodType<Error503> = z.object({
  name: z.enum(["SERVICE_UNAVAILABLE"]).optional(),
  message: z.enum(["Service Unavailable."]).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const ErrorLocationSchema: z.ZodType<ErrorLocation> = z.enum(["body", "path", "query"]);

export const ErrorDetailsSchema: z.ZodType<ErrorDetails> = z.object({
  field: z.string().optional(),
  value: z.string().optional(),
  location: ErrorLocationSchema.optional(),
  issue: z.string(),
  description: z.string().optional(),
});

export const Error400Schema: z.ZodType<Error400> = z.object({
  name: z.enum(["INVALID_REQUEST"]).optional(),
  message: z.enum(["Request is not well-formed, syntactically incorrect, or violates schema."]).optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error401Schema: z.ZodType<Error401> = z.object({
  name: z.enum(["AUTHENTICATION_FAILURE"]).optional(),
  message: z.enum(["Authentication failed due to missing authorization header, or invalid authentication credentials."])
    .optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error403Schema: z.ZodType<Error403> = z.object({
  name: z.enum(["NOT_AUTHORIZED"]).optional(),
  message: z.enum(["Authorization failed due to insufficient permissions."]).optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error404Schema: z.ZodType<Error404> = z.object({
  name: z.enum(["RESOURCE_NOT_FOUND"]).optional(),
  message: z.enum(["The specified resource does not exist."]).optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error409Schema: z.ZodType<Error409> = z.object({
  name: z.enum(["RESOURCE_CONFLICT"]).optional(),
  message: z.enum(["The server has detected a conflict while processing this request."]).optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error415Schema: z.ZodType<Error415> = z.object({
  name: z.enum(["UNSUPPORTED_MEDIA_TYPE"]).optional(),
  message: z.enum(["The server does not support the request payload's media type."]).optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error422Schema: z.ZodType<Error422> = z.object({
  name: z.enum(["UNPROCESSABLE_ENTITY"]).optional(),
  message: z.enum([
    "The requested action could not be performed, semantically incorrect, or failed business validation.",
  ]).optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const ErrorDefaultSchema: z.ZodType<ErrorDefault> = z.union([
  Error400Schema,
  Error401Schema,
  Error403Schema,
  Error404Schema,
  Error409Schema,
  Error415Schema,
  Error422Schema,
  Error500Schema,
  Error503Schema,
]);

export const ExchangeRateSchema: z.ZodType<ExchangeRate> = z.object({
  source_currency: CurrencyCodeSchema.optional(),
  target_currency: CurrencyCodeSchema.optional(),
  value: z.string().optional(),
});

export const LinkDescriptionSchema: z.ZodType<LinkDescription> = z.object({
  href: z.string(),
  rel: z.string(),
  method: z.enum(["GET", "POST", "PUT", "DELETE", "HEAD", "CONNECT", "OPTIONS", "PATCH"]).optional(),
});

export const LinkDescriptionListSchema: z.ZodType<LinkDescriptionList> = z.array(LinkDescriptionSchema);

export const MoneySchema: z.ZodType<Money> = z.object({
  currency_code: CurrencyCodeSchema,
  value: z.string().regex(new RegExp("^((-?[0-9]+)|(-?([0-9]+)?[.][0-9]+))$")).max(32),
});

export const DefinitionsPlatformFeeSchema: z.ZodType<DefinitionsPlatformFee> = z.object({
  amount: MoneySchema,
});

export const DefinitionsPlatformFeeListSchema: z.ZodType<DefinitionsPlatformFeeList> = z.array(
  DefinitionsPlatformFeeSchema,
).min(0).max(1);

export const NetAmountBreakdownItemSchema: z.ZodType<NetAmountBreakdownItem> = z.object({
  payable_amount: MoneySchema.optional(),
  converted_amount: MoneySchema.optional(),
  exchange_rate: ExchangeRateSchema.optional(),
});

export const NetAmountBreakdownItemListSchema: z.ZodType<NetAmountBreakdownItemList> = z.array(
  NetAmountBreakdownItemSchema,
);

export const NetworkTransactionReferenceSchema: z.ZodType<NetworkTransactionReference> = z.object({
  id: z.string().regex(new RegExp("^[a-zA-Z0-9-_@.:&+=*^'~#!$%()]+$")).min(9).max(36),
  date: z.string().regex(new RegExp("^[0-9]+$")).min(4).max(4).optional(),
  network: CardBrandSchema.optional(),
  acquirer_reference_number: z.string().regex(new RegExp("^[a-zA-Z0-9]+$")).min(1).max(36).optional(),
});

export const PayeeBaseSchema: z.ZodType<PayeeBase> = z.object({
  email_address: EmailSchema.optional(),
  merchant_id: AccountIdSchema.optional(),
});

export const PaymentInstruction2Schema: z.ZodType<PaymentInstruction2> = z.object({
  platform_fees: DefinitionsPlatformFeeListSchema.optional(),
});

export const PlatformFeeSchema: z.ZodType<PlatformFee> = z.object({
  amount: MoneySchema,
  payee: PayeeBaseSchema.optional(),
});

export const PaymentInstructionDefinitionPlatformFeeListSchema: z.ZodType<PaymentInstructionDefinitionPlatformFeeList> =
  z.array(PlatformFeeSchema).min(0).max(1);

export const PaymentInstructionSchema: z.ZodType<PaymentInstruction> = z.object({
  platform_fees: PaymentInstructionDefinitionPlatformFeeListSchema.optional(),
  disbursement_mode: DisbursementModeSchema.optional(),
  payee_receivable_fx_rate_id: z.string().regex(new RegExp("^.*$")).min(1).max(4000).optional(),
});

export const PlatformFeeListSchema: z.ZodType<PlatformFeeList> = z.array(PlatformFeeSchema).min(0).max(1);

export const ProcessorResponseSchema: z.ZodType<ProcessorResponse> = z.object({
  avs_code: z.enum([
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "I",
    "M",
    "N",
    "P",
    "R",
    "S",
    "U",
    "W",
    "X",
    "Y",
    "Z",
    "Null",
    "0",
    "1",
    "2",
    "3",
    "4",
  ]).optional(),
  cvv_code: z.enum(["E", "I", "M", "N", "P", "S", "U", "X", "All others", "0", "1", "2", "3", "4"]).optional(),
  response_code: z.enum([
    "0000",
    "00N7",
    "0100",
    "0390",
    "0500",
    "0580",
    "0800",
    "0880",
    "0890",
    "0960",
    "0R00",
    "1000",
    "10BR",
    "1300",
    "1310",
    "1312",
    "1317",
    "1320",
    "1330",
    "1335",
    "1340",
    "1350",
    "1352",
    "1360",
    "1370",
    "1380",
    "1382",
    "1384",
    "1390",
    "1393",
    "5100",
    "5110",
    "5120",
    "5130",
    "5135",
    "5140",
    "5150",
    "5160",
    "5170",
    "5180",
    "5190",
    "5200",
    "5210",
    "5400",
    "5500",
    "5650",
    "5700",
    "5710",
    "5800",
    "5900",
    "5910",
    "5920",
    "5930",
    "5950",
    "6300",
    "7600",
    "7700",
    "7710",
    "7800",
    "7900",
    "8000",
    "8010",
    "8020",
    "8030",
    "8100",
    "8110",
    "8220",
    "9100",
    "9500",
    "9510",
    "9520",
    "9530",
    "9540",
    "9600",
    "PCNR",
    "PCVV",
    "PP06",
    "PPRN",
    "PPAD",
    "PPAB",
    "PPAE",
    "PPAG",
    "PPAI",
    "PPAR",
    "PPAU",
    "PPAV",
    "PPAX",
    "PPBG",
    "PPC2",
    "PPCE",
    "PPCO",
    "PPCR",
    "PPCT",
    "PPCU",
    "PPD3",
    "PPDC",
    "PPDI",
    "PPDV",
    "PPDT",
    "PPEF",
    "PPEL",
    "PPER",
    "PPEX",
    "PPFE",
    "PPFI",
    "PPFR",
    "PPFV",
    "PPGR",
    "PPH1",
    "PPIF",
    "PPII",
    "PPIM",
    "PPIT",
    "PPLR",
    "PPLS",
    "PPMB",
    "PPMC",
    "PPMD",
    "PPNC",
    "PPNL",
    "PPNM",
    "PPNT",
    "PPPH",
    "PPPI",
    "PPPM",
    "PPQC",
    "PPRE",
    "PPRF",
    "PPRR",
    "PPS0",
    "PPS1",
    "PPS2",
    "PPS3",
    "PPS4",
    "PPS5",
    "PPS6",
    "PPSC",
    "PPSD",
    "PPSE",
    "PPTE",
    "PPTF",
    "PPTI",
    "PPTR",
    "PPTT",
    "PPTV",
    "PPUA",
    "PPUC",
    "PPUE",
    "PPUI",
    "PPUP",
    "PPUR",
    "PPVC",
    "PPVE",
    "PPVT",
  ]).optional(),
  payment_advice_code: z.enum([
    "01",
    "02",
    "03",
    "04",
    "21",
    "22",
    "24",
    "25",
    "26",
    "27",
    "28",
    "29",
    "30",
    "40",
    "43",
  ]).optional(),
});

export const ReauthorizeRequestSchema: z.ZodType<ReauthorizeRequest> = z.object({
  amount: MoneySchema.optional(),
});

export const RefundDefinitionsPlatformFeeListSchema: z.ZodType<RefundDefinitionsPlatformFeeList> = z.array(
  PlatformFeeSchema,
).min(0).max(1);

export const RefundRequestSchema: z.ZodType<RefundRequest> = z.object({
  amount: MoneySchema.optional(),
  custom_id: z.string().regex(new RegExp("^.*$")).min(1).max(127).optional(),
  invoice_id: z.string().regex(new RegExp("^.*$")).min(1).max(127).optional(),
  note_to_payer: z.string().regex(new RegExp("^.*$")).min(1).max(255).optional(),
  payment_instruction: PaymentInstruction2Schema.optional(),
});

export const RefundStatusDetailsSchema: z.ZodType<RefundStatusDetails> = z.object({
  reason: z.enum(["ECHECK"]).optional(),
});

export const RefundStatusSchema: z.ZodType<RefundStatus> = z.object({
  status: z.enum(["CANCELLED", "FAILED", "PENDING", "COMPLETED"]).optional(),
  status_details: RefundStatusDetailsSchema.optional(),
});

export const RelatedIdsSchema: z.ZodType<RelatedIds> = z.object({
  order_id: z.string().regex(new RegExp("^[A-Z0-9]+$")).min(1).max(20).optional(),
  authorization_id: z.string().regex(new RegExp("^[A-Z0-9]+$")).min(1).max(20).optional(),
  capture_id: z.string().regex(new RegExp("^[A-Z0-9]+$")).min(1).max(20).optional(),
});

export const SellerPayableBreakdownSchema: z.ZodType<SellerPayableBreakdown> = z.object({
  gross_amount: MoneySchema.optional(),
  paypal_fee: MoneySchema.optional(),
  paypal_fee_in_receivable_currency: MoneySchema.optional(),
  net_amount: MoneySchema.optional(),
  net_amount_in_receivable_currency: MoneySchema.optional(),
  platform_fees: RefundDefinitionsPlatformFeeListSchema.optional(),
  net_amount_breakdown: NetAmountBreakdownItemListSchema.optional(),
  total_refunded_amount: MoneySchema.optional(),
});

export const RefundSchema: z.ZodType<Refund> = RefundStatusSchema.and(z.unknown()).and(ActivityTimestampsSchema);

export const SellerProtectionSchema: z.ZodType<SellerProtection> = z.object({
  status: z.enum(["ELIGIBLE", "PARTIALLY_ELIGIBLE", "NOT_ELIGIBLE"]).optional(),
  dispute_categories: DisputeCategoriesListSchema.optional(),
});

export const AuthorizationSchema: z.ZodType<Authorization> = AuthorizationStatusSchema.and(z.unknown()).and(
  ActivityTimestampsSchema,
);

export const SellerReceivableBreakdownSchema: z.ZodType<SellerReceivableBreakdown> = z.object({
  gross_amount: MoneySchema,
  paypal_fee: MoneySchema.optional(),
  paypal_fee_in_receivable_currency: MoneySchema.optional(),
  net_amount: MoneySchema.optional(),
  receivable_amount: MoneySchema.optional(),
  exchange_rate: ExchangeRateSchema.optional(),
  platform_fees: PlatformFeeListSchema.optional(),
});

export const CaptureSchema: z.ZodType<Capture> = CaptureStatusSchema.and(z.unknown()).and(ActivityTimestampsSchema);

export const SupplementaryDataSchema: z.ZodType<SupplementaryData> = z.object({
  related_ids: RelatedIdsSchema.optional(),
});

export const Authorization2Schema: z.ZodType<Authorization2> = AuthorizationSchema.and(z.unknown());

export const Capture2Schema: z.ZodType<Capture2> = CaptureSchema.and(z.unknown());

export const SupplementaryPurchaseDataSchema: z.ZodType<SupplementaryPurchaseData> = z.object({
  invoice_id: z.string().regex(new RegExp("^.{1,127}$")).min(1).max(127).optional(),
  note_to_payer: z.string().regex(new RegExp("^.{1,255}$")).min(1).max(255).optional(),
});

export const CaptureRequestSchema: z.ZodType<CaptureRequest> = SupplementaryPurchaseDataSchema.and(z.unknown()).and(
  _2Schema,
);

/**
 * API Client class with path-based access to all operations.
 * All methods are inline within the class.
 */
export class ApiClient {
  constructor(private readonly config: OpenAPIClientConfig) {}

  readonly "/v2/payments/authorizations/{authorization_id}" = {
    /**
     * Show details for authorized payment
     *
     * Shows details for an authorized payment, by ID.
     */
    get: (request: {
      path: {
        /** The PayPal-generated ID for the authorized payment to void. */
        authorization_id: string;
      };
      headers?: {
        /** An API-caller-provided JSON Web Token (JWT) assertion that identifies the merchant. For details, see [PayPal-Auth-Assertion](/docs/api/reference/api-requests/#paypal-auth-assertion).<blockquote><strong>Note:</strong>For three party transactions in which a partner is managing the API calls on behalf of a merchant, the partner must identify the merchant using either a PayPal-Auth-Assertion header or an access token with target_subject.</blockquote> */
        "PayPal-Auth-Assertion"?: string;
      };
    }): Promise<
      OpenAPIResponses<{
        /** A successful request returns the HTTP <code>200 OK</code> status code and a JSON response body that shows authorization details. */
        200: {
          body: Authorization2;
        };
        /** Authentication failed due to missing authorization header, or invalid authentication credentials. */
        401: {
          body: Error401;
        };
        /** The request failed because the resource does not exist. */
        404: {
          body: Error404 & _404;
        };
        /** The request failed because an internal server error occurred. */
        500: {
          body: unknown;
        };
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/v2/payments/authorizations/{authorization_id}",
          method: "get",
          requestSchema: z.object({
            path: z.object({
              authorization_id: z.string(),
            }),
            headers: z.object({
              "PayPal-Auth-Assertion": z.string().optional(),
            }).optional(),
          }),
          responseSchema: {
            200: z.object({ body: Authorization2Schema }),
            401: z.object({ body: Error401Schema }),
            404: z.object({ body: Error404Schema.and(_404Schema) }),
            500: z.object({ body: z.unknown() }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };

  readonly "/v2/payments/authorizations/{authorization_id}/capture" = {
    /**
     * Capture authorized payment
     *
     * Captures an authorized payment, by ID.
     */
    post: (request: {
      path: {
        /** The PayPal-generated ID for the authorized payment to void. */
        authorization_id: string;
      };
      headers?: {
        /** The server stores keys for 45 days. */
        "PayPal-Request-Id"?: string;
        /** The preferred server response upon successful completion of the request. Value is:<ul><li><code>return=minimal</code>. The server returns a minimal response to optimize communication between the API caller and the server. A minimal response includes the <code>id</code>, <code>status</code> and HATEOAS links.</li><li><code>return=representation</code>. The server returns a complete resource representation, including the current state of the resource.</li></ul> */
        Prefer?: string;
        /** An API-caller-provided JSON Web Token (JWT) assertion that identifies the merchant. For details, see [PayPal-Auth-Assertion](/docs/api/reference/api-requests/#paypal-auth-assertion).<blockquote><strong>Note:</strong>For three party transactions in which a partner is managing the API calls on behalf of a merchant, the partner must identify the merchant using either a PayPal-Auth-Assertion header or an access token with target_subject.</blockquote> */
        "PayPal-Auth-Assertion"?: string;
      };
      body: CaptureRequest;
    }): Promise<
      OpenAPIResponses<{
        /** A successful request returns the HTTP <code>200 OK</code> status code and a JSON response body that shows captured payment details. */
        200: {
          body: Capture2;
        };
        /** A successful request returns the HTTP <code>201 Created</code> status code and a JSON response body that shows captured payment details. */
        201: {
          body: Capture2;
        };
        /** The request failed because it is not well-formed or is syntactically incorrect or violates schema. */
        400: {
          body: Error400 & _400;
        };
        /** Authentication failed due to missing authorization header, or invalid authentication credentials. */
        401: {
          body: Error401;
        };
        /** The request failed because the caller has insufficient permissions. */
        403: {
          body: Error403 & _403;
        };
        /** The request failed because the resource does not exist. */
        404: {
          body: Error404 & _404;
        };
        /** The server has detected a conflict while processing this request. */
        409: {
          body: Error409;
        };
        /** The request failed because it is semantically incorrect or failed business validation. */
        422: {
          body: Error422 & _422;
        };
        /** The request failed because an internal server error occurred. */
        500: {
          body: unknown;
        };
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/v2/payments/authorizations/{authorization_id}/capture",
          method: "post",
          requestSchema: z.object({
            path: z.object({
              authorization_id: z.string(),
            }),
            headers: z.object({
              "PayPal-Request-Id": z.string().optional(),
              Prefer: z.string().default("return=minimal").optional(),
              "PayPal-Auth-Assertion": z.string().optional(),
            }).optional(),
            body: CaptureRequestSchema,
          }),
          responseSchema: {
            200: z.object({ body: Capture2Schema }),
            201: z.object({ body: Capture2Schema }),
            400: z.object({ body: Error400Schema.and(_400Schema) }),
            401: z.object({ body: Error401Schema }),
            403: z.object({ body: Error403Schema.and(_403Schema) }),
            404: z.object({ body: Error404Schema.and(_404Schema) }),
            409: z.object({ body: Error409Schema }),
            422: z.object({ body: Error422Schema.and(_422Schema) }),
            500: z.object({ body: z.unknown() }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };

  readonly "/v2/payments/authorizations/{authorization_id}/reauthorize" = {
    /**
     * Reauthorize authorized payment
     *
     * Reauthorizes an authorized PayPal account payment, by ID. To ensure that funds are still available, reauthorize a payment after its initial three-day honor period expires. Within the 29-day authorization period, you can issue multiple re-authorizations after the honor period expires.<br/><br/>If 30 days have transpired since the date of the original authorization, you must create an authorized payment instead of reauthorizing the original authorized payment.<br/><br/>A reauthorized payment itself has a new honor period of three days.<br/><br/>You can reauthorize an authorized payment from 4 to 29 days after the 3-day honor period. The allowed amount depends on context and geography, for example in US it is up to 115% of the original authorized amount, not to exceed an increase of $75 USD.<br/><br/>Supports only the `amount` request parameter.
     */
    post: (request: {
      path: {
        /** The PayPal-generated ID for the authorized payment to void. */
        authorization_id: string;
      };
      headers?: {
        /** The server stores keys for 45 days. */
        "PayPal-Request-Id"?: string;
        /** The preferred server response upon successful completion of the request. Value is:<ul><li><code>return=minimal</code>. The server returns a minimal response to optimize communication between the API caller and the server. A minimal response includes the <code>id</code>, <code>status</code> and HATEOAS links.</li><li><code>return=representation</code>. The server returns a complete resource representation, including the current state of the resource.</li></ul> */
        Prefer?: string;
        /** An API-caller-provided JSON Web Token (JWT) assertion that identifies the merchant. For details, see [PayPal-Auth-Assertion](/docs/api/reference/api-requests/#paypal-auth-assertion).<blockquote><strong>Note:</strong>For three party transactions in which a partner is managing the API calls on behalf of a merchant, the partner must identify the merchant using either a PayPal-Auth-Assertion header or an access token with target_subject.</blockquote> */
        "PayPal-Auth-Assertion"?: string;
      };
      body?: ReauthorizeRequest;
    }): Promise<
      OpenAPIResponses<{
        /** A successful request returns the HTTP <code>200 OK</code> status code and a JSON response body that shows the reauthorized payment details. */
        200: {
          body: Authorization2;
        };
        /** A successful request returns the HTTP <code>201 Created</code> status code and a JSON response body that shows the reauthorized payment details. */
        201: {
          body: Authorization2;
        };
        /** The request failed because it is not well-formed or is syntactically incorrect or violates schema. */
        400: {
          body: Error400 & AuthorizationsReauthorize400;
        };
        /** Authentication failed due to missing authorization header, or invalid authentication credentials. */
        401: {
          body: Error401;
        };
        /** The request failed because the resource does not exist. */
        404: {
          body: Error404 & _404;
        };
        /** The request failed because it either is semantically incorrect or failed business validation. */
        422: {
          body: Error422 & AuthorizationsReauthorize422;
        };
        /** The request failed because an internal server error occurred. */
        500: {
          body: unknown;
        };
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/v2/payments/authorizations/{authorization_id}/reauthorize",
          method: "post",
          requestSchema: z.object({
            path: z.object({
              authorization_id: z.string(),
            }),
            headers: z.object({
              "PayPal-Request-Id": z.string().optional(),
              Prefer: z.string().default("return=minimal").optional(),
              "PayPal-Auth-Assertion": z.string().optional(),
            }).optional(),
            body: ReauthorizeRequestSchema,
          }),
          responseSchema: {
            200: z.object({ body: Authorization2Schema }),
            201: z.object({ body: Authorization2Schema }),
            400: z.object({ body: Error400Schema.and(AuthorizationsReauthorize400Schema) }),
            401: z.object({ body: Error401Schema }),
            404: z.object({ body: Error404Schema.and(_404Schema) }),
            422: z.object({ body: Error422Schema.and(AuthorizationsReauthorize422Schema) }),
            500: z.object({ body: z.unknown() }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };

  readonly "/v2/payments/authorizations/{authorization_id}/void" = {
    /**
     * Void authorized payment
     *
     * Voids, or cancels, an authorized payment, by ID. You cannot void an authorized payment that has been fully captured.
     */
    post: (request: {
      path: {
        /** The PayPal-generated ID for the authorized payment to void. */
        authorization_id: string;
      };
      headers?: {
        /** An API-caller-provided JSON Web Token (JWT) assertion that identifies the merchant. For details, see [PayPal-Auth-Assertion](/docs/api/reference/api-requests/#paypal-auth-assertion).<blockquote><strong>Note:</strong>For three party transactions in which a partner is managing the API calls on behalf of a merchant, the partner must identify the merchant using either a PayPal-Auth-Assertion header or an access token with target_subject.</blockquote> */
        "PayPal-Auth-Assertion"?: string;
        /** The server stores keys for 45 days. */
        "PayPal-Request-Id"?: string;
        /** The preferred server response upon successful completion of the request. Value is:<ul><li><code>return=minimal</code>. The server returns a minimal response to optimize communication between the API caller and the server. A minimal response includes the <code>id</code>, <code>status</code> and HATEOAS links.</li><li><code>return=representation</code>. The server returns a complete resource representation, including the current state of the resource.</li></ul> */
        Prefer?: string;
      };
    }): Promise<
      OpenAPIResponses<{
        /** A successful request returns the HTTP <code>200 OK</code> status code and a JSON response body that shows authorization details. This response is returned when the Prefer header is set to return=representation. */
        200: {
          body: Authorization2;
        };
        /** A successful request returns the HTTP <code>204 No Content</code> status code with no JSON response body. This response is returned when the Prefer header is set to return=minimal. */
        204: {
          body: unknown;
        };
        /** Authentication failed due to missing authorization header, or invalid authentication credentials. */
        401: {
          body: Error401 & _401;
        };
        /** The request failed because the caller has insufficient permissions. */
        403: {
          body: Error403 & _403;
        };
        /** The request failed because the resource does not exist. */
        404: {
          body: Error404 & _404;
        };
        /** The request failed because a previous call for the given resource is in progress. */
        409: {
          body: Error409 & _409;
        };
        /** The request failed because it either is semantically incorrect or failed business validation. */
        422: {
          body: Error422 & AuthorizationsVoid422;
        };
        /** The request failed because an internal server error occurred. */
        500: {
          body: unknown;
        };
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/v2/payments/authorizations/{authorization_id}/void",
          method: "post",
          requestSchema: z.object({
            path: z.object({
              authorization_id: z.string(),
            }),
            headers: z.object({
              "PayPal-Auth-Assertion": z.string().optional(),
              "PayPal-Request-Id": z.string().optional(),
              Prefer: z.string().default("return=minimal").optional(),
            }).optional(),
          }),
          responseSchema: {
            200: z.object({ body: Authorization2Schema }),
            204: z.object({ body: z.unknown() }),
            401: z.object({ body: Error401Schema.and(_401Schema) }),
            403: z.object({ body: Error403Schema.and(_403Schema) }),
            404: z.object({ body: Error404Schema.and(_404Schema) }),
            409: z.object({ body: Error409Schema.and(_409Schema) }),
            422: z.object({ body: Error422Schema.and(AuthorizationsVoid422Schema) }),
            500: z.object({ body: z.unknown() }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };

  readonly "/v2/payments/captures/{capture_id}" = {
    /**
     * Show captured payment details
     *
     * Shows details for a captured payment, by ID.
     */
    get: (request: {
      path: {
        /** The PayPal-generated ID for the captured payment to refund. */
        capture_id: string;
      };
    }): Promise<
      OpenAPIResponses<{
        /** A successful request returns the HTTP <code>200 OK</code> status code and a JSON response body that shows captured payment details. */
        200: {
          body: Capture2;
        };
        /** Authentication failed due to missing authorization header, or invalid authentication credentials. */
        401: {
          body: Error401;
        };
        /** The request failed because the caller has insufficient permissions. */
        403: {
          body: Error403 & _403;
        };
        /** The request failed because the resource does not exist. */
        404: {
          body: Error404 & _404;
        };
        /** The request failed because an internal server error occurred. */
        500: {
          body: unknown;
        };
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/v2/payments/captures/{capture_id}",
          method: "get",
          requestSchema: z.object({
            path: z.object({
              capture_id: z.string(),
            }),
          }),
          responseSchema: {
            200: z.object({ body: Capture2Schema }),
            401: z.object({ body: Error401Schema }),
            403: z.object({ body: Error403Schema.and(_403Schema) }),
            404: z.object({ body: Error404Schema.and(_404Schema) }),
            500: z.object({ body: z.unknown() }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };

  readonly "/v2/payments/captures/{capture_id}/refund" = {
    /**
     * Refund captured payment
     *
     * Refunds a captured payment, by ID. For a full refund, include an empty payload in the JSON request body. For a partial refund, include an <code>amount</code> object in the JSON request body.
     */
    post: (request: {
      path: {
        /** The PayPal-generated ID for the captured payment to refund. */
        capture_id: string;
      };
      headers?: {
        /** The server stores keys for 45 days. */
        "PayPal-Request-Id"?: string;
        /** The preferred server response upon successful completion of the request. Value is:<ul><li><code>return=minimal</code>. The server returns a minimal response to optimize communication between the API caller and the server. A minimal response includes the <code>id</code>, <code>status</code> and HATEOAS links.</li><li><code>return=representation</code>. The server returns a complete resource representation, including the current state of the resource.</li></ul> */
        Prefer?: string;
        /** An API-caller-provided JSON Web Token (JWT) assertion that identifies the merchant. For details, see [PayPal-Auth-Assertion](/docs/api/reference/api-requests/#paypal-auth-assertion).<blockquote><strong>Note:</strong>For three party transactions in which a partner is managing the API calls on behalf of a merchant, the partner must identify the merchant using either a PayPal-Auth-Assertion header or an access token with target_subject.</blockquote> */
        "PayPal-Auth-Assertion"?: string;
      };
      body?: RefundRequest;
    }): Promise<
      OpenAPIResponses<{
        /** A successful request returns the HTTP <code>200 OK</code> status code and a JSON response body that shows refund details. */
        200: {
          body: Refund;
        };
        /** A successful request returns the HTTP <code>201 Created</code> status code and a JSON response body that shows refund details. */
        201: {
          body: Refund;
        };
        /** The request failed because it is not well-formed or is syntactically incorrect or violates schema. */
        400: {
          body: Error400 & CapturesRefund400;
        };
        /** Authentication failed due to missing authorization header, or invalid authentication credentials. */
        401: {
          body: Error401 & _401;
        };
        /** The request failed because the caller has insufficient permissions. */
        403: {
          body: Error403 & _403;
        };
        /** The request failed because the resource does not exist. */
        404: {
          body: Error404 & _404;
        };
        /** The request failed because a previous call for the given resource is in progress. */
        409: {
          body: Error409 & _409;
        };
        /** The request failed because it either is semantically incorrect or failed business validation. */
        422: {
          body: Error422 & CapturesRefund422;
        };
        /** The request failed because an internal server error occurred. */
        500: {
          body: unknown;
        };
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/v2/payments/captures/{capture_id}/refund",
          method: "post",
          requestSchema: z.object({
            path: z.object({
              capture_id: z.string(),
            }),
            headers: z.object({
              "PayPal-Request-Id": z.string().optional(),
              Prefer: z.string().default("return=minimal").optional(),
              "PayPal-Auth-Assertion": z.string().optional(),
            }).optional(),
            body: RefundRequestSchema,
          }),
          responseSchema: {
            200: z.object({ body: RefundSchema }),
            201: z.object({ body: RefundSchema }),
            400: z.object({ body: Error400Schema.and(CapturesRefund400Schema) }),
            401: z.object({ body: Error401Schema.and(_401Schema) }),
            403: z.object({ body: Error403Schema.and(_403Schema) }),
            404: z.object({ body: Error404Schema.and(_404Schema) }),
            409: z.object({ body: Error409Schema.and(_409Schema) }),
            422: z.object({ body: Error422Schema.and(CapturesRefund422Schema) }),
            500: z.object({ body: z.unknown() }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };

  readonly "/v2/payments/refunds/{refund_id}" = {
    /**
     * Show refund details
     *
     * Shows details for a refund, by ID.
     */
    get: (request: {
      path: {
        /** The PayPal-generated ID for the refund for which to show details. */
        refund_id: string;
      };
      headers?: {
        /** An API-caller-provided JSON Web Token (JWT) assertion that identifies the merchant. For details, see [PayPal-Auth-Assertion](/docs/api/reference/api-requests/#paypal-auth-assertion).<blockquote><strong>Note:</strong>For three party transactions in which a partner is managing the API calls on behalf of a merchant, the partner must identify the merchant using either a PayPal-Auth-Assertion header or an access token with target_subject.</blockquote> */
        "PayPal-Auth-Assertion"?: string;
      };
    }): Promise<
      OpenAPIResponses<{
        /** A successful request returns the HTTP <code>200 OK</code> status code and a JSON response body that shows refund details. */
        200: {
          body: Refund;
        };
        /** Authentication failed due to missing authorization header, or invalid authentication credentials. */
        401: {
          body: Error401 & _401;
        };
        /** The request failed because the caller has insufficient permissions. */
        403: {
          body: Error403 & _403;
        };
        /** The request failed because the resource does not exist. */
        404: {
          body: Error404 & _404;
        };
        /** The request failed because an internal server error occurred. */
        500: {
          body: unknown;
        };
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/v2/payments/refunds/{refund_id}",
          method: "get",
          requestSchema: z.object({
            path: z.object({
              refund_id: z.string(),
            }),
            headers: z.object({
              "PayPal-Auth-Assertion": z.string().optional(),
            }).optional(),
          }),
          responseSchema: {
            200: z.object({ body: RefundSchema }),
            401: z.object({ body: Error401Schema.and(_401Schema) }),
            403: z.object({ body: Error403Schema.and(_403Schema) }),
            404: z.object({ body: Error404Schema.and(_404Schema) }),
            500: z.object({ body: z.unknown() }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };
}
