// deno-lint-ignore-file no-explicit-any
// This file was auto-generated by @brad-jones/open-api-client

import {
  type OpenAPIClientConfig,
  openAPIFetch,
  type OpenAPIResponses,
} from "jsr:@brad-jones/deno-net-open-api-client@0.1.6";
import { z } from "npm:zod@^4.1.12";

export type Carrier =
  | "2EBOX"
  | "360LION"
  | "3JMSLOGISTICS"
  | "4_72"
  | "6LS"
  | "A1POST"
  | "AAA_COOPER"
  | "ABCUSTOM"
  | "ABXEXPRESS_MY"
  | "ACOMMMERCE"
  | "ACSWORLDWIDE"
  | "ACS_GR"
  | "ADERONLINE"
  | "ADICIONAL"
  | "ADSONE"
  | "ADUIEPYLE"
  | "AERONET"
  | "AEX"
  | "AFLLOG_FTP"
  | "AGILITY"
  | "AIRMEE_WEBHOOK"
  | "AIR_CANADA_GLOBAL"
  | "ALFATREX"
  | "ALLIEDEXPRESS"
  | "ALLJOY"
  | "ALPHAFAST"
  | "ALWAYS_EXPRESS"
  | "AMAZON"
  | "AMAZON_FBA_SWISHIP"
  | "AMAZON_SHIP_MCF"
  | "AMSTAN"
  | "AMS_GRP"
  | "ANDREANI"
  | "ANICAM_BOX"
  | "ANJUN"
  | "ANSERX"
  | "AN_POST"
  | "AO_COURIER"
  | "AO_DEUTSCHLAND"
  | "APC_OVERNIGHT"
  | "APC_OVERNIGHT_CONNUM"
  | "APG"
  | "APRISAEXPRESS"
  | "AQUILINE"
  | "ARAMEX"
  | "ARAMEX_AU"
  | "ARCO_SPEDIZIONI"
  | "ARE_EMIRATES_POST"
  | "ARG_OCA"
  | "ARK_LOGISTICS"
  | "ASE"
  | "ASENDIA_HK"
  | "ASENDIA_UK"
  | "ASENDIA_USA"
  | "ASIGNA"
  | "AUPOST_CN"
  | "AUSTRIAN_POST_EXPRESS"
  | "AUS_STARTRACK"
  | "AUS_TOLL"
  | "AU_AUSTRIAN_POST"
  | "AU_AU_POST"
  | "AU_TNT"
  | "AVERITT"
  | "BEL_DHL"
  | "BEL_RS"
  | "BESTWAYPARCEL"
  | "BE_BPOST"
  | "BE_KIALA"
  | "BG_BULGARIAN_POST"
  | "BH_POSTA"
  | "BH_WORLDWIDE"
  | "BIRDSYSTEM"
  | "BJSHOMEDELIVERY"
  | "BLINKLASTMILE"
  | "BLR_BELPOST"
  | "BLUECARE"
  | "BLUESTAR"
  | "BLUEX"
  | "BNEED"
  | "BOMBINOEXP"
  | "BOND"
  | "BONDSCOURIERS"
  | "BORDEREXPRESS"
  | "BOX_BERRY"
  | "BPOST_INT"
  | "BRA_CORREIOS"
  | "BRING"
  | "BROUWER_TRANSPORT"
  | "BRT_IT"
  | "BRT_IT_PARCELID"
  | "BRT_IT_SENDER_REF"
  | "BUDBEE_WEBHOOK"
  | "BUYLOGIC"
  | "B_TWO_C_EUROPE"
  | "CAE_DELIVERS"
  | "CAINIAO"
  | "CARIBOU"
  | "CARRIERS"
  | "CARRY_FLAP"
  | "CA_CANADA_POST"
  | "CA_CANPAR"
  | "CA_GREYHOUND"
  | "CA_PUROLATOR"
  | "CBL_LOGISTICA"
  | "CDEK"
  | "CDEK_TR"
  | "CELERITAS"
  | "CELLO_SQUARE"
  | "CESKA_CZ"
  | "CEVA"
  | "CFL_LOGISTICS"
  | "CGS_EXPRESS"
  | "CHAMPION_LOGISTICS"
  | "CHITCHATS"
  | "CHOIR_EXP"
  | "CHROBINSON"
  | "CHRONOPOST_FR"
  | "CHUKOU1"
  | "CH_SWISS_POST_PRIORITY"
  | "CITYLINK_MY"
  | "CJPACKET"
  | "CJ_CENTURY"
  | "CJ_GLS"
  | "CJ_HK_INTERNATIONAL"
  | "CJ_INT_MY"
  | "CJ_KR"
  | "CJ_LOGISTICS"
  | "CJ_TH"
  | "CLEVY_LINKS"
  | "CLE_LOGISTICS"
  | "CLOUDWISH_ASIA"
  | "CNDEXPRESS"
  | "CNEXPS"
  | "CNWANGTONG"
  | "CN_17POST"
  | "CN_BESTEXPRESS"
  | "CN_BOXC"
  | "CN_CHINA_POST_EMS"
  | "CN_DPEX"
  | "CN_EMS"
  | "CN_EQUICK"
  | "CN_JCEX"
  | "CN_PAYPAL_PACKAGE"
  | "CN_POST56"
  | "CN_SF_EXPRESS"
  | "CN_STO"
  | "CN_WEDO"
  | "CN_WISHPOST"
  | "CN_YUNDA"
  | "COLIS_PRIVE"
  | "COLLECTCO"
  | "COLLIVERY"
  | "COMET_TECH"
  | "CONTINENTAL"
  | "CON_WAY"
  | "COORDINADORA"
  | "COPA_COURIER"
  | "COPE"
  | "CORPORATECOURIERS_WEBHOOK"
  | "CORREOS_DE_MEXICO"
  | "CORREOS_ES"
  | "CORREOS_EXPRESS"
  | "CORREO_UY"
  | "COSTMETICSNOW"
  | "COURANT_PLUS"
  | "COUREX"
  | "COURIERS_PLEASE"
  | "CPACKET"
  | "CPEX"
  | "CROSHOT"
  | "CSE"
  | "CTC_EXPRESS"
  | "CUBYN"
  | "CUCKOOEXPRESS"
  | "CYPRUS_POST_CYP"
  | "DAIGLOBALTRACK"
  | "DAJIN"
  | "DANSKE_FRAGT"
  | "DAWN_WING"
  | "DAYTON_FREIGHT"
  | "DBSCHENKER_B2B"
  | "DBSCHENKER_SE"
  | "DBSCHENKER_SV"
  | "DDEXPRESS"
  | "DEALERSEND"
  | "DELIVERYONTIME"
  | "DELNEXT"
  | "DELTEC_UK"
  | "DEMANDSHIP"
  | "DESCARTES"
  | "DESIGNERTRANSPORT_WEBHOOK"
  | "DESTINY"
  | "DEX_I"
  | "DE_ASENDIA"
  | "DE_DEUTSCHE"
  | "DE_DEUTSCHE_POST_DHL_WITHIN_EUROPE_TRACKNET"
  | "DE_DHL_EXPRESS"
  | "DE_DPD_DELISTRACK"
  | "DE_GLS"
  | "DHL"
  | "DHL_ACTIVE_TRACING"
  | "DHL_AU"
  | "DHL_BENELUX"
  | "DHL_ECOMERCE_ASA"
  | "DHL_ES"
  | "DHL_FR"
  | "DHL_FREIGHT"
  | "DHL_GLOBAL_MAIL_ASIA"
  | "DHL_HK"
  | "DHL_JP"
  | "DHL_PARCEL_ES"
  | "DHL_PARCEL_NL"
  | "DHL_PARCEL_RU"
  | "DHL_PL"
  | "DHL_REFR"
  | "DHL_SG"
  | "DHL_SUPPLY_CHAIN"
  | "DHL_UK"
  | "DIAMOND_EUROGISTICS"
  | "DICOM"
  | "DIDADI"
  | "DIMERCO"
  | "DIRECTCOURIERS"
  | "DIRECTLOG"
  | "DIRECTPARCELS"
  | "DMM_NETWORK"
  | "DMS_MATRIX"
  | "DOBROPOST"
  | "DOORA"
  | "DOORDASH_WEBHOOK"
  | "DPD"
  | "DPD_DELISTRACK"
  | "DPD_FR"
  | "DPD_HGRY"
  | "DPD_HK"
  | "DPD_IR"
  | "DPD_LOCAL"
  | "DPD_LOCAL_REF"
  | "DPD_POLAND"
  | "DPD_RO"
  | "DPD_RU"
  | "DPEX"
  | "DPE_EXPRESS"
  | "DPE_SOUTH_AFRC"
  | "DSV"
  | "DTDC_AU"
  | "DTDC_EXPRESS"
  | "DTDC_IN"
  | "DTD_EXPR"
  | "DX_SFTP"
  | "DYLT"
  | "DYNALOGIC"
  | "EASY_MAIL"
  | "ECEXPRESS"
  | "ECHO"
  | "ECMS"
  | "ECOSCOOTING"
  | "EFEX"
  | "EFS"
  | "EKART"
  | "ELIAN_POST"
  | "EMPS_CN"
  | "ENDEAVOUR_DELIVERY"
  | "ENVIALIA_REFERENCE"
  | "EPARCEL_KR"
  | "EPST_GLBL"
  | "EP_BOX"
  | "ESHIPPING"
  | "ESP_ASM"
  | "ESP_ENVIALIA"
  | "ESP_MRW"
  | "ESP_NACEX"
  | "ESP_PACKLINK"
  | "ESP_REDUR"
  | "ETOMARS"
  | "ETOTAL"
  | "ETS_EXPRESS"
  | "EU_FLEET_SOLUTIONS"
  | "EU_IMX"
  | "EXPRESSSALE"
  | "FARGOOD"
  | "FAR_INTERNATIONAL"
  | "FASTRACK"
  | "FASTRK_SERV"
  | "FASTWAY_IR"
  | "FASTWAY_NZ"
  | "FDSEXPRESS"
  | "FEDEX"
  | "FEDEX_CROSSBORDER"
  | "FEDEX_FR"
  | "FEDEX_INTL_MLSERV"
  | "FEDEX_POLAND"
  | "FEDEX_UK"
  | "FETCHR_WEBHOOK"
  | "FIEGE"
  | "FIEGE_NL"
  | "FIRSTMILE"
  | "FLASHEXPRESS"
  | "FMX"
  | "FONSEN"
  | "FORRUN"
  | "FREIGHTQUOTE"
  | "FRETERAPIDO"
  | "FR_BERT"
  | "FR_COLIS"
  | "FR_EXAPAQ"
  | "FR_GEODIS"
  | "FR_GLS"
  | "FULFILLA"
  | "FULFILLME"
  | "FURDECO"
  | "GAC"
  | "GANGBAO"
  | "GBA"
  | "GBS_BROKER"
  | "GB_APC"
  | "GB_ARROW"
  | "GB_NORSK"
  | "GB_PANTHER"
  | "GB_TUFFNELLS"
  | "GEIS"
  | "GEL_EXPRESS"
  | "GEMWORLDWIDE"
  | "GENERAL_OVERNIGHT"
  | "GENIKI_GR"
  | "GEODIS_ESPACE"
  | "GESWL"
  | "GIAO_HANG"
  | "GIO_EXPRESS"
  | "GLOBALTRANZ"
  | "GLOBAL_ABF"
  | "GLOBAL_ESTES"
  | "GLOBAL_EXPRESS"
  | "GLOBAL_IPARCEL"
  | "GLOBAL_TNT"
  | "GLOBAVEND"
  | "GLS_CROTIA"
  | "GLS_CZ"
  | "GLS_IT"
  | "GLS_ITALY"
  | "GLS_SLOV"
  | "GLS_SLOVEN"
  | "GOGLOBALPOST"
  | "GOJEK"
  | "GRAB_WEBHOOK"
  | "GRUPO"
  | "GR_ELTA"
  | "GSI_EXPRESS"
  | "GSO"
  | "HAPPY2POINT"
  | "HCT_LOGISTICS"
  | "HDB"
  | "HDB_BOX"
  | "HELLMANN"
  | "HELTHJEM"
  | "HEPPNER"
  | "HEPPNER_FR"
  | "HERMES"
  | "HERMES_2MANN_HANDLING"
  | "HERMES_DE"
  | "HH_EXP"
  | "HIPSHIPPER"
  | "HKD"
  | "HK_FLYT_EXPRESS"
  | "HK_FOUR_PX_EXPRESS"
  | "HK_POST"
  | "HK_TGX"
  | "HOLISOL"
  | "HOME_DELIVERY_SOLUTIONS"
  | "HOUNDEXPRESS"
  | "HRPARCEL"
  | "HRV_HRVATSKA"
  | "HUAHAN_EXPRESS"
  | "HUNTER_EXPRESS"
  | "HUODULL"
  | "HX_EXPRESS"
  | "IBEONE"
  | "ICUMULUS"
  | "IDEXPRESS"
  | "IDN_JNE"
  | "IDN_LION_PARCEL"
  | "IDN_PANDU"
  | "IML"
  | "INDOPAKET"
  | "IND_BLUEDART"
  | "IND_DELHIVERY"
  | "IND_DELIVREE"
  | "IND_DOTZOT"
  | "IND_ECOM"
  | "IND_FIRSTFLIGHT"
  | "IND_GATI"
  | "IND_GOJAVAS"
  | "IND_PROFESSIONAL_COURIERS"
  | "IND_SAFEEXPRESS"
  | "IND_XPRESSBEES"
  | "INPOST_PACZKOMATY"
  | "INTEGRA2_FTP"
  | "INTELIPOST"
  | "INTEL_VALLEY"
  | "INTERPARCEL_AU"
  | "INTERPARCEL_NZ"
  | "INTERPARCEL_UK"
  | "INTEXPRESS"
  | "ISRAEL_POST"
  | "ISR_POST_DOMESTIC"
  | "IT_DHL_ECOMMERCE"
  | "IT_FERCAM"
  | "IT_NEXIVE"
  | "IT_POSTE_ITALIA"
  | "IT_TNT"
  | "IVOY_WEBHOOK"
  | "I_DIKA"
  | "JANCO"
  | "JANIO"
  | "JERSEY_POST"
  | "JET_SHIP"
  | "JINDOUYUN"
  | "JINSUNG"
  | "JOCOM"
  | "JOOM_LOGIS"
  | "JOYING_BOX"
  | "JPN_JAPAN_POST"
  | "JPN_SAGAWA"
  | "JP_KURO_NEKO_YAMATO_UNYUU"
  | "JS_EXPRESS"
  | "JTEXPRESS"
  | "JTEXPRESS_VN"
  | "JX"
  | "J_NET"
  | "K1_EXPRESS"
  | "KANGAROO_MY"
  | "KEC"
  | "KERRYTJ"
  | "KERRYTTC_VN"
  | "KERRY_ECOMMERCE"
  | "KGMHUB"
  | "KHM_CAMBODIA_POST"
  | "KOR_ECARGO"
  | "KPOST"
  | "KR_KOREA_POST"
  | "KUEHNE"
  | "KURASI"
  | "KWE_GLOBAL"
  | "KWT"
  | "KYUNGDONG_PARCEL"
  | "KY_EXPRESS"
  | "LALAMOVE"
  | "LANDMARK_GLOBAL"
  | "LANDMARK_GLOBAL_REFERENCE"
  | "LATVIJAS_PASTS"
  | "LA_POSTE_SUIVI"
  | "LBCEXPRESS_FTP"
  | "LEADER"
  | "LEGION_EXPRESS"
  | "LEXSHIP"
  | "LHT_EXPRESS"
  | "LICCARDI_EXPRESS"
  | "LIEFERY"
  | "LINE"
  | "LINKBRIDGE"
  | "LOCUS_WEBHOOK"
  | "LOGISTERS"
  | "LOGISTICSWORLDWIDE_HK"
  | "LOGISTIKA"
  | "LOGISTYX_TRANSGROUP"
  | "LONESTAR"
  | "LOOMIS_EXPRESS"
  | "LOTTE"
  | "LTIANEXP"
  | "LTL"
  | "LTU_LIETUVOS"
  | "MAGYAR_HU"
  | "MAILAMERICAS"
  | "MAILPLUS_JPN"
  | "MAIL_PLUS"
  | "MAINFREIGHT"
  | "MAINWAY"
  | "MATDESPATCH"
  | "MATKAHUOLTO"
  | "MBW"
  | "MEX_AEROFLASH"
  | "MEX_ESTAFETA"
  | "MEX_REDPACK"
  | "MEX_SENDA"
  | "MGLOBAL"
  | "MIKROPAKKET"
  | "MIKROPAKKET_BE"
  | "MILKMAN"
  | "MORE_LINK"
  | "MORNING_EXPRESS"
  | "MRW_FTP"
  | "MXE"
  | "MX_CARGO"
  | "MYHERMES"
  | "MYS_AIRPAK"
  | "MYS_EMS"
  | "MYS_GDEX"
  | "MYS_MYPOST_ONLINE"
  | "MYS_MYS_POST"
  | "MYS_SKYNET"
  | "M_XPRESS"
  | "NACEX"
  | "NACEX_ES"
  | "NANJINGWOYUAN"
  | "NATIONAL_SAMEDAY"
  | "NATIONEX"
  | "NATIONWIDE_MY"
  | "NEWAY"
  | "NEWEGGEXPRESS"
  | "NEWGISTICS"
  | "NEWZEALAND_COURIERS"
  | "NG_COURIERPLUS"
  | "NHANS_SOLUTIONS"
  | "NIM_EXPRESS"
  | "NINJAVAN_MY"
  | "NINJAVAN_SG"
  | "NINJAVAN_THAI"
  | "NINJAVAN_WB"
  | "NIPOST_NG"
  | "NLD_DHL"
  | "NLD_GLS"
  | "NLD_POSTNL"
  | "NLD_TRANSMISSION"
  | "NOVA_POSHTA"
  | "NOVA_POSHTA_INT"
  | "NOX_NACHTEXPRESS"
  | "NOX_NIGHT_TIME_EXPRESS"
  | "NTLOGISTICS_VN"
  | "NZ_COURIER_POST"
  | "NZ_NZ_POST"
  | "OCS"
  | "OCS_WORLDWIDE"
  | "OKAYPARCEL"
  | "OMNIPARCEL"
  | "OMNIVA"
  | "ONECLICK"
  | "ONEWORLDEXPRESS"
  | "ORANGE_DS"
  | "OSM_WORLDWIDE"
  | "OVERSE_EXP"
  | "P2P_TRC"
  | "PAACK_WEBHOOK"
  | "PADTF"
  | "PAGO"
  | "PALEXPRESS"
  | "PALLETWAYS"
  | "PALLET_NETWORK"
  | "PANTHER_REFERENCE"
  | "PAN_ASIA"
  | "PAPERFLY"
  | "PAPER_EXPRESS"
  | "PAQUETEXPRESS"
  | "PARCEL2GO"
  | "PARCELINKLOGISTICS"
  | "PARCELLED_IN"
  | "PARCELONE"
  | "PARCELPAL_WEBHOOK"
  | "PARCELPOINT"
  | "PARCELPOST_SG"
  | "PARCEL_2_POST"
  | "PARKNPARCEL"
  | "PCFCORP"
  | "PFCEXPRESS"
  | "PFLOGISTICS"
  | "PHL_AIR21"
  | "PHL_AIRSPEED"
  | "PHL_JAMEXPRESS"
  | "PICKRR"
  | "PICKUP"
  | "PICKUPP_MYS"
  | "PICKUPP_SGP"
  | "PILOT_FREIGHT"
  | "PIL_LOGISTICS"
  | "PITNEY_BOWES"
  | "PITTOHIO"
  | "PIXSELL"
  | "PLANZER"
  | "PLUS_LOG_UK"
  | "PL_POCZTA_POLSKA"
  | "POL_SIODEMKA"
  | "PONY_EXPRESS"
  | "POSTA_PLUS"
  | "POSTA_RO"
  | "POSTA_UKR"
  | "POSTEN_NORGE"
  | "POSTI"
  | "POSTNL_INTL_3S"
  | "POSTNL_INT_3_S"
  | "POSTNORD_LOGISTICS"
  | "POSTNORD_LOGISTICS_DK"
  | "POSTUR_IS"
  | "POST_SERBIA"
  | "POST_SLOVENIA"
  | "PRESIDENT_TRANS"
  | "PRESSIODE"
  | "PRIMAMULTICIPTA"
  | "PROMEDDELIVERY"
  | "PRT_CHRONOPOST"
  | "PRT_CTT"
  | "PRT_INT_SEUR"
  | "PRT_SEUR"
  | "PTS"
  | "PTT_POST"
  | "QUANTIUM"
  | "QWINTRY"
  | "RABEN_GROUP"
  | "RAF_PH"
  | "RAIDEREX"
  | "RAM"
  | "RCL"
  | "RINCOS"
  | "RL_US"
  | "ROADBULL"
  | "ROADRUNNER_FREIGHT"
  | "ROCKET_PARCEL"
  | "ROUTIFIC_WEBHOOK"
  | "ROYAL_MAIL"
  | "RPD2MAN"
  | "RPX"
  | "RPXLOGISTICS"
  | "RPX_ID"
  | "RUSSIAN_POST"
  | "RUSTON"
  | "RZYEXPRESS"
  | "SAIA_FREIGHT"
  | "SAILPOST"
  | "SAP_EXPRESS"
  | "SAU_SAUDI_POST"
  | "SCUDEX_EXPRESS"
  | "SDA_IT"
  | "SDH_SCM"
  | "SEFL"
  | "SEINO"
  | "SEKOLOGISTICS"
  | "SEKO_SFTP"
  | "SENDING"
  | "SENDIT"
  | "SENDLE"
  | "SEUR_ES"
  | "SEUR_SP_API"
  | "SFB2C"
  | "SFCSERVICE"
  | "SFC_LOGISTICS"
  | "SFPLUS_WEBHOOK"
  | "SF_EX"
  | "SG_DETRACK"
  | "SG_QXPRESS"
  | "SG_SG_POST"
  | "SG_SPEEDPOST"
  | "SG_TAQBIN"
  | "SHENZHEN"
  | "SHIPENTEGRA"
  | "SHIPPIT"
  | "SHIPTER"
  | "SHIPTOR"
  | "SHIP_GATE"
  | "SHIP_IT_ASIA"
  | "SHOPFANS"
  | "SHREENANDANCOURIER"
  | "SHREETIRUPATI"
  | "SHREE_ANJANI_COURIER"
  | "SHREE_MARUTI"
  | "SIMPLYPOST"
  | "SINOTRANS"
  | "SIN_GLBL"
  | "SKYBOX"
  | "SKYNET_UAE"
  | "SKYNET_UK"
  | "SKYNET_WORLDWIDE"
  | "SKYNET_ZA"
  | "SKY_POSTAL"
  | "SK_POSTA"
  | "SMG_EXPRESS"
  | "SMOOTH"
  | "SMSA_EXPRESS"
  | "SONICTL"
  | "SOUTH_AFRICAN_POST_OFFICE"
  | "SPEEDCOURIERS_GR"
  | "SPEEDEE"
  | "SPEEDEXCOURIER"
  | "SPOTON"
  | "SPRING_GDS"
  | "SRE_KOREA"
  | "STALLIONEXPRESS"
  | "STARKEN"
  | "STAR_TRACK_EXPRESS"
  | "STAR_TRACK_NEXT_FLIGHT"
  | "STEPFORWARDFS"
  | "STONE3PL"
  | "STRECK_TRANSPORT"
  | "SUTTON"
  | "SWE_POSTNORD"
  | "SWISHIP_DE"
  | "SWISS_POST_FTP"
  | "SYPOST"
  | "SZENDEX"
  | "TAQBIN_HK"
  | "TAQBIN_MY"
  | "TARRIVE"
  | "TAZMANIAN_FREIGHT"
  | "TCK_EXPRESS"
  | "TCS"
  | "TFM"
  | "TFORCE_FINALMILE"
  | "THABIT_LOGISTICS"
  | "THA_DYNAMIC_LOGISTICS"
  | "THA_KERRY"
  | "THA_THAILAND_POST"
  | "THECOURIERGUY"
  | "THEDELIVERYGROUP"
  | "THENILE_WEBHOOK"
  | "TIGFREIGHT"
  | "TIKI_ID"
  | "TIPSA"
  | "TNT"
  | "TNT_CLICK_IT"
  | "TNT_FR"
  | "TNT_NL"
  | "TNT_REFR"
  | "TNT_UK"
  | "TNT_UK_REFR"
  | "TOLL"
  | "TOLL_NZ"
  | "TOLOS"
  | "TOPHATTEREXPRESS"
  | "TOPYOU"
  | "TOTAL_EXPRESS"
  | "TOURLINE"
  | "TRACKON"
  | "TRANS_KARGO"
  | "TRUMPCARD"
  | "TRUNKRS_WEBHOOK"
  | "TUFFNELLS_REFERENCE"
  | "TWO_GO"
  | "TW_TAIWAN_POST"
  | "UBI_LOGISTICS"
  | "UC_EXPRE"
  | "UDS"
  | "UK_COLLECTPLUS"
  | "UK_DPD"
  | "UK_NIGHTLINE"
  | "UK_PARCELFORCE"
  | "UK_UK_MAIL"
  | "UK_XDP"
  | "UK_YODEL"
  | "UPS"
  | "UPS_FREIGHT"
  | "UPS_MAIL_INNOVATIONS"
  | "UPS_REFERENCE"
  | "USF_REDDAWAY"
  | "USHIP"
  | "USPS"
  | "US_GLOBEGISTICS"
  | "US_LASERSHIP"
  | "US_OLD_DOMINION"
  | "US_ONTRAC"
  | "US_YRC"
  | "VAMOX"
  | "VENIPAK"
  | "VIAEUROPE"
  | "VIA_EXPRESS"
  | "VIRTRANSPORT"
  | "VIWO"
  | "VNM_VIETNAM_POST"
  | "VNM_VIETTELPOST"
  | "WAHANA_ID"
  | "WANBEXPRESS"
  | "WEASHIP"
  | "WEPOST"
  | "WESTBANK_COURIER"
  | "WESTGATE_GL"
  | "WHISTL"
  | "WINIT"
  | "WISELOADS"
  | "WISE_EXPRESS"
  | "WIZMO"
  | "WMG"
  | "WNDIRECT"
  | "WYNGS"
  | "XDE_WEBHOOK"
  | "XDP_UK_REFERENCE"
  | "XL_EXPRESS"
  | "XPERT_DELIVERY"
  | "XPOST"
  | "XPO_LOGISTICS"
  | "XPRESSEN_DK"
  | "XQ_EXPRESS"
  | "YAKIT"
  | "YANWEN"
  | "YDH_EXPRESS"
  | "YINGNUO_LOGISTICS"
  | "YODEL_DIR"
  | "YODEL_INTNL"
  | "YTO"
  | "YUNEXPRESS"
  | "YURTICI_KARGO"
  | "YUSEN"
  | "ZAJIL_EXPRESS"
  | "ZA_COURIERIT"
  | "ZA_FASTWAY"
  | "ZA_SPECIALISED_FREIGHT"
  | "ZEEK_2_DOOR"
  | "ZELERIS"
  | "ZEPTO_EXPRESS"
  | "ZES_EXPRESS"
  | "ZIINGFINALMILE"
  | "ZINC"
  | "ZJS_EXPRESS"
  | "ZTO_EXPRESS"
  | "ZYLLEM";

/**
 * The stand-alone date, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). To represent special legal values, such as a date of birth, you should use dates with no associated time or time-zone data. Whenever possible, use the standard `date_time` type. This regular expression does not validate all dates. For example, February 31 is valid and nothing is known about leap years.
 *
 * @format ppaas_date_notime_v2
 */
export type DateNoTime = string;

/**
 * The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional.<blockquote><strong>Note:</strong> The regular expression provides guidance but does not reject all invalid dates.</blockquote>
 *
 * @format ppaas_date_time_v3
 */
export type DateTime = string;

/** The request-related [HATEOAS link](/api/rest/responses/#hateoas-links) information. */
export type ErrorLinkDescription = {
  /** The complete target URL. To make the related call, combine the method with this [URI Template-formatted](https://tools.ietf.org/html/rfc6570) link. For pre-processing, include the `$`, `(`, and `)` characters. The `href` is the key HATEOAS component that links a completed call with a subsequent call. */
  href: string;
  /** The [link relation type](https://tools.ietf.org/html/rfc5988#section-4), which serves as an ID for a link that unambiguously describes the semantics of the link. See [Link Relations](https://www.iana.org/assignments/link-relations/link-relations.xhtml). */
  rel: string;
  method?: "GET" | "POST" | "PUT" | "DELETE" | "PATCH";
};

/** This is either a system or application error, and generally indicates that although the client appeared to provide a correct request, something unexpected has gone wrong on the server. */
export type Error500 = {
  name?: "INTERNAL_SERVER_ERROR";
  message?: "An internal server error occurred.";
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** The server is temporarily unable to handle the request, for example, because of planned maintenance or downtime. */
export type Error503 = {
  name?: "SERVICE_UNAVAILABLE";
  message?: "Service Unavailable.";
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

export type ErrorLocation = "body" | "path" | "query";

/** The error details. Required for client-side `4XX` errors. */
export type ErrorDetails = {
  /** The field that caused the error. If this field is in the body, set this value to the field's JSON pointer value. Required for client-side errors. */
  field?: string;
  /** The value of the field that caused the error. */
  value?: string;
  location?: ErrorLocation;
  /** The unique, fine-grained application-level error code. */
  issue: string;
  /** The human-readable description for an issue. The description can change over the lifetime of an API, so clients must not depend on this value. */
  description?: string;
};

/** Request is not well-formed, syntactically incorrect, or violates schema. */
export type Error400 = {
  name?: "INVALID_REQUEST";
  message?: "Request is not well-formed, syntactically incorrect, or violates schema.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** Authentication failed due to missing Authorization header, or invalid authentication credentials. */
export type Error401 = {
  name?: "AUTHENTICATION_FAILURE";
  message?: "Authentication failed due to missing authorization header, or invalid authentication credentials.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** The client is not authorized to access this resource, although it may have valid credentials.  */
export type Error403 = {
  name?: "NOT_AUTHORIZED";
  message?: "Authorization failed due to insufficient permissions.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** The server has not found anything matching the request URI. This either means that the URI is incorrect or the resource is not available. */
export type Error404 = {
  name?: "RESOURCE_NOT_FOUND";
  message?: "The specified resource does not exist.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** The server has detected a conflict while processing this request. */
export type Error409 = {
  name?: "RESOURCE_CONFLICT";
  message?: "The server has detected a conflict while processing this request.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** The server does not support the request payload's media type. */
export type Error415 = {
  name?: "UNSUPPORTED_MEDIA_TYPE";
  message?: "The server does not support the request payload's media type.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** The requested action cannot be performed and may require interaction with APIs or processes outside of the current request. This is distinct from a 500 response in that there are no systemic problems limiting the API from performing the request. */
export type Error422 = {
  name?: "UNPROCESSABLE_ENTITY";
  message?: "The requested action could not be performed, semantically incorrect, or failed business validation.";
  details?: ErrorDetails[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
  links?: ErrorLinkDescription[];
};

/** A request-related [HATEOAS link](/api/rest/responses/#hateoas-links). */
export type LinkDescription = {
  /** The complete target URL. To make the related call, combine the method with this link, in [URI template format](https://tools.ietf.org/html/rfc6570). Include the `$`, `(`, and `)` characters for pre-processing. The `href` is the key HATEOAS component that links a completed call with a subsequent call. */
  href: string;
  /** The [link relation type](https://tools.ietf.org/html/rfc5988#section-4), which serves as an ID for a link that unambiguously describes the semantics of the link. See [Link Relations](https://www.iana.org/assignments/link-relations/link-relations.xhtml). */
  rel: string;
  method?: "GET" | "POST" | "PUT" | "DELETE" | "HEAD" | "CONNECT" | "OPTIONS" | "PATCH";
};

/** An array of request-related [HATEOAS links](/docs/api/reference/api-responses/#hateoas-links). */
export type BatchTrackerCollectionDefinitionsLinkDescriptionList = LinkDescription[];

/** The request-related [HATEOAS link](/api/rest/responses/#hateoas-links) information. */
export type LinkDescription2 = {
  /** The complete target URL. To make the related call, combine the method with this [URI Template-formatted](https://tools.ietf.org/html/rfc6570) link. For pre-processing, include the `$`, `(`, and `)` characters. The `href` is the key HATEOAS component that links a completed call with a subsequent call. */
  href: string;
  /** The [link relation type](https://tools.ietf.org/html/rfc5988#section-4), which serves as an ID for a link that unambiguously describes the semantics of the link. See [Link Relations](https://www.iana.org/assignments/link-relations/link-relations.xhtml). */
  rel: string;
  method?: "GET" | "POST" | "PUT" | "DELETE" | "HEAD" | "CONNECT" | "OPTIONS" | "PATCH";
};

/** An array of request-related [HATEOAS links](/api/rest/responses/#hateoas-links) that are either relevant to the issue by providing additional information or offering potential resolutions. */
export type DefinitionsLinkDescriptionList = LinkDescription2[];

/** An array of request-related [HATEOAS links](/api/rest/responses/#hateoas-links). */
export type ErrorDefinitionsLinkDescriptionList = LinkDescription2[];

/** The error details. Required for client-side `4XX` errors. */
export type ErrorDetails2 = {
  /** The field that caused the error. If this field is in the body, set this value to the field's JSON pointer value. Required for client-side errors. */
  field?: string;
  /** The value of the field that caused the error. */
  value?: string;
  /** The location of the field that caused the error. Value is `body`, `path`, or `query`. */
  location?: string;
  /** The unique, fine-grained application-level error code. */
  issue: string;
  /** The human-readable description for an issue. The description can change over the lifetime of an API, so clients must not depend on this value. */
  description?: string;
  links?: DefinitionsLinkDescriptionList;
};

/** An array of additional details about the error. */
export type ErrorDetailsList = ErrorDetails2[];

/** The error details. */
export type Error = {
  /** The human-readable, unique name of the error. */
  name: string;
  /** The message that describes the error. */
  message: string;
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id: string;
  /** The information link, or URI, that shows detailed information about this error for the developer. */
  information_link?: string;
  details?: ErrorDetailsList;
  links?: ErrorDefinitionsLinkDescriptionList;
};

/** An array of error responses. */
export type ErrorList = Error[];

/** An array of request-related [HATEOAS links](/docs/api/reference/api-responses/#hateoas-links). */
export type LinkDescriptionList = LinkDescription[];

/** The tracking identifiers for a shipment. */
export type TrackerIdentifier = {
  /** The PayPal transaction ID. */
  transaction_id: string;
  /** The tracking number for the shipment. */
  tracking_number?: string;
  links?: LinkDescriptionList;
};

/** An array of tracking IDs. */
export type DefinitionsTrackerIdentifierList = TrackerIdentifier[];

/** An array of request-related [HATEOAS links](/docs/api/reference/api-responses/#hateoas-links). */
export type TrackerIdentifierCollectionDefinitionsLinkDescriptionList = LinkDescription[];

/** The add tracking information for a PayPal transaction response details. */
export type TrackerIdentifierCollection = {
  tracker_identifiers?: DefinitionsTrackerIdentifierList;
  links?: TrackerIdentifierCollectionDefinitionsLinkDescriptionList;
};

/** The batch header. */
export type TrackerIdentifierList = TrackerIdentifier[];

/** The add tracking information for multiple PayPal transactions response details. */
export type BatchTrackerCollection = {
  tracker_identifiers?: TrackerIdentifierList;
  errors?: ErrorList;
  links?: BatchTrackerCollectionDefinitionsLinkDescriptionList;
};

export type TrackingNumberType = "CARRIER_PROVIDED" | "E2E_PARTNER_PROVIDED";

export type TrackingStatus =
  | "CANCELLED"
  | "DELIVERED"
  | "LOCAL_PICKUP"
  | "ON_HOLD"
  | "SHIPPED"
  | "SHIPMENT_CREATED"
  | "DROPPED_OFF"
  | "IN_TRANSIT"
  | "RETURNED"
  | "LABEL_PRINTED"
  | "ERROR"
  | "UNCONFIRMED"
  | "PICKUP_FAILED"
  | "DELIVERY_DELAYED"
  | "DELIVERY_SCHEDULED"
  | "DELIVERY_FAILED"
  | "INRETURN"
  | "IN_PROCESS"
  | "NEW"
  | "VOID"
  | "PROCESSED"
  | "NOT_SHIPPED"
  | "COMPLETED";

/** The tracking information for a shipment. */
export type Tracker = {
  /** The PayPal transaction ID. */
  transaction_id: string;
  /** The tracking number for the shipment. Carrier information, `carrier` is required if tracking_number is provided. */
  tracking_number?: string;
  tracking_number_type?: TrackingNumberType;
  status: TrackingStatus;
  shipment_date?: DateNoTime;
  carrier?: Carrier;
  /** The name of the carrier for the shipment. Provide this value only if the carrier parameter is OTHER. */
  carrier_name_other?: string;
  /** The postage payment ID. */
  postage_payment_id?: string;
  /** If true , sends an email notification to the buyer of the PayPal transaction. The email contains the tracking information that was uploaded through the API. */
  notify_buyer?: boolean;
  /** The quantity of items shipped. */
  quantity?: number;
  /** Indicates whether the carrier validated the tracking number. */
  tracking_number_validated?: boolean;
  last_updated_time?: DateTime;
  shipment_direction?: "FORWARD" | "RETURN";
  shipment_uploader?: "MERCHANT" | "CONSUMER" | "PARTNER";
  /** Encrypted PayPal Account ID of the buyer or seller. */
  account_id?: string;
  /**
   * Tracking Link of the shipment.
   *
   * @format uri
   */
  tracking_url?: string;
  links?: LinkDescriptionList;
};

/** An array of tracking information for shipments. */
export type TrackerList = Tracker[];

/** The add tracking information for one or more transactions response details. */
export type TrackerCollection = {
  trackers?: TrackerList;
  links?: LinkDescriptionList;
};

export const CarrierSchema: z.ZodType<Carrier> = z.enum([
  "2EBOX",
  "360LION",
  "3JMSLOGISTICS",
  "4_72",
  "6LS",
  "A1POST",
  "AAA_COOPER",
  "ABCUSTOM",
  "ABXEXPRESS_MY",
  "ACOMMMERCE",
  "ACSWORLDWIDE",
  "ACS_GR",
  "ADERONLINE",
  "ADICIONAL",
  "ADSONE",
  "ADUIEPYLE",
  "AERONET",
  "AEX",
  "AFLLOG_FTP",
  "AGILITY",
  "AIRMEE_WEBHOOK",
  "AIR_CANADA_GLOBAL",
  "ALFATREX",
  "ALLIEDEXPRESS",
  "ALLJOY",
  "ALPHAFAST",
  "ALWAYS_EXPRESS",
  "AMAZON",
  "AMAZON_FBA_SWISHIP",
  "AMAZON_SHIP_MCF",
  "AMSTAN",
  "AMS_GRP",
  "ANDREANI",
  "ANICAM_BOX",
  "ANJUN",
  "ANSERX",
  "AN_POST",
  "AO_COURIER",
  "AO_DEUTSCHLAND",
  "APC_OVERNIGHT",
  "APC_OVERNIGHT_CONNUM",
  "APG",
  "APRISAEXPRESS",
  "AQUILINE",
  "ARAMEX",
  "ARAMEX_AU",
  "ARCO_SPEDIZIONI",
  "ARE_EMIRATES_POST",
  "ARG_OCA",
  "ARK_LOGISTICS",
  "ASE",
  "ASENDIA_HK",
  "ASENDIA_UK",
  "ASENDIA_USA",
  "ASIGNA",
  "AUPOST_CN",
  "AUSTRIAN_POST_EXPRESS",
  "AUS_STARTRACK",
  "AUS_TOLL",
  "AU_AUSTRIAN_POST",
  "AU_AU_POST",
  "AU_TNT",
  "AVERITT",
  "BEL_DHL",
  "BEL_RS",
  "BESTWAYPARCEL",
  "BE_BPOST",
  "BE_KIALA",
  "BG_BULGARIAN_POST",
  "BH_POSTA",
  "BH_WORLDWIDE",
  "BIRDSYSTEM",
  "BJSHOMEDELIVERY",
  "BLINKLASTMILE",
  "BLR_BELPOST",
  "BLUECARE",
  "BLUESTAR",
  "BLUEX",
  "BNEED",
  "BOMBINOEXP",
  "BOND",
  "BONDSCOURIERS",
  "BORDEREXPRESS",
  "BOX_BERRY",
  "BPOST_INT",
  "BRA_CORREIOS",
  "BRING",
  "BROUWER_TRANSPORT",
  "BRT_IT",
  "BRT_IT_PARCELID",
  "BRT_IT_SENDER_REF",
  "BUDBEE_WEBHOOK",
  "BUYLOGIC",
  "B_TWO_C_EUROPE",
  "CAE_DELIVERS",
  "CAINIAO",
  "CARIBOU",
  "CARRIERS",
  "CARRY_FLAP",
  "CA_CANADA_POST",
  "CA_CANPAR",
  "CA_GREYHOUND",
  "CA_PUROLATOR",
  "CBL_LOGISTICA",
  "CDEK",
  "CDEK_TR",
  "CELERITAS",
  "CELLO_SQUARE",
  "CESKA_CZ",
  "CEVA",
  "CFL_LOGISTICS",
  "CGS_EXPRESS",
  "CHAMPION_LOGISTICS",
  "CHITCHATS",
  "CHOIR_EXP",
  "CHROBINSON",
  "CHRONOPOST_FR",
  "CHUKOU1",
  "CH_SWISS_POST_PRIORITY",
  "CITYLINK_MY",
  "CJPACKET",
  "CJ_CENTURY",
  "CJ_GLS",
  "CJ_HK_INTERNATIONAL",
  "CJ_INT_MY",
  "CJ_KR",
  "CJ_LOGISTICS",
  "CJ_TH",
  "CLEVY_LINKS",
  "CLE_LOGISTICS",
  "CLOUDWISH_ASIA",
  "CNDEXPRESS",
  "CNEXPS",
  "CNWANGTONG",
  "CN_17POST",
  "CN_BESTEXPRESS",
  "CN_BOXC",
  "CN_CHINA_POST_EMS",
  "CN_DPEX",
  "CN_EMS",
  "CN_EQUICK",
  "CN_JCEX",
  "CN_PAYPAL_PACKAGE",
  "CN_POST56",
  "CN_SF_EXPRESS",
  "CN_STO",
  "CN_WEDO",
  "CN_WISHPOST",
  "CN_YUNDA",
  "COLIS_PRIVE",
  "COLLECTCO",
  "COLLIVERY",
  "COMET_TECH",
  "CONTINENTAL",
  "CON_WAY",
  "COORDINADORA",
  "COPA_COURIER",
  "COPE",
  "CORPORATECOURIERS_WEBHOOK",
  "CORREOS_DE_MEXICO",
  "CORREOS_ES",
  "CORREOS_EXPRESS",
  "CORREO_UY",
  "COSTMETICSNOW",
  "COURANT_PLUS",
  "COUREX",
  "COURIERS_PLEASE",
  "CPACKET",
  "CPEX",
  "CROSHOT",
  "CSE",
  "CTC_EXPRESS",
  "CUBYN",
  "CUCKOOEXPRESS",
  "CYPRUS_POST_CYP",
  "DAIGLOBALTRACK",
  "DAJIN",
  "DANSKE_FRAGT",
  "DAWN_WING",
  "DAYTON_FREIGHT",
  "DBSCHENKER_B2B",
  "DBSCHENKER_SE",
  "DBSCHENKER_SV",
  "DDEXPRESS",
  "DEALERSEND",
  "DELIVERYONTIME",
  "DELNEXT",
  "DELTEC_UK",
  "DEMANDSHIP",
  "DESCARTES",
  "DESIGNERTRANSPORT_WEBHOOK",
  "DESTINY",
  "DEX_I",
  "DE_ASENDIA",
  "DE_DEUTSCHE",
  "DE_DEUTSCHE_POST_DHL_WITHIN_EUROPE_TRACKNET",
  "DE_DHL_EXPRESS",
  "DE_DPD_DELISTRACK",
  "DE_GLS",
  "DHL",
  "DHL_ACTIVE_TRACING",
  "DHL_AU",
  "DHL_BENELUX",
  "DHL_ECOMERCE_ASA",
  "DHL_ES",
  "DHL_FR",
  "DHL_FREIGHT",
  "DHL_GLOBAL_MAIL_ASIA",
  "DHL_HK",
  "DHL_JP",
  "DHL_PARCEL_ES",
  "DHL_PARCEL_NL",
  "DHL_PARCEL_RU",
  "DHL_PL",
  "DHL_REFR",
  "DHL_SG",
  "DHL_SUPPLY_CHAIN",
  "DHL_UK",
  "DIAMOND_EUROGISTICS",
  "DICOM",
  "DIDADI",
  "DIMERCO",
  "DIRECTCOURIERS",
  "DIRECTLOG",
  "DIRECTPARCELS",
  "DMM_NETWORK",
  "DMS_MATRIX",
  "DOBROPOST",
  "DOORA",
  "DOORDASH_WEBHOOK",
  "DPD",
  "DPD_DELISTRACK",
  "DPD_FR",
  "DPD_HGRY",
  "DPD_HK",
  "DPD_IR",
  "DPD_LOCAL",
  "DPD_LOCAL_REF",
  "DPD_POLAND",
  "DPD_RO",
  "DPD_RU",
  "DPEX",
  "DPE_EXPRESS",
  "DPE_SOUTH_AFRC",
  "DSV",
  "DTDC_AU",
  "DTDC_EXPRESS",
  "DTDC_IN",
  "DTD_EXPR",
  "DX_SFTP",
  "DYLT",
  "DYNALOGIC",
  "EASY_MAIL",
  "ECEXPRESS",
  "ECHO",
  "ECMS",
  "ECOSCOOTING",
  "EFEX",
  "EFS",
  "EKART",
  "ELIAN_POST",
  "EMPS_CN",
  "ENDEAVOUR_DELIVERY",
  "ENVIALIA_REFERENCE",
  "EPARCEL_KR",
  "EPST_GLBL",
  "EP_BOX",
  "ESHIPPING",
  "ESP_ASM",
  "ESP_ENVIALIA",
  "ESP_MRW",
  "ESP_NACEX",
  "ESP_PACKLINK",
  "ESP_REDUR",
  "ETOMARS",
  "ETOTAL",
  "ETS_EXPRESS",
  "EU_FLEET_SOLUTIONS",
  "EU_IMX",
  "EXPRESSSALE",
  "FARGOOD",
  "FAR_INTERNATIONAL",
  "FASTRACK",
  "FASTRK_SERV",
  "FASTWAY_IR",
  "FASTWAY_NZ",
  "FDSEXPRESS",
  "FEDEX",
  "FEDEX_CROSSBORDER",
  "FEDEX_FR",
  "FEDEX_INTL_MLSERV",
  "FEDEX_POLAND",
  "FEDEX_UK",
  "FETCHR_WEBHOOK",
  "FIEGE",
  "FIEGE_NL",
  "FIRSTMILE",
  "FLASHEXPRESS",
  "FMX",
  "FONSEN",
  "FORRUN",
  "FREIGHTQUOTE",
  "FRETERAPIDO",
  "FR_BERT",
  "FR_COLIS",
  "FR_EXAPAQ",
  "FR_GEODIS",
  "FR_GLS",
  "FULFILLA",
  "FULFILLME",
  "FURDECO",
  "GAC",
  "GANGBAO",
  "GBA",
  "GBS_BROKER",
  "GB_APC",
  "GB_ARROW",
  "GB_NORSK",
  "GB_PANTHER",
  "GB_TUFFNELLS",
  "GEIS",
  "GEL_EXPRESS",
  "GEMWORLDWIDE",
  "GENERAL_OVERNIGHT",
  "GENIKI_GR",
  "GEODIS_ESPACE",
  "GESWL",
  "GIAO_HANG",
  "GIO_EXPRESS",
  "GLOBALTRANZ",
  "GLOBAL_ABF",
  "GLOBAL_ESTES",
  "GLOBAL_EXPRESS",
  "GLOBAL_IPARCEL",
  "GLOBAL_TNT",
  "GLOBAVEND",
  "GLS_CROTIA",
  "GLS_CZ",
  "GLS_IT",
  "GLS_ITALY",
  "GLS_SLOV",
  "GLS_SLOVEN",
  "GOGLOBALPOST",
  "GOJEK",
  "GRAB_WEBHOOK",
  "GRUPO",
  "GR_ELTA",
  "GSI_EXPRESS",
  "GSO",
  "HAPPY2POINT",
  "HCT_LOGISTICS",
  "HDB",
  "HDB_BOX",
  "HELLMANN",
  "HELTHJEM",
  "HEPPNER",
  "HEPPNER_FR",
  "HERMES",
  "HERMES_2MANN_HANDLING",
  "HERMES_DE",
  "HH_EXP",
  "HIPSHIPPER",
  "HKD",
  "HK_FLYT_EXPRESS",
  "HK_FOUR_PX_EXPRESS",
  "HK_POST",
  "HK_TGX",
  "HOLISOL",
  "HOME_DELIVERY_SOLUTIONS",
  "HOUNDEXPRESS",
  "HRPARCEL",
  "HRV_HRVATSKA",
  "HUAHAN_EXPRESS",
  "HUNTER_EXPRESS",
  "HUODULL",
  "HX_EXPRESS",
  "IBEONE",
  "ICUMULUS",
  "IDEXPRESS",
  "IDN_JNE",
  "IDN_LION_PARCEL",
  "IDN_PANDU",
  "IML",
  "INDOPAKET",
  "IND_BLUEDART",
  "IND_DELHIVERY",
  "IND_DELIVREE",
  "IND_DOTZOT",
  "IND_ECOM",
  "IND_FIRSTFLIGHT",
  "IND_GATI",
  "IND_GOJAVAS",
  "IND_PROFESSIONAL_COURIERS",
  "IND_SAFEEXPRESS",
  "IND_XPRESSBEES",
  "INPOST_PACZKOMATY",
  "INTEGRA2_FTP",
  "INTELIPOST",
  "INTEL_VALLEY",
  "INTERPARCEL_AU",
  "INTERPARCEL_NZ",
  "INTERPARCEL_UK",
  "INTEXPRESS",
  "ISRAEL_POST",
  "ISR_POST_DOMESTIC",
  "IT_DHL_ECOMMERCE",
  "IT_FERCAM",
  "IT_NEXIVE",
  "IT_POSTE_ITALIA",
  "IT_TNT",
  "IVOY_WEBHOOK",
  "I_DIKA",
  "JANCO",
  "JANIO",
  "JERSEY_POST",
  "JET_SHIP",
  "JINDOUYUN",
  "JINSUNG",
  "JOCOM",
  "JOOM_LOGIS",
  "JOYING_BOX",
  "JPN_JAPAN_POST",
  "JPN_SAGAWA",
  "JP_KURO_NEKO_YAMATO_UNYUU",
  "JS_EXPRESS",
  "JTEXPRESS",
  "JTEXPRESS_VN",
  "JX",
  "J_NET",
  "K1_EXPRESS",
  "KANGAROO_MY",
  "KEC",
  "KERRYTJ",
  "KERRYTTC_VN",
  "KERRY_ECOMMERCE",
  "KGMHUB",
  "KHM_CAMBODIA_POST",
  "KOR_ECARGO",
  "KPOST",
  "KR_KOREA_POST",
  "KUEHNE",
  "KURASI",
  "KWE_GLOBAL",
  "KWT",
  "KYUNGDONG_PARCEL",
  "KY_EXPRESS",
  "LALAMOVE",
  "LANDMARK_GLOBAL",
  "LANDMARK_GLOBAL_REFERENCE",
  "LATVIJAS_PASTS",
  "LA_POSTE_SUIVI",
  "LBCEXPRESS_FTP",
  "LEADER",
  "LEGION_EXPRESS",
  "LEXSHIP",
  "LHT_EXPRESS",
  "LICCARDI_EXPRESS",
  "LIEFERY",
  "LINE",
  "LINKBRIDGE",
  "LOCUS_WEBHOOK",
  "LOGISTERS",
  "LOGISTICSWORLDWIDE_HK",
  "LOGISTIKA",
  "LOGISTYX_TRANSGROUP",
  "LONESTAR",
  "LOOMIS_EXPRESS",
  "LOTTE",
  "LTIANEXP",
  "LTL",
  "LTU_LIETUVOS",
  "MAGYAR_HU",
  "MAILAMERICAS",
  "MAILPLUS_JPN",
  "MAIL_PLUS",
  "MAINFREIGHT",
  "MAINWAY",
  "MATDESPATCH",
  "MATKAHUOLTO",
  "MBW",
  "MEX_AEROFLASH",
  "MEX_ESTAFETA",
  "MEX_REDPACK",
  "MEX_SENDA",
  "MGLOBAL",
  "MIKROPAKKET",
  "MIKROPAKKET_BE",
  "MILKMAN",
  "MORE_LINK",
  "MORNING_EXPRESS",
  "MRW_FTP",
  "MXE",
  "MX_CARGO",
  "MYHERMES",
  "MYS_AIRPAK",
  "MYS_EMS",
  "MYS_GDEX",
  "MYS_MYPOST_ONLINE",
  "MYS_MYS_POST",
  "MYS_SKYNET",
  "M_XPRESS",
  "NACEX",
  "NACEX_ES",
  "NANJINGWOYUAN",
  "NATIONAL_SAMEDAY",
  "NATIONEX",
  "NATIONWIDE_MY",
  "NEWAY",
  "NEWEGGEXPRESS",
  "NEWGISTICS",
  "NEWZEALAND_COURIERS",
  "NG_COURIERPLUS",
  "NHANS_SOLUTIONS",
  "NIM_EXPRESS",
  "NINJAVAN_MY",
  "NINJAVAN_SG",
  "NINJAVAN_THAI",
  "NINJAVAN_WB",
  "NIPOST_NG",
  "NLD_DHL",
  "NLD_GLS",
  "NLD_POSTNL",
  "NLD_TRANSMISSION",
  "NOVA_POSHTA",
  "NOVA_POSHTA_INT",
  "NOX_NACHTEXPRESS",
  "NOX_NIGHT_TIME_EXPRESS",
  "NTLOGISTICS_VN",
  "NZ_COURIER_POST",
  "NZ_NZ_POST",
  "OCS",
  "OCS_WORLDWIDE",
  "OKAYPARCEL",
  "OMNIPARCEL",
  "OMNIVA",
  "ONECLICK",
  "ONEWORLDEXPRESS",
  "ORANGE_DS",
  "OSM_WORLDWIDE",
  "OVERSE_EXP",
  "P2P_TRC",
  "PAACK_WEBHOOK",
  "PADTF",
  "PAGO",
  "PALEXPRESS",
  "PALLETWAYS",
  "PALLET_NETWORK",
  "PANTHER_REFERENCE",
  "PAN_ASIA",
  "PAPERFLY",
  "PAPER_EXPRESS",
  "PAQUETEXPRESS",
  "PARCEL2GO",
  "PARCELINKLOGISTICS",
  "PARCELLED_IN",
  "PARCELONE",
  "PARCELPAL_WEBHOOK",
  "PARCELPOINT",
  "PARCELPOST_SG",
  "PARCEL_2_POST",
  "PARKNPARCEL",
  "PCFCORP",
  "PFCEXPRESS",
  "PFLOGISTICS",
  "PHL_AIR21",
  "PHL_AIRSPEED",
  "PHL_JAMEXPRESS",
  "PICKRR",
  "PICKUP",
  "PICKUPP_MYS",
  "PICKUPP_SGP",
  "PILOT_FREIGHT",
  "PIL_LOGISTICS",
  "PITNEY_BOWES",
  "PITTOHIO",
  "PIXSELL",
  "PLANZER",
  "PLUS_LOG_UK",
  "PL_POCZTA_POLSKA",
  "POL_SIODEMKA",
  "PONY_EXPRESS",
  "POSTA_PLUS",
  "POSTA_RO",
  "POSTA_UKR",
  "POSTEN_NORGE",
  "POSTI",
  "POSTNL_INTL_3S",
  "POSTNL_INT_3_S",
  "POSTNORD_LOGISTICS",
  "POSTNORD_LOGISTICS_DK",
  "POSTUR_IS",
  "POST_SERBIA",
  "POST_SLOVENIA",
  "PRESIDENT_TRANS",
  "PRESSIODE",
  "PRIMAMULTICIPTA",
  "PROMEDDELIVERY",
  "PRT_CHRONOPOST",
  "PRT_CTT",
  "PRT_INT_SEUR",
  "PRT_SEUR",
  "PTS",
  "PTT_POST",
  "QUANTIUM",
  "QWINTRY",
  "RABEN_GROUP",
  "RAF_PH",
  "RAIDEREX",
  "RAM",
  "RCL",
  "RINCOS",
  "RL_US",
  "ROADBULL",
  "ROADRUNNER_FREIGHT",
  "ROCKET_PARCEL",
  "ROUTIFIC_WEBHOOK",
  "ROYAL_MAIL",
  "RPD2MAN",
  "RPX",
  "RPXLOGISTICS",
  "RPX_ID",
  "RUSSIAN_POST",
  "RUSTON",
  "RZYEXPRESS",
  "SAIA_FREIGHT",
  "SAILPOST",
  "SAP_EXPRESS",
  "SAU_SAUDI_POST",
  "SCUDEX_EXPRESS",
  "SDA_IT",
  "SDH_SCM",
  "SEFL",
  "SEINO",
  "SEKOLOGISTICS",
  "SEKO_SFTP",
  "SENDING",
  "SENDIT",
  "SENDLE",
  "SEUR_ES",
  "SEUR_SP_API",
  "SFB2C",
  "SFCSERVICE",
  "SFC_LOGISTICS",
  "SFPLUS_WEBHOOK",
  "SF_EX",
  "SG_DETRACK",
  "SG_QXPRESS",
  "SG_SG_POST",
  "SG_SPEEDPOST",
  "SG_TAQBIN",
  "SHENZHEN",
  "SHIPENTEGRA",
  "SHIPPIT",
  "SHIPTER",
  "SHIPTOR",
  "SHIP_GATE",
  "SHIP_IT_ASIA",
  "SHOPFANS",
  "SHREENANDANCOURIER",
  "SHREETIRUPATI",
  "SHREE_ANJANI_COURIER",
  "SHREE_MARUTI",
  "SIMPLYPOST",
  "SINOTRANS",
  "SIN_GLBL",
  "SKYBOX",
  "SKYNET_UAE",
  "SKYNET_UK",
  "SKYNET_WORLDWIDE",
  "SKYNET_ZA",
  "SKY_POSTAL",
  "SK_POSTA",
  "SMG_EXPRESS",
  "SMOOTH",
  "SMSA_EXPRESS",
  "SONICTL",
  "SOUTH_AFRICAN_POST_OFFICE",
  "SPEEDCOURIERS_GR",
  "SPEEDEE",
  "SPEEDEXCOURIER",
  "SPOTON",
  "SPRING_GDS",
  "SRE_KOREA",
  "STALLIONEXPRESS",
  "STARKEN",
  "STAR_TRACK_EXPRESS",
  "STAR_TRACK_NEXT_FLIGHT",
  "STEPFORWARDFS",
  "STONE3PL",
  "STRECK_TRANSPORT",
  "SUTTON",
  "SWE_POSTNORD",
  "SWISHIP_DE",
  "SWISS_POST_FTP",
  "SYPOST",
  "SZENDEX",
  "TAQBIN_HK",
  "TAQBIN_MY",
  "TARRIVE",
  "TAZMANIAN_FREIGHT",
  "TCK_EXPRESS",
  "TCS",
  "TFM",
  "TFORCE_FINALMILE",
  "THABIT_LOGISTICS",
  "THA_DYNAMIC_LOGISTICS",
  "THA_KERRY",
  "THA_THAILAND_POST",
  "THECOURIERGUY",
  "THEDELIVERYGROUP",
  "THENILE_WEBHOOK",
  "TIGFREIGHT",
  "TIKI_ID",
  "TIPSA",
  "TNT",
  "TNT_CLICK_IT",
  "TNT_FR",
  "TNT_NL",
  "TNT_REFR",
  "TNT_UK",
  "TNT_UK_REFR",
  "TOLL",
  "TOLL_NZ",
  "TOLOS",
  "TOPHATTEREXPRESS",
  "TOPYOU",
  "TOTAL_EXPRESS",
  "TOURLINE",
  "TRACKON",
  "TRANS_KARGO",
  "TRUMPCARD",
  "TRUNKRS_WEBHOOK",
  "TUFFNELLS_REFERENCE",
  "TWO_GO",
  "TW_TAIWAN_POST",
  "UBI_LOGISTICS",
  "UC_EXPRE",
  "UDS",
  "UK_COLLECTPLUS",
  "UK_DPD",
  "UK_NIGHTLINE",
  "UK_PARCELFORCE",
  "UK_UK_MAIL",
  "UK_XDP",
  "UK_YODEL",
  "UPS",
  "UPS_FREIGHT",
  "UPS_MAIL_INNOVATIONS",
  "UPS_REFERENCE",
  "USF_REDDAWAY",
  "USHIP",
  "USPS",
  "US_GLOBEGISTICS",
  "US_LASERSHIP",
  "US_OLD_DOMINION",
  "US_ONTRAC",
  "US_YRC",
  "VAMOX",
  "VENIPAK",
  "VIAEUROPE",
  "VIA_EXPRESS",
  "VIRTRANSPORT",
  "VIWO",
  "VNM_VIETNAM_POST",
  "VNM_VIETTELPOST",
  "WAHANA_ID",
  "WANBEXPRESS",
  "WEASHIP",
  "WEPOST",
  "WESTBANK_COURIER",
  "WESTGATE_GL",
  "WHISTL",
  "WINIT",
  "WISELOADS",
  "WISE_EXPRESS",
  "WIZMO",
  "WMG",
  "WNDIRECT",
  "WYNGS",
  "XDE_WEBHOOK",
  "XDP_UK_REFERENCE",
  "XL_EXPRESS",
  "XPERT_DELIVERY",
  "XPOST",
  "XPO_LOGISTICS",
  "XPRESSEN_DK",
  "XQ_EXPRESS",
  "YAKIT",
  "YANWEN",
  "YDH_EXPRESS",
  "YINGNUO_LOGISTICS",
  "YODEL_DIR",
  "YODEL_INTNL",
  "YTO",
  "YUNEXPRESS",
  "YURTICI_KARGO",
  "YUSEN",
  "ZAJIL_EXPRESS",
  "ZA_COURIERIT",
  "ZA_FASTWAY",
  "ZA_SPECIALISED_FREIGHT",
  "ZEEK_2_DOOR",
  "ZELERIS",
  "ZEPTO_EXPRESS",
  "ZES_EXPRESS",
  "ZIINGFINALMILE",
  "ZINC",
  "ZJS_EXPRESS",
  "ZTO_EXPRESS",
  "ZYLLEM",
]);

export const DateNoTimeSchema: z.ZodType<DateNoTime> = z.string().regex(
  new RegExp("^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$"),
).min(10).max(10);

export const DateTimeSchema: z.ZodType<DateTime> = z.string().regex(
  new RegExp(
    "^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])[T,t]([0-1][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)([.][0-9]+)?([Zz]|[+-][0-9]{2}:[0-9]{2})$",
  ),
).min(20).max(64);

export const ErrorLinkDescriptionSchema: z.ZodType<ErrorLinkDescription> = z.object({
  href: z.string().regex(new RegExp("^.*$")).min(0).max(20000),
  rel: z.string().regex(new RegExp("^.*$")).min(0).max(100),
  method: z.enum(["GET", "POST", "PUT", "DELETE", "PATCH"]).optional(),
});

export const Error500Schema: z.ZodType<Error500> = z.object({
  name: z.enum(["INTERNAL_SERVER_ERROR"]).optional(),
  message: z.enum(["An internal server error occurred."]).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error503Schema: z.ZodType<Error503> = z.object({
  name: z.enum(["SERVICE_UNAVAILABLE"]).optional(),
  message: z.enum(["Service Unavailable."]).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const ErrorLocationSchema: z.ZodType<ErrorLocation> = z.enum(["body", "path", "query"]);

export const ErrorDetailsSchema: z.ZodType<ErrorDetails> = z.object({
  field: z.string().optional(),
  value: z.string().optional(),
  location: ErrorLocationSchema.optional(),
  issue: z.string(),
  description: z.string().optional(),
});

export const Error400Schema: z.ZodType<Error400> = z.object({
  name: z.enum(["INVALID_REQUEST"]).optional(),
  message: z.enum(["Request is not well-formed, syntactically incorrect, or violates schema."]).optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error401Schema: z.ZodType<Error401> = z.object({
  name: z.enum(["AUTHENTICATION_FAILURE"]).optional(),
  message: z.enum(["Authentication failed due to missing authorization header, or invalid authentication credentials."])
    .optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error403Schema: z.ZodType<Error403> = z.object({
  name: z.enum(["NOT_AUTHORIZED"]).optional(),
  message: z.enum(["Authorization failed due to insufficient permissions."]).optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error404Schema: z.ZodType<Error404> = z.object({
  name: z.enum(["RESOURCE_NOT_FOUND"]).optional(),
  message: z.enum(["The specified resource does not exist."]).optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error409Schema: z.ZodType<Error409> = z.object({
  name: z.enum(["RESOURCE_CONFLICT"]).optional(),
  message: z.enum(["The server has detected a conflict while processing this request."]).optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error415Schema: z.ZodType<Error415> = z.object({
  name: z.enum(["UNSUPPORTED_MEDIA_TYPE"]).optional(),
  message: z.enum(["The server does not support the request payload's media type."]).optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const Error422Schema: z.ZodType<Error422> = z.object({
  name: z.enum(["UNPROCESSABLE_ENTITY"]).optional(),
  message: z.enum([
    "The requested action could not be performed, semantically incorrect, or failed business validation.",
  ]).optional(),
  details: z.array(ErrorDetailsSchema).optional(),
  debug_id: z.string().optional(),
  links: z.array(ErrorLinkDescriptionSchema).min(0).max(10000).optional(),
});

export const LinkDescriptionSchema: z.ZodType<LinkDescription> = z.object({
  href: z.string(),
  rel: z.string(),
  method: z.enum(["GET", "POST", "PUT", "DELETE", "HEAD", "CONNECT", "OPTIONS", "PATCH"]).optional(),
});

export const BatchTrackerCollectionDefinitionsLinkDescriptionListSchema: z.ZodType<
  BatchTrackerCollectionDefinitionsLinkDescriptionList
> = z.array(LinkDescriptionSchema).min(1).max(1);

export const LinkDescription2Schema: z.ZodType<LinkDescription2> = z.object({
  href: z.string(),
  rel: z.string(),
  method: z.enum(["GET", "POST", "PUT", "DELETE", "HEAD", "CONNECT", "OPTIONS", "PATCH"]).optional(),
});

export const DefinitionsLinkDescriptionListSchema: z.ZodType<DefinitionsLinkDescriptionList> = z.array(
  LinkDescription2Schema,
).min(1).max(4);

export const ErrorDefinitionsLinkDescriptionListSchema: z.ZodType<ErrorDefinitionsLinkDescriptionList> = z.array(
  LinkDescription2Schema,
);

export const ErrorDetails2Schema: z.ZodType<ErrorDetails2> = z.object({
  field: z.string().optional(),
  value: z.string().optional(),
  location: z.string().default("body").optional(),
  issue: z.string(),
  description: z.string().optional(),
  links: DefinitionsLinkDescriptionListSchema.optional(),
});

export const ErrorDetailsListSchema: z.ZodType<ErrorDetailsList> = z.array(ErrorDetails2Schema);

export const ErrorSchema: z.ZodType<Error> = z.object({
  name: z.string(),
  message: z.string(),
  debug_id: z.string(),
  information_link: z.string().optional(),
  details: ErrorDetailsListSchema.optional(),
  links: ErrorDefinitionsLinkDescriptionListSchema.optional(),
});

export const ErrorListSchema: z.ZodType<ErrorList> = z.array(ErrorSchema).min(1).max(100);

export const LinkDescriptionListSchema: z.ZodType<LinkDescriptionList> = z.array(LinkDescriptionSchema).min(1).max(2);

export const TrackerIdentifierSchema: z.ZodType<TrackerIdentifier> = z.object({
  transaction_id: z.string().regex(new RegExp("^[a-zA-Z0-9]*$")).min(1).max(50),
  tracking_number: z.string().regex(new RegExp("^.*$")).min(1).max(64).optional(),
  links: LinkDescriptionListSchema.optional(),
});

export const DefinitionsTrackerIdentifierListSchema: z.ZodType<DefinitionsTrackerIdentifierList> = z.array(
  TrackerIdentifierSchema,
).min(1).max(100);

export const TrackerIdentifierCollectionDefinitionsLinkDescriptionListSchema: z.ZodType<
  TrackerIdentifierCollectionDefinitionsLinkDescriptionList
> = z.array(LinkDescriptionSchema).min(1).max(1);

export const TrackerIdentifierCollectionSchema: z.ZodType<TrackerIdentifierCollection> = z.object({
  tracker_identifiers: DefinitionsTrackerIdentifierListSchema.optional(),
  links: TrackerIdentifierCollectionDefinitionsLinkDescriptionListSchema.optional(),
});

export const TrackerIdentifierListSchema: z.ZodType<TrackerIdentifierList> = z.array(TrackerIdentifierSchema).min(1)
  .max(100);

export const BatchTrackerCollectionSchema: z.ZodType<BatchTrackerCollection> = z.object({
  tracker_identifiers: TrackerIdentifierListSchema.optional(),
  errors: ErrorListSchema.optional(),
  links: BatchTrackerCollectionDefinitionsLinkDescriptionListSchema.optional(),
});

export const TrackingNumberTypeSchema: z.ZodType<TrackingNumberType> = z.enum([
  "CARRIER_PROVIDED",
  "E2E_PARTNER_PROVIDED",
]);

export const TrackingStatusSchema: z.ZodType<TrackingStatus> = z.enum([
  "CANCELLED",
  "DELIVERED",
  "LOCAL_PICKUP",
  "ON_HOLD",
  "SHIPPED",
  "SHIPMENT_CREATED",
  "DROPPED_OFF",
  "IN_TRANSIT",
  "RETURNED",
  "LABEL_PRINTED",
  "ERROR",
  "UNCONFIRMED",
  "PICKUP_FAILED",
  "DELIVERY_DELAYED",
  "DELIVERY_SCHEDULED",
  "DELIVERY_FAILED",
  "INRETURN",
  "IN_PROCESS",
  "NEW",
  "VOID",
  "PROCESSED",
  "NOT_SHIPPED",
  "COMPLETED",
]);

export const TrackerSchema: z.ZodType<Tracker> = z.object({
  transaction_id: z.string().regex(new RegExp("^[a-zA-Z0-9]*$")).min(1).max(50),
  tracking_number: z.string().regex(new RegExp("^.*$")).min(1).max(64).optional(),
  tracking_number_type: TrackingNumberTypeSchema.optional(),
  status: TrackingStatusSchema,
  shipment_date: DateNoTimeSchema.optional(),
  carrier: CarrierSchema.optional(),
  carrier_name_other: z.string().regex(new RegExp("^.*$")).min(1).max(64).optional(),
  postage_payment_id: z.string().regex(new RegExp("^.*$")).min(1).max(64).optional(),
  notify_buyer: z.boolean().optional(),
  quantity: z.number().int().min(1).max(22).optional(),
  tracking_number_validated: z.boolean().optional(),
  last_updated_time: DateTimeSchema.optional(),
  shipment_direction: z.enum(["FORWARD", "RETURN"]).optional(),
  shipment_uploader: z.enum(["MERCHANT", "CONSUMER", "PARTNER"]).optional(),
  account_id: z.string().regex(new RegExp("^[2-9A-HJ-NP-Z]{13}$")).min(13).max(13).optional(),
  tracking_url: z.string().regex(new RegExp("^.*$")).min(1).max(250).optional(),
  links: LinkDescriptionListSchema.optional(),
});

export const TrackerListSchema: z.ZodType<TrackerList> = z.array(TrackerSchema).min(1).max(20);

export const TrackerCollectionSchema: z.ZodType<TrackerCollection> = z.object({
  trackers: TrackerListSchema.optional(),
  links: LinkDescriptionListSchema.optional(),
});

/**
 * API Client class with path-based access to all operations.
 * All methods are inline within the class.
 */
export class ApiClient {
  constructor(private readonly config: OpenAPIClientConfig) {}

  readonly "/v1/shipping/trackers" = {
    /**
     * List tracking information
     *
     * Lists tracking information that meet search criteria. The tracking ID is required but the tracking number is optional.
     */
    get: (request: {
      query: {
        /** Filters the tracking information that appears in the response by a PayPal transaction ID. */
        transaction_id: string;
        /** Filters the tracking information that appears in the response by a tracking number. */
        tracking_number?: string;
        /** Encrypted PayPal Account ID of the buyer or seller. */
        account_id?: string;
      };
    }): Promise<
      OpenAPIResponses<{
        /** A successful request returns the HTTP 200 OK status code and a JSON response body that lists tracking information that meets search criteria. */
        200: {
          body: Tracker;
        };
        /** The error response. */
        "default": {
          body: Error;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/v1/shipping/trackers",
          method: "get",
          requestSchema: z.object({
            query: z.object({
              transaction_id: z.string(),
              tracking_number: z.string().optional(),
              account_id: z.string().regex(new RegExp("^[2-9A-HJ-NP-Z]{13}$")).min(13).max(13).optional(),
            }),
          }),
          responseSchema: {
            200: z.object({ body: TrackerSchema }),
            "default": z.object({ body: ErrorSchema }),
          },
        },
        request,
      ) as any,
    /**
     * Add tracking information for PayPal transaction
     *
     * Adds tracking information for a PayPal transaction.
     */
    post: (request?: {}): Promise<
      OpenAPIResponses<{
        /** A successful request returns the HTTP 200 OK status code and a JSON response body that shows tracking information. */
        200: {
          body: TrackerIdentifierCollection;
        };
        /** The error response. */
        "default": {
          body: Error;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/v1/shipping/trackers",
          method: "post",
          requestSchema: z.object({}),
          responseSchema: {
            200: z.object({ body: TrackerIdentifierCollectionSchema }),
            "default": z.object({ body: ErrorSchema }),
          },
        },
        request,
      ) as any,
  };

  readonly "/v1/shipping/trackers-batch" = {
    /**
     * Add tracking information for multiple PayPal transactions
     *
     * <blockquote><strong>Deprecation notice:</strong> Adding tracking details for an order through <code>/v1/shipping/trackers-batch</code> is deprecated as its a legacy way of integration. Use the new <a href="/docs/tracking/orders-api/integrate/">Orders v2 API</a> to share tracking details with PayPal.</blockquote>Adds tracking information, with or without tracking numbers, for multiple PayPal transactions. Accepts up to 20 tracking IDs. For more information, see <a href="/docs/tracking/tracking-api/integrate/#link-addtrackinginformationwithtrackingnumbers">Add tracking information with tracking numbers</a> and <a href="/docs/tracking/tracking-api/integrate/#link-addtrackinginformationwithouttrackingnumbers">Add tracking information without tracking numbers</a>.
     */
    post: (request?: {}): Promise<
      OpenAPIResponses<{
        /** A successful request returns the HTTP 200 OK status code and a JSON response body that shows tracking information. */
        200: {
          body: BatchTrackerCollection;
        };
        /** The request is not well-formed, syntactically incorrect, or violates schema. */
        400: {
          body: unknown;
        };
        /** The authorization failed due to insufficient permissions. */
        403: {
          body: unknown;
        };
        /** The specified resource does not exist. */
        404: {
          body: unknown;
        };
        /** An internal server error has occurred. */
        500: {
          body: unknown;
        };
        /** The error response. */
        "default": {
          body: Error;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/v1/shipping/trackers-batch",
          method: "post",
          requestSchema: z.object({}),
          responseSchema: {
            200: z.object({ body: BatchTrackerCollectionSchema }),
            400: z.object({ body: z.unknown() }),
            403: z.object({ body: z.unknown() }),
            404: z.object({ body: z.unknown() }),
            500: z.object({ body: z.unknown() }),
            "default": z.object({ body: ErrorSchema }),
          },
        },
        request,
      ) as any,
  };

  readonly "/v1/shipping/trackers/{id}" = {
    /**
     * Show tracking information
     *
     * Shows tracking information, by tracker ID, for a PayPal transaction.
     */
    get: (request: {
      path: {
        /** The ID of the tracker in the <code><var>transaction_id</var>-<var>tracking_number</var></code> format. */
        id: string;
      };
      query?: {
        /** Encrypted PayPal Account ID of the buyer or seller. */
        account_id?: string;
      };
    }): Promise<
      OpenAPIResponses<{
        /** A successful request returns the HTTP `200 OK` status code and a JSON response body that shows tracking information. */
        200: {
          body: Tracker;
        };
        /** The error response. */
        "default": {
          body: Error;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/v1/shipping/trackers/{id}",
          method: "get",
          requestSchema: z.object({
            path: z.object({
              id: z.string().regex(new RegExp("^[a-zA-Z0-9-_]*$")).min(1).max(100),
            }),
            query: z.object({
              account_id: z.string().regex(new RegExp("^[2-9A-HJ-NP-Z]{13}$")).min(13).max(13).optional(),
            }).optional(),
          }),
          responseSchema: {
            200: z.object({ body: TrackerSchema }),
            "default": z.object({ body: ErrorSchema }),
          },
        },
        request,
      ) as any,
    /**
     * Update or cancel tracking information for PayPal transaction
     *
     * Updates or cancels the tracking information for a PayPal transaction, by ID. To cancel tracking information, call this method and set the status to CANCELLED. For more information, see <a href="/docs/tracking/tracking-api/integrate/#link-updateorcanceltrackinginformation">Update or cancel tracking information</a>.
     */
    put: (request: {
      path: {
        /** The ID of the tracker in the <code><var>transaction_id</var>-<var>tracking_number</var></code> format. */
        id: string;
      };
      body: Tracker;
    }): Promise<
      OpenAPIResponses<{
        /** A successful request returns the HTTP 204 OK status code with no JSON response body. */
        204: {
          body: unknown;
        };
        /** The error response. */
        "default": {
          body: Error;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/v1/shipping/trackers/{id}",
          method: "put",
          requestSchema: z.object({
            path: z.object({
              id: z.string().regex(new RegExp("^[a-zA-Z0-9-_]*$")).min(1).max(100),
            }),
            body: TrackerSchema,
          }),
          responseSchema: {
            204: z.object({ body: z.unknown() }),
            "default": z.object({ body: ErrorSchema }),
          },
        },
        request,
      ) as any,
  };
}
