/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Schema {
  /**
   * The number of characters for an indent.
   */
  indentWidth?: number;
  /**
   * Whether to use tabs or spaces.
   */
  indentStyle?: ("tab" | "space") & string;
  /**
   * How many characters can be written on a single line.
   */
  lineLength?: number;
  /**
   * The type of quote used when representing string literals.
   */
  quoteStyle?: ("double" | "single") & string;
  /**
   * The kind of line ending.
   */
  lineEnding?: ("lf" | "cr-lf") & string;
  /**
   * Ignore the magic trailing comma.
   */
  skipMagicTrailingComma?: boolean;
  /**
   * Whether to enable preview mode. When preview mode is enabled, Ruff will use unstable rules, fixes, and formatting.
   */
  preview?: boolean;
}
