// deno-lint-ignore-file no-explicit-any
// This file was auto-generated by @brad-jones/open-api-client

import {
  type OpenAPIClientConfig,
  openAPIFetch,
  type OpenAPIResponses,
} from "jsr:@brad-jones/deno-net-open-api-client@0.2.1";

/**
 * API Client class with path-based access to all operations.
 * All methods are inline within the class.
 */
export class ApiClient {
  constructor(private readonly config: OpenAPIClientConfig) {}

  readonly "/strongly-typed/hello/{name}" = {
    post: (request: {
      path: {
        name: string;
      };
      body: {
        age: number;
      };
    }): Promise<
      OpenAPIResponses<{
        200: {
          body: {
            message: string;
          };
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/strongly-typed/hello/{name}",
          method: "post",
        },
        request,
      ) as any,
  };
}
