/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NewLineKind = "auto" | "crlf" | "lf" | "system";
export type NewLineKind1 = string;

export interface Schema {
  /**
   * Whether the configuration is not allowed to be overridden or extended.
   */
  locked?: boolean;
  /**
   * The width of a line the printer will try to stay under. Note that the printer may exceed this width in certain cases.
   */
  lineWidth?: number;
  /**
   * The kind of newline to use.
   */
  newLineKind?: NewLineKind & NewLineKind1;
}
