// deno-lint-ignore-file no-explicit-any
// This file was auto-generated by @brad-jones/open-api-client

import {
  type OpenAPIClientConfig,
  openAPIFetch,
  type OpenAPIResponses,
} from "jsr:@brad-jones/deno-net-open-api-client@0.2.0";
import { z } from "npm:zod@^4.1.12";

export type Address = {
  line1: string;
  line2?: string;
  city: string;
  state: string;
  postal_code: string;
  country: string;
};

export type CartItem = {
  /** @format uuid */
  product_id: string;
  quantity: number;
};

export type Order = {
  /** @format uuid */
  id: string;
  items: CartItem[];
  total_amount: number;
  status: "pending" | "confirmed" | "shipped" | "delivered";
  /** @format date-time */
  created_at: string;
};

export type Product = {
  /** @format uuid */
  id: string;
  name: string;
  description?: string;
  /** @format float */
  price: number;
  category: string;
  /** @format uri */
  image_url?: string;
  stock: number;
  /** @format date-time */
  created_at?: string;
  /** @format date-time */
  updated_at?: string;
};

export const AddressSchema: z.ZodType<Address> = z.object({
  line1: z.string(),
  line2: z.string().optional(),
  city: z.string(),
  state: z.string(),
  postal_code: z.string(),
  country: z.string(),
});

export const CartItemSchema: z.ZodType<CartItem> = z.object({
  product_id: z.string(),
  quantity: z.number().int().min(1),
});

export const OrderSchema: z.ZodType<Order> = z.object({
  id: z.string(),
  items: z.array(CartItemSchema),
  total_amount: z.number(),
  status: z.enum(["pending", "confirmed", "shipped", "delivered"]),
  created_at: z.string(),
});

export const ProductSchema: z.ZodType<Product> = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string().optional(),
  price: z.number(),
  category: z.string(),
  image_url: z.string().optional(),
  stock: z.number().int(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

/**
 * API Client class with path-based access to all operations.
 * All methods are inline within the class.
 */
export class ApiClient {
  constructor(private readonly config: OpenAPIClientConfig) {}

  readonly "/addresses" = {
    /**
     * Get your saved addresses
     */
    get: (): Promise<
      OpenAPIResponses<{
        /** List of saved addresses */
        200: {
          body: Address[];
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/addresses",
          method: "get",
          responseSchema: {
            200: z.object({ body: z.array(AddressSchema) }),
          },
        },
      ) as any,
    /**
     * Add a new address
     */
    post: (request: { body: Address }): Promise<
      OpenAPIResponses<{
        /** Address added */
        201: {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/addresses",
          method: "post",
          requestSchema: z.object({
            body: AddressSchema,
          }),
          responseSchema: {
            201: z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };

  readonly "/auth/login" = {
    /**
     * Login and get access token
     */
    post: (request: {
      body: {
        email: string;
        password: string;
      };
    }): Promise<
      OpenAPIResponses<{
        /** Authenticated successfully */
        200: {
          body: unknown;
        };
        /** Unauthorized */
        401: {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/auth/login",
          method: "post",
          requestSchema: z.object({
            body: z.object({
              email: z.string(),
              password: z.string(),
            }),
          }),
          responseSchema: {
            200: z.object({ body: z.unknown() }),
            401: z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };

  readonly "/auth/register" = {
    /**
     * Create a new user account
     */
    post: (request: {
      body: {
        /** @format email */
        email: string;
        /** @format password */
        password: string;
        name?: string;
      };
    }): Promise<
      OpenAPIResponses<{
        /** User created */
        201: {
          body: unknown;
        };
        /** Invalid input */
        400: {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/auth/register",
          method: "post",
          requestSchema: z.object({
            body: z.object({
              email: z.string(),
              password: z.string(),
              name: z.string().optional(),
            }),
          }),
          responseSchema: {
            201: z.object({ body: z.unknown() }),
            400: z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };

  readonly "/cart" = {
    /**
     * Get current user's cart
     */
    get: (): Promise<
      OpenAPIResponses<{
        /** Your cart items */
        200: {
          body: CartItem[];
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/cart",
          method: "get",
          responseSchema: {
            200: z.object({ body: z.array(CartItemSchema) }),
          },
        },
      ) as any,
  };

  readonly "/cart/items" = {
    /**
     * Add item to cart
     */
    post: (request: { body: CartItem }): Promise<
      OpenAPIResponses<{
        /** Item added to cart */
        200: {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/cart/items",
          method: "post",
          requestSchema: z.object({
            body: CartItemSchema,
          }),
          responseSchema: {
            200: z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };

  readonly "/checkout" = {
    /**
     * Checkout and place order
     */
    post: (request: {
      body: {
        address_id: string;
        payment_method_id: string;
      };
    }): Promise<
      OpenAPIResponses<{
        /** Order created */
        201: {
          body: Order;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/checkout",
          method: "post",
          requestSchema: z.object({
            body: z.object({
              address_id: z.string(),
              payment_method_id: z.string(),
            }),
          }),
          responseSchema: {
            201: z.object({ body: OrderSchema }),
          },
        },
        request,
      ) as any,
  };

  readonly "/orders" = {
    /**
     * List your past orders
     */
    get: (): Promise<
      OpenAPIResponses<{
        /** Order history */
        200: {
          body: Order[];
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/orders",
          method: "get",
          responseSchema: {
            200: z.object({ body: z.array(OrderSchema) }),
          },
        },
      ) as any,
  };

  readonly "/orders/{orderId}" = {
    /**
     * Get order details
     */
    get: (request: {
      path: {
        orderId: string;
      };
    }): Promise<
      OpenAPIResponses<{
        /** Order detail */
        200: {
          body: Order;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/orders/{orderId}",
          method: "get",
          requestSchema: z.object({
            path: z.object({
              orderId: z.string(),
            }),
          }),
          responseSchema: {
            200: z.object({ body: OrderSchema }),
          },
        },
        request,
      ) as any,
  };

  readonly "/products" = {
    /**
     * List all products with filters
     */
    get: (request?: {
      query?: {
        category?: string;
        search?: string;
        min_price?: number;
        max_price?: number;
      };
    }): Promise<
      OpenAPIResponses<{
        /** List of products */
        200: {
          body: Product[];
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/products",
          method: "get",
          requestSchema: z.object({
            query: z.object({
              category: z.string().optional(),
              search: z.string().optional(),
              min_price: z.number().optional(),
              max_price: z.number().optional(),
            }).optional(),
          }),
          responseSchema: {
            200: z.object({ body: z.array(ProductSchema) }),
          },
        },
        request,
      ) as any,
  };

  readonly "/products/{id}" = {
    /**
     * Get product details by ID
     */
    get: (request: {
      path: {
        id: string;
      };
    }): Promise<
      OpenAPIResponses<{
        /** Product details */
        200: {
          body: Product;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/products/{id}",
          method: "get",
          requestSchema: z.object({
            path: z.object({
              id: z.string(),
            }),
          }),
          responseSchema: {
            200: z.object({ body: ProductSchema }),
          },
        },
        request,
      ) as any,
  };
}
