// deno-lint-ignore-file no-explicit-any
// This file was auto-generated by @brad-jones/open-api-client

import {
  createCustomClient,
  type OpenAPIClientConfig,
  openAPIFetch,
  type OpenAPIResponsePromise,
  type OpenAPIResponses,
} from "jsr:@brad-jones/deno-net-open-api-client@0.3.1";
import { z } from "npm:zod@^4.1.12";

/**
 * subscribes a client to receive out-of-band data
 */
export const postStreams = (config: OpenAPIClientConfig, request: {
  query: {
    /**
     * the location where data will be sent.  Must be network accessible
     * by the source server
     */
    callbackUrl: string;
  };
}): OpenAPIResponsePromise<
  OpenAPIResponses<{
    /** subscription successfully created */
    201: {
      /** subscription information */
      body: {
        /** this unique identifier allows management of the subscription */
        subscriptionId: string;
      };
    };
  }>
> =>
  openAPIFetch(
    config,
    {
      path: "/streams",
      method: "post",
      requestSchema: z.object({
        query: z.object({
          callbackUrl: z.string(),
        }),
      }),
      responseSchema: {
        201: z.object({
          body: z.object({
            subscriptionId: z.string(),
          }),
        }),
      },
    },
    request,
  ) as any;

export { createCustomClient } from "jsr:@brad-jones/deno-net-open-api-client@0.3.1";

/**
 * Create a client with all available operations.
 * This is convenient but will include all operations in your bundle.
 * For better tree-shaking, use createCustomClient() to select specific operations.
 */
export function createClient(config: OpenAPIClientConfig) {
  return createCustomClient(config, { postStreams });
}
