// deno-lint-ignore-file no-explicit-any
// This file was auto-generated by @brad-jones/open-api-client

import {
  createCustomClient,
  type OpenAPIClientConfig,
  openAPIFetch,
  type OpenAPIResponses,
} from "jsr:@brad-jones/deno-net-open-api-client@0.2.2";
import { z } from "npm:zod@^4.1.12";

/**
 * Says hello to a given name.
 */
export const getHelloName = (config: OpenAPIClientConfig, request: {
  path: {
    /** The name to say hello to. */
    name: string;
  };
  query?: {
    lastName?: string;
  };
}): Promise<
  OpenAPIResponses<{
    /** OK */
    200: {
      body: {
        message?: string;
      };
    };
    /** Bad Request */
    400: {
      body: {
        error?: string;
      };
    };
    /** Error */
    "default": {
      body: {
        fooBar?: string;
      };
    };
  }>
> =>
  openAPIFetch(
    config,
    {
      path: "/hello/{name}",
      method: "get",
      requestSchema: z.object({
        path: z.object({
          name: z.string(),
        }),
        query: z.object({
          lastName: z.string().optional(),
        }).optional(),
      }),
      responseSchema: {
        200: z.object({
          body: z.object({
            message: z.string().optional(),
          }),
        }),
        400: z.object({
          body: z.object({
            error: z.string().optional(),
          }),
        }),
        "default": z.object({
          body: z.object({
            fooBar: z.string().optional(),
          }),
        }),
      },
    },
    request,
  ) as any;

export { createCustomClient } from "jsr:@brad-jones/deno-net-open-api-client@0.2.2";

/**
 * Create a client with all available operations.
 * This is convenient but will include all operations in your bundle.
 * For better tree-shaking, use createCustomClient() to select specific operations.
 */
export function createClient(config: OpenAPIClientConfig) {
  return createCustomClient(config, { getHelloName });
}
