// deno-lint-ignore-file no-explicit-any
// This file was auto-generated by @brad-jones/open-api-client

import {
  type OpenAPIClientConfig,
  openAPIFetch,
  type OpenAPIResponsePromise,
  type OpenAPIResponses,
} from "jsr:@brad-jones/deno-net-open-api-client@0.2.5";
import { z } from "npm:zod@^4.1.12";

export type User = {
  username?: string;
  uuid?: string;
};

export type Repository = {
  slug?: string;
  owner?: User;
};

export type Pullrequest = {
  id?: number;
  title?: string;
  repository?: Repository;
  author?: User;
};

export const UserSchema: z.ZodType<User> = z.object({
  username: z.string().optional(),
  uuid: z.string().optional(),
});

export const RepositorySchema: z.ZodType<Repository> = z.object({
  slug: z.string().optional(),
  owner: UserSchema.optional(),
});

export const PullrequestSchema: z.ZodType<Pullrequest> = z.object({
  id: z.number().int().optional(),
  title: z.string().optional(),
  repository: RepositorySchema.optional(),
  author: UserSchema.optional(),
});

/**
 * API Client class with path-based access to all operations.
 * All methods are inline within the class.
 */
export class ApiClient {
  constructor(private readonly config: OpenAPIClientConfig) {}

  readonly "/2.0/repositories/{username}" = {
    get: (request: {
      path: {
        username: string;
      };
    }): OpenAPIResponsePromise<
      OpenAPIResponses<{
        /** repositories owned by the supplied user */
        200: {
          body: Repository[];
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/2.0/repositories/{username}",
          method: "get",
          requestSchema: z.object({
            path: z.object({
              username: z.string(),
            }),
          }),
          responseSchema: {
            200: z.object({ body: z.array(RepositorySchema) }),
          },
        },
        request,
      ) as any,
  };

  readonly "/2.0/repositories/{username}/{slug}" = {
    get: (request: {
      path: {
        username: string;
        slug: string;
      };
    }): OpenAPIResponsePromise<
      OpenAPIResponses<{
        /** The repository */
        200: {
          body: Repository;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/2.0/repositories/{username}/{slug}",
          method: "get",
          requestSchema: z.object({
            path: z.object({
              username: z.string(),
              slug: z.string(),
            }),
          }),
          responseSchema: {
            200: z.object({ body: RepositorySchema }),
          },
        },
        request,
      ) as any,
  };

  readonly "/2.0/repositories/{username}/{slug}/pullrequests" = {
    get: (request: {
      path: {
        username: string;
        slug: string;
      };
      query?: {
        state?: "open" | "merged" | "declined";
      };
    }): OpenAPIResponsePromise<
      OpenAPIResponses<{
        /** an array of pull request objects */
        200: {
          body: Pullrequest[];
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/2.0/repositories/{username}/{slug}/pullrequests",
          method: "get",
          requestSchema: z.object({
            path: z.object({
              username: z.string(),
              slug: z.string(),
            }),
            query: z.object({
              state: z.enum(["open", "merged", "declined"]).optional(),
            }).optional(),
          }),
          responseSchema: {
            200: z.object({ body: z.array(PullrequestSchema) }),
          },
        },
        request,
      ) as any,
  };

  readonly "/2.0/repositories/{username}/{slug}/pullrequests/{pid}" = {
    get: (request: {
      path: {
        username: string;
        slug: string;
        pid: string;
      };
    }): OpenAPIResponsePromise<
      OpenAPIResponses<{
        /** a pull request object */
        200: {
          body: Pullrequest;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/2.0/repositories/{username}/{slug}/pullrequests/{pid}",
          method: "get",
          requestSchema: z.object({
            path: z.object({
              username: z.string(),
              slug: z.string(),
              pid: z.string(),
            }),
          }),
          responseSchema: {
            200: z.object({ body: PullrequestSchema }),
          },
        },
        request,
      ) as any,
  };

  readonly "/2.0/repositories/{username}/{slug}/pullrequests/{pid}/merge" = {
    post: (request: {
      path: {
        username: string;
        slug: string;
        pid: string;
      };
    }): OpenAPIResponsePromise<
      OpenAPIResponses<{
        /** the PR was successfully merged */
        204: {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/2.0/repositories/{username}/{slug}/pullrequests/{pid}/merge",
          method: "post",
          requestSchema: z.object({
            path: z.object({
              username: z.string(),
              slug: z.string(),
              pid: z.string(),
            }),
          }),
          responseSchema: {
            204: z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };

  readonly "/2.0/users/{username}" = {
    get: (request: {
      path: {
        username: string;
      };
    }): OpenAPIResponsePromise<
      OpenAPIResponses<{
        /** The User */
        200: {
          body: User;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/2.0/users/{username}",
          method: "get",
          requestSchema: z.object({
            path: z.object({
              username: z.string(),
            }),
          }),
          responseSchema: {
            200: z.object({ body: UserSchema }),
          },
        },
        request,
      ) as any,
  };
}
