// deno-lint-ignore-file no-explicit-any
// This file was auto-generated by @brad-jones/open-api-client

import {
  createCustomClient,
  type OpenAPIClientConfig,
  openAPIFetch,
  type OpenAPIResponses,
} from "jsr:@brad-jones/deno-net-open-api-client@0.2.4";
import { z } from "npm:zod@^4.1.12";

export const getPetFindbytags = (config: OpenAPIClientConfig, request: {
  query: {
    tags: string[];
  };
}): Promise<
  OpenAPIResponses<{
    /** OK */
    200: {
      body: unknown;
    };
  }>
> =>
  openAPIFetch(
    config,
    {
      path: "/pet/findByTags",
      method: "get",
      parameters: [{ "name": "tags", "location": "query", "style": "pipeDelimited", "explode": true }],
      requestSchema: z.object({
        query: z.object({
          tags: z.array(z.string()),
        }),
      }),
      responseSchema: {
        200: z.object({ body: z.unknown() }),
      },
    },
    request,
  ) as any;

export { createCustomClient } from "jsr:@brad-jones/deno-net-open-api-client@0.2.4";

/**
 * Create a client with all available operations.
 * This is convenient but will include all operations in your bundle.
 * For better tree-shaking, use createCustomClient() to select specific operations.
 */
export function createClient(config: OpenAPIClientConfig) {
  return createCustomClient(config, { getPetFindbytags });
}
