// deno-lint-ignore-file no-explicit-any
// This file was auto-generated by @brad-jones/open-api-client

import {
  type OpenAPIClientConfig,
  openAPIFetch,
  type OpenAPIResponses,
} from "jsr:@brad-jones/deno-net-open-api-client@0.2.1";
import { z } from "npm:zod@^4.1.12";

/**
 * API Client class with path-based access to all operations.
 * All methods are inline within the class.
 */
export class ApiClient {
  constructor(private readonly config: OpenAPIClientConfig) {}

  readonly "/pet/findByTags" = {
    get: (request: {
      query: {
        tags: string[];
      };
    }): Promise<
      OpenAPIResponses<{
        /** OK */
        200: {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/pet/findByTags",
          method: "get",
          parameters: [{ "name": "tags", "location": "query", "style": "pipeDelimited", "explode": true }],
          requestSchema: z.object({
            query: z.object({
              tags: z.array(z.string()),
            }),
          }),
          responseSchema: {
            200: z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };
}
