// deno-lint-ignore-file no-explicit-any
// This file was auto-generated by @brad-jones/open-api-client

import {
  createCustomClient,
  type OpenAPIClientConfig,
  openAPIFetch,
  type OpenAPIResponsePromise,
  type OpenAPIResponses,
} from "jsr:@brad-jones/deno-net-open-api-client@0.2.5";
import { z } from "npm:zod@^4.1.12";

export type Error = {
  /** @format int32 */
  code: number;
  message: string;
};

export type Pet = {
  /** @format int64 */
  id: number;
  name: string;
  tag?: string;
};

export type Pets = Pet[];

export const ErrorSchema: z.ZodType<Error> = z.object({
  code: z.number().int(),
  message: z.string(),
});

export const PetSchema: z.ZodType<Pet> = z.object({
  id: z.number().int(),
  name: z.string(),
  tag: z.string().optional(),
});

export const PetsSchema: z.ZodType<Pets> = z.array(PetSchema).max(100);

/**
 * List all pets
 */
export const listPets = (config: OpenAPIClientConfig, request?: {
  query?: {
    /** How many items to return at one time (max 100) */
    limit?: number;
  };
}): OpenAPIResponsePromise<
  OpenAPIResponses<{
    /** A paged array of pets */
    200: {
      body: Pets;
      headers: {
        /** A link to the next page of responses */
        "x-next"?: string;
      };
    };
    /** unexpected error */
    "default": {
      body: Error;
    };
  }>
> =>
  openAPIFetch(
    config,
    {
      path: "/pets",
      method: "get",
      requestSchema: z.object({
        query: z.object({
          limit: z.number().int().max(100).optional(),
        }).optional(),
      }),
      responseSchema: {
        200: z.object({
          body: PetsSchema,
          headers: z.object({
            "x-next": z.string().optional(),
          }),
        }),
        "default": z.object({ body: ErrorSchema }),
      },
    },
    request,
  ) as any;

/**
 * Create a pet
 */
export const createPets = (
  config: OpenAPIClientConfig,
  request: { body: Pet },
): OpenAPIResponsePromise<
  OpenAPIResponses<{
    /** Null response */
    201: {
      body: unknown;
    };
    /** unexpected error */
    "default": {
      body: Error;
    };
  }>
> =>
  openAPIFetch(
    config,
    {
      path: "/pets",
      method: "post",
      requestSchema: z.object({
        body: PetSchema,
      }),
      responseSchema: {
        201: z.object({ body: z.unknown() }),
        "default": z.object({ body: ErrorSchema }),
      },
    },
    request,
  ) as any;

/**
 * Info for a specific pet
 */
export const showPetById = (config: OpenAPIClientConfig, request: {
  path: {
    /** The id of the pet to retrieve */
    petId: string;
  };
}): OpenAPIResponsePromise<
  OpenAPIResponses<{
    /** Expected response to a valid request */
    200: {
      body: Pet;
    };
    /** unexpected error */
    "default": {
      body: Error;
    };
  }>
> =>
  openAPIFetch(
    config,
    {
      path: "/pets/{petId}",
      method: "get",
      requestSchema: z.object({
        path: z.object({
          petId: z.string(),
        }),
      }),
      responseSchema: {
        200: z.object({ body: PetSchema }),
        "default": z.object({ body: ErrorSchema }),
      },
    },
    request,
  ) as any;

export { createCustomClient } from "jsr:@brad-jones/deno-net-open-api-client@0.2.5";

/**
 * Create a client with all available operations.
 * This is convenient but will include all operations in your bundle.
 * For better tree-shaking, use createCustomClient() to select specific operations.
 */
export function createClient(config: OpenAPIClientConfig) {
  return createCustomClient(config, { listPets, createPets, showPetById });
}
