// deno-lint-ignore-file no-explicit-any
// This file was auto-generated by @brad-jones/open-api-client

import {
  type OpenAPIClientConfig,
  openAPIFetch,
  type OpenAPIResponses,
} from "jsr:@brad-jones/deno-net-open-api-client@0.2.1";
import { z } from "npm:zod@^4.1.12";

export type ApiResponse = {
  /** @format int32 */
  code?: number;
  type?: string;
  message?: string;
};

export type Category = {
  /** @format int64 */
  id?: number;
  name?: string;
};

export type Order = {
  /** @format int64 */
  id?: number;
  /** @format int64 */
  petId?: number;
  /** @format int32 */
  quantity?: number;
  /** @format date-time */
  shipDate?: string;
  status?: "placed" | "approved" | "delivered";
  complete?: boolean;
};

export type Tag = {
  /** @format int64 */
  id?: number;
  name?: string;
};

export type Pet = {
  /** @format int64 */
  id?: number;
  name: string;
  category?: Category;
  photoUrls: string[];
  tags?: Tag[];
  status?: "available" | "pending" | "sold";
};

export type User = {
  /** @format int64 */
  id?: number;
  username?: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  password?: string;
  phone?: string;
  /**
   * User Status
   *
   * @format int32
   */
  userStatus?: number;
};

export const ApiResponseSchema: z.ZodType<ApiResponse> = z.object({
  code: z.number().int().optional(),
  type: z.string().optional(),
  message: z.string().optional(),
});

export const CategorySchema: z.ZodType<Category> = z.object({
  id: z.number().int().optional(),
  name: z.string().optional(),
});

export const OrderSchema: z.ZodType<Order> = z.object({
  id: z.number().int().optional(),
  petId: z.number().int().optional(),
  quantity: z.number().int().optional(),
  shipDate: z.string().optional(),
  status: z.enum(["placed", "approved", "delivered"]).optional(),
  complete: z.boolean().optional(),
});

export const TagSchema: z.ZodType<Tag> = z.object({
  id: z.number().int().optional(),
  name: z.string().optional(),
});

export const PetSchema: z.ZodType<Pet> = z.object({
  id: z.number().int().optional(),
  name: z.string(),
  category: CategorySchema.optional(),
  photoUrls: z.array(z.string()),
  tags: z.array(TagSchema).optional(),
  status: z.enum(["available", "pending", "sold"]).optional(),
});

export const UserSchema: z.ZodType<User> = z.object({
  id: z.number().int().optional(),
  username: z.string().optional(),
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  email: z.string().optional(),
  password: z.string().optional(),
  phone: z.string().optional(),
  userStatus: z.number().int().optional(),
});

/**
 * API Client class with path-based access to all operations.
 * All methods are inline within the class.
 */
export class ApiClient {
  constructor(private readonly config: OpenAPIClientConfig) {}

  readonly "/pet" = {
    /**
     * Add a new pet to the store.
     *
     * Add a new pet to the store.
     */
    post: (request: { body: Pet }): Promise<
      OpenAPIResponses<{
        /** Successful operation */
        200: {
          body: Pet;
        };
        /** Invalid input */
        400: {
          body: unknown;
        };
        /** Validation exception */
        422: {
          body: unknown;
        };
        /** Unexpected error */
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/pet",
          method: "post",
          requestSchema: z.object({
            body: PetSchema,
          }),
          responseSchema: {
            200: z.object({ body: PetSchema }),
            400: z.object({ body: z.unknown() }),
            422: z.object({ body: z.unknown() }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
    /**
     * Update an existing pet.
     *
     * Update an existing pet by Id.
     */
    put: (request: { body: Pet }): Promise<
      OpenAPIResponses<{
        /** Successful operation */
        200: {
          body: Pet;
        };
        /** Invalid ID supplied */
        400: {
          body: unknown;
        };
        /** Pet not found */
        404: {
          body: unknown;
        };
        /** Validation exception */
        422: {
          body: unknown;
        };
        /** Unexpected error */
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/pet",
          method: "put",
          requestSchema: z.object({
            body: PetSchema,
          }),
          responseSchema: {
            200: z.object({ body: PetSchema }),
            400: z.object({ body: z.unknown() }),
            404: z.object({ body: z.unknown() }),
            422: z.object({ body: z.unknown() }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };

  readonly "/pet/{petId}" = {
    /**
     * Find pet by ID.
     *
     * Returns a single pet.
     */
    get: (request: {
      path: {
        /** ID of pet to return */
        petId: number;
      };
    }): Promise<
      OpenAPIResponses<{
        /** successful operation */
        200: {
          body: Pet;
        };
        /** Invalid ID supplied */
        400: {
          body: unknown;
        };
        /** Pet not found */
        404: {
          body: unknown;
        };
        /** Unexpected error */
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/pet/{petId}",
          method: "get",
          requestSchema: z.object({
            path: z.object({
              petId: z.number().int(),
            }),
          }),
          responseSchema: {
            200: z.object({ body: PetSchema }),
            400: z.object({ body: z.unknown() }),
            404: z.object({ body: z.unknown() }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
    /**
     * Updates a pet in the store with form data.
     *
     * Updates a pet resource based on the form data.
     */
    post: (request: {
      path: {
        /** ID of pet that needs to be updated */
        petId: number;
      };
      query?: {
        /** Name of pet that needs to be updated */
        name?: string;
        /** Status of pet that needs to be updated */
        status?: string;
      };
    }): Promise<
      OpenAPIResponses<{
        /** successful operation */
        200: {
          body: Pet;
        };
        /** Invalid input */
        400: {
          body: unknown;
        };
        /** Unexpected error */
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/pet/{petId}",
          method: "post",
          requestSchema: z.object({
            path: z.object({
              petId: z.number().int(),
            }),
            query: z.object({
              name: z.string().optional(),
              status: z.string().optional(),
            }).optional(),
          }),
          responseSchema: {
            200: z.object({ body: PetSchema }),
            400: z.object({ body: z.unknown() }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
    /**
     * Deletes a pet.
     *
     * Delete a pet.
     */
    delete: (request: {
      path: {
        /** Pet id to delete */
        petId: number;
      };
      headers?: {
        api_key?: string;
      };
    }): Promise<
      OpenAPIResponses<{
        /** Pet deleted */
        200: {
          body: unknown;
        };
        /** Invalid pet value */
        400: {
          body: unknown;
        };
        /** Unexpected error */
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/pet/{petId}",
          method: "delete",
          requestSchema: z.object({
            path: z.object({
              petId: z.number().int(),
            }),
            headers: z.object({
              api_key: z.string().optional(),
            }).optional(),
          }),
          responseSchema: {
            200: z.object({ body: z.unknown() }),
            400: z.object({ body: z.unknown() }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };

  readonly "/pet/{petId}/uploadImage" = {
    /**
     * Uploads an image.
     *
     * Upload image of the pet.
     */
    post: (request: {
      path: {
        /** ID of pet to update */
        petId: number;
      };
      query?: {
        /** Additional Metadata */
        additionalMetadata?: string;
      };
      body: "WARN: application/json is the only supported content type";
    }): Promise<
      OpenAPIResponses<{
        /** successful operation */
        200: {
          body: ApiResponse;
        };
        /** No file uploaded */
        400: {
          body: unknown;
        };
        /** Pet not found */
        404: {
          body: unknown;
        };
        /** Unexpected error */
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/pet/{petId}/uploadImage",
          method: "post",
          requestSchema: z.object({
            path: z.object({
              petId: z.number().int(),
            }),
            query: z.object({
              additionalMetadata: z.string().optional(),
            }).optional(),
          }),
          responseSchema: {
            200: z.object({ body: ApiResponseSchema }),
            400: z.object({ body: z.unknown() }),
            404: z.object({ body: z.unknown() }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };

  readonly "/pet/findByStatus" = {
    /**
     * Finds Pets by status.
     *
     * Multiple status values can be provided with comma separated strings.
     */
    get: (request: {
      query: {
        /** Status values that need to be considered for filter */
        status: "available" | "pending" | "sold";
      };
    }): Promise<
      OpenAPIResponses<{
        /** successful operation */
        200: {
          body: Pet[];
        };
        /** Invalid status value */
        400: {
          body: unknown;
        };
        /** Unexpected error */
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/pet/findByStatus",
          method: "get",
          requestSchema: z.object({
            query: z.object({
              status: z.enum(["available", "pending", "sold"]),
            }),
          }),
          responseSchema: {
            200: z.object({ body: z.array(PetSchema) }),
            400: z.object({ body: z.unknown() }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };

  readonly "/pet/findByTags" = {
    /**
     * Finds Pets by tags.
     *
     * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
     */
    get: (request: {
      query: {
        /** Tags to filter by */
        tags: string[];
      };
    }): Promise<
      OpenAPIResponses<{
        /** successful operation */
        200: {
          body: Pet[];
        };
        /** Invalid tag value */
        400: {
          body: unknown;
        };
        /** Unexpected error */
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/pet/findByTags",
          method: "get",
          requestSchema: z.object({
            query: z.object({
              tags: z.array(z.string()),
            }),
          }),
          responseSchema: {
            200: z.object({ body: z.array(PetSchema) }),
            400: z.object({ body: z.unknown() }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };

  readonly "/store/inventory" = {
    /**
     * Returns pet inventories by status.
     *
     * Returns a map of status codes to quantities.
     */
    get: (): Promise<
      OpenAPIResponses<{
        /** successful operation */
        200: {
          body: Record<string, /** @format int32 */ number>;
        };
        /** Unexpected error */
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/store/inventory",
          method: "get",
          responseSchema: {
            200: z.object({ body: z.record(z.string(), z.number().int()) }),
            "default": z.object({ body: z.unknown() }),
          },
        },
      ) as any,
  };

  readonly "/store/order" = {
    /**
     * Place an order for a pet.
     *
     * Place a new order in the store.
     */
    post: (request?: { body?: Order }): Promise<
      OpenAPIResponses<{
        /** successful operation */
        200: {
          body: Order;
        };
        /** Invalid input */
        400: {
          body: unknown;
        };
        /** Validation exception */
        422: {
          body: unknown;
        };
        /** Unexpected error */
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/store/order",
          method: "post",
          requestSchema: z.object({
            body: OrderSchema,
          }),
          responseSchema: {
            200: z.object({ body: OrderSchema }),
            400: z.object({ body: z.unknown() }),
            422: z.object({ body: z.unknown() }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };

  readonly "/store/order/{orderId}" = {
    /**
     * Find purchase order by ID.
     *
     * For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
     */
    get: (request: {
      path: {
        /** ID of order that needs to be fetched */
        orderId: number;
      };
    }): Promise<
      OpenAPIResponses<{
        /** successful operation */
        200: {
          body: Order;
        };
        /** Invalid ID supplied */
        400: {
          body: unknown;
        };
        /** Order not found */
        404: {
          body: unknown;
        };
        /** Unexpected error */
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/store/order/{orderId}",
          method: "get",
          requestSchema: z.object({
            path: z.object({
              orderId: z.number().int(),
            }),
          }),
          responseSchema: {
            200: z.object({ body: OrderSchema }),
            400: z.object({ body: z.unknown() }),
            404: z.object({ body: z.unknown() }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
    /**
     * Delete purchase order by identifier.
     *
     * For valid response try integer IDs with value < 1000. Anything above 1000 or non-integers will generate API errors.
     */
    delete: (request: {
      path: {
        /** ID of the order that needs to be deleted */
        orderId: number;
      };
    }): Promise<
      OpenAPIResponses<{
        /** order deleted */
        200: {
          body: unknown;
        };
        /** Invalid ID supplied */
        400: {
          body: unknown;
        };
        /** Order not found */
        404: {
          body: unknown;
        };
        /** Unexpected error */
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/store/order/{orderId}",
          method: "delete",
          requestSchema: z.object({
            path: z.object({
              orderId: z.number().int(),
            }),
          }),
          responseSchema: {
            200: z.object({ body: z.unknown() }),
            400: z.object({ body: z.unknown() }),
            404: z.object({ body: z.unknown() }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };

  readonly "/user" = {
    /**
     * Create user.
     *
     * This can only be done by the logged in user.
     */
    post: (request?: { body?: User }): Promise<
      OpenAPIResponses<{
        /** successful operation */
        200: {
          body: User;
        };
        /** Unexpected error */
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/user",
          method: "post",
          requestSchema: z.object({
            body: UserSchema,
          }),
          responseSchema: {
            200: z.object({ body: UserSchema }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };

  readonly "/user/{username}" = {
    /**
     * Get user by user name.
     *
     * Get user detail based on username.
     */
    get: (request: {
      path: {
        /** The name that needs to be fetched. Use user1 for testing */
        username: string;
      };
    }): Promise<
      OpenAPIResponses<{
        /** successful operation */
        200: {
          body: User;
        };
        /** Invalid username supplied */
        400: {
          body: unknown;
        };
        /** User not found */
        404: {
          body: unknown;
        };
        /** Unexpected error */
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/user/{username}",
          method: "get",
          requestSchema: z.object({
            path: z.object({
              username: z.string(),
            }),
          }),
          responseSchema: {
            200: z.object({ body: UserSchema }),
            400: z.object({ body: z.unknown() }),
            404: z.object({ body: z.unknown() }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
    /**
     * Update user resource.
     *
     * This can only be done by the logged in user.
     */
    put: (request: {
      path: {
        /** name that need to be deleted */
        username: string;
      };
      body?: User;
    }): Promise<
      OpenAPIResponses<{
        /** successful operation */
        200: {
          body: unknown;
        };
        /** bad request */
        400: {
          body: unknown;
        };
        /** user not found */
        404: {
          body: unknown;
        };
        /** Unexpected error */
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/user/{username}",
          method: "put",
          requestSchema: z.object({
            path: z.object({
              username: z.string(),
            }),
            body: UserSchema,
          }),
          responseSchema: {
            200: z.object({ body: z.unknown() }),
            400: z.object({ body: z.unknown() }),
            404: z.object({ body: z.unknown() }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
    /**
     * Delete user resource.
     *
     * This can only be done by the logged in user.
     */
    delete: (request: {
      path: {
        /** The name that needs to be deleted */
        username: string;
      };
    }): Promise<
      OpenAPIResponses<{
        /** User deleted */
        200: {
          body: unknown;
        };
        /** Invalid username supplied */
        400: {
          body: unknown;
        };
        /** User not found */
        404: {
          body: unknown;
        };
        /** Unexpected error */
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/user/{username}",
          method: "delete",
          requestSchema: z.object({
            path: z.object({
              username: z.string(),
            }),
          }),
          responseSchema: {
            200: z.object({ body: z.unknown() }),
            400: z.object({ body: z.unknown() }),
            404: z.object({ body: z.unknown() }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };

  readonly "/user/createWithList" = {
    /**
     * Creates list of users with given input array.
     *
     * Creates list of users with given input array.
     */
    post: (request: { body: User[] }): Promise<
      OpenAPIResponses<{
        /** Successful operation */
        200: {
          body: User;
        };
        /** Unexpected error */
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/user/createWithList",
          method: "post",
          requestSchema: z.object({
            body: z.array(UserSchema),
          }),
          responseSchema: {
            200: z.object({ body: UserSchema }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };

  readonly "/user/login" = {
    /**
     * Logs user into the system.
     *
     * Log into the system.
     */
    get: (request?: {
      query?: {
        /** The user name for login */
        username?: string;
        /** The password for login in clear text */
        password?: string;
      };
    }): Promise<
      OpenAPIResponses<{
        /** successful operation */
        200: {
          body: string;
          headers: {
            /** calls per hour allowed by the user */
            "X-Rate-Limit"?: number;
            /** date in UTC when token expires */
            "X-Expires-After"?: string;
          };
        };
        /** Invalid username/password supplied */
        400: {
          body: unknown;
        };
        /** Unexpected error */
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/user/login",
          method: "get",
          requestSchema: z.object({
            query: z.object({
              username: z.string().optional(),
              password: z.string().optional(),
            }).optional(),
          }),
          responseSchema: {
            200: z.object({
              body: z.string(),
              headers: z.object({
                "X-Rate-Limit": z.number().int().optional(),
                "X-Expires-After": z.string().optional(),
              }),
            }),
            400: z.object({ body: z.unknown() }),
            "default": z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };

  readonly "/user/logout" = {
    /**
     * Logs out current logged in user session.
     *
     * Log user out of the system.
     */
    get: (): Promise<
      OpenAPIResponses<{
        /** successful operation */
        200: {
          body: unknown;
        };
        /** Unexpected error */
        "default": {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/user/logout",
          method: "get",
          responseSchema: {
            200: z.object({ body: z.unknown() }),
            "default": z.object({ body: z.unknown() }),
          },
        },
      ) as any,
  };
}
