// deno-lint-ignore-file no-explicit-any
// This file was auto-generated by @brad-jones/open-api-client

import {
  type OpenAPIClientConfig,
  openAPIFetch,
  type OpenAPIResponses,
} from "jsr:@brad-jones/deno-net-open-api-client@0.2.4";
import { z } from "npm:zod@^4.1.12";

export type Error = {
  /** @format int32 */
  code: number;
  message: string;
};

export type Pet = {
  /** @format int64 */
  id: number;
  name: string;
  tag?: string;
};

export type Pets = Pet[];

export const ErrorSchema: z.ZodType<Error> = z.object({
  code: z.number().int(),
  message: z.string(),
});

export const PetSchema: z.ZodType<Pet> = z.object({
  id: z.number().int(),
  name: z.string(),
  tag: z.string().optional(),
});

export const PetsSchema: z.ZodType<Pets> = z.array(PetSchema).max(100);

/**
 * API Client class with path-based access to all operations.
 * All methods are inline within the class.
 */
export class ApiClient {
  constructor(private readonly config: OpenAPIClientConfig) {}

  readonly "/pets" = {
    /**
     * List all pets
     */
    get: (request?: {
      query?: {
        /** How many items to return at one time (max 100) */
        limit?: number;
      };
    }): Promise<
      OpenAPIResponses<{
        /** A paged array of pets */
        200: {
          body: Pets;
          headers: {
            /** A link to the next page of responses */
            "x-next"?: string;
          };
        };
        /** unexpected error */
        "default": {
          body: Error;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/pets",
          method: "get",
          requestSchema: z.object({
            query: z.object({
              limit: z.number().int().max(100).optional(),
            }).optional(),
          }),
          responseSchema: {
            200: z.object({
              body: PetsSchema,
              headers: z.object({
                "x-next": z.string().optional(),
              }),
            }),
            "default": z.object({ body: ErrorSchema }),
          },
        },
        request,
      ) as any,
    /**
     * Create a pet
     */
    post: (request: { body: Pet }): Promise<
      OpenAPIResponses<{
        /** Null response */
        201: {
          body: unknown;
        };
        /** unexpected error */
        "default": {
          body: Error;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/pets",
          method: "post",
          requestSchema: z.object({
            body: PetSchema,
          }),
          responseSchema: {
            201: z.object({ body: z.unknown() }),
            "default": z.object({ body: ErrorSchema }),
          },
        },
        request,
      ) as any,
  };

  readonly "/pets/{petId}" = {
    /**
     * Info for a specific pet
     */
    get: (request: {
      path: {
        /** The id of the pet to retrieve */
        petId: string;
      };
    }): Promise<
      OpenAPIResponses<{
        /** Expected response to a valid request */
        200: {
          body: Pet;
        };
        /** unexpected error */
        "default": {
          body: Error;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/pets/{petId}",
          method: "get",
          requestSchema: z.object({
            path: z.object({
              petId: z.string(),
            }),
          }),
          responseSchema: {
            200: z.object({ body: PetSchema }),
            "default": z.object({ body: ErrorSchema }),
          },
        },
        request,
      ) as any,
  };
}
