// deno-lint-ignore-file no-explicit-any
// This file was auto-generated by @brad-jones/open-api-client

import {
  createCustomClient,
  type OpenAPIClientConfig,
  openAPIFetch,
  type OpenAPIResponses,
} from "jsr:@brad-jones/deno-net-open-api-client@0.2.2";
import { z } from "npm:zod@^4.1.12";

export const getPing = (config: OpenAPIClientConfig): Promise<
  OpenAPIResponses<{
    /** OK */
    200: {
      body: {
        pong?: string;
      };
    };
  }>
> =>
  openAPIFetch(
    config,
    {
      path: "/ping",
      method: "get",
      responseSchema: {
        200: z.object({
          body: z.object({
            pong: z.string().optional(),
          }),
        }),
      },
    },
  ) as any;

export { createCustomClient } from "jsr:@brad-jones/deno-net-open-api-client@0.2.2";

/**
 * Create a client with all available operations.
 * This is convenient but will include all operations in your bundle.
 * For better tree-shaking, use createCustomClient() to select specific operations.
 */
export function createClient(config: OpenAPIClientConfig) {
  return createCustomClient(config, { getPing });
}
