// deno-lint-ignore-file no-explicit-any
// This file was auto-generated by @brad-jones/open-api-client

import {
  createCustomClient,
  type OpenAPIClientConfig,
  openAPIFetch,
  type OpenAPIResponses,
} from "jsr:@brad-jones/deno-net-open-api-client@0.2.0";
import { z } from "npm:zod@^4.1.12";

/**
 * Get paginated data with pagination headers
 */
export const getPaginatedData = (config: OpenAPIClientConfig, request?: {
  query?: {
    page?: number;
    limit?: number;
  };
}): Promise<
  OpenAPIResponses<{
    /** Successful response with pagination metadata in headers */
    200: {
      body: {
        items?: {
          id?: string;
          name?: string;
        }[];
      };
      headers: {
        /** Total number of items */
        "X-Total-Count": number;
        /** Current page number */
        "X-Page-Number"?: number;
        /** Number of items per page */
        "X-Page-Size"?: number;
        /** Total number of pages */
        "X-Total-Pages"?: number;
      };
    };
  }>
> =>
  openAPIFetch(
    config,
    {
      path: "/paginated-data",
      method: "get",
      requestSchema: z.object({
        query: z.object({
          page: z.number().int().default(1).optional(),
          limit: z.number().int().default(20).optional(),
        }).optional(),
      }),
      responseSchema: {
        200: z.object({
          body: z.object({
            items: z.array(z.object({
              id: z.string().optional(),
              name: z.string().optional(),
            })).optional(),
          }),
          headers: z.object({
            "X-Total-Count": z.number().int(),
            "X-Page-Number": z.number().int().optional(),
            "X-Page-Size": z.number().int().optional(),
            "X-Total-Pages": z.number().int().optional(),
          }),
        }),
      },
    },
    request,
  ) as any;

/**
 * Get data with rate limit information in headers
 */
export const getRateLimitedData = (config: OpenAPIClientConfig): Promise<
  OpenAPIResponses<{
    /** Success with rate limit headers */
    200: {
      body: {
        data?: string;
      };
      headers: {
        /** Request limit per hour */
        "X-RateLimit-Limit"?: number;
        /** Remaining requests for this hour */
        "X-RateLimit-Remaining"?: number;
        /** Unix timestamp when the rate limit resets */
        "X-RateLimit-Reset"?: number;
      };
    };
    /** Rate limit exceeded */
    429: {
      body: {
        error?: string;
        message?: string;
      };
      headers: {
        /** Number of seconds to wait before retrying */
        "Retry-After": number;
        "X-RateLimit-Limit"?: number;
        "X-RateLimit-Reset"?: number;
      };
    };
  }>
> =>
  openAPIFetch(
    config,
    {
      path: "/rate-limited",
      method: "get",
      responseSchema: {
        200: z.object({
          body: z.object({
            data: z.string().optional(),
          }),
          headers: z.object({
            "X-RateLimit-Limit": z.number().int().optional(),
            "X-RateLimit-Remaining": z.number().int().optional(),
            "X-RateLimit-Reset": z.number().int().optional(),
          }),
        }),
        429: z.object({
          body: z.object({
            error: z.string().optional(),
            message: z.string().optional(),
          }),
          headers: z.object({
            "Retry-After": z.number().int(),
            "X-RateLimit-Limit": z.number().int().optional(),
            "X-RateLimit-Reset": z.number().int().optional(),
          }),
        }),
      },
    },
  ) as any;

/**
 * Get resource with ETag for caching
 */
export const getWithEtag = (config: OpenAPIClientConfig, request?: {
  headers?: {
    /** ETag from previous response */
    "If-None-Match"?: string;
  };
}): Promise<
  OpenAPIResponses<{
    /** Resource content */
    200: {
      body: {
        id?: string;
        content?: string;
      };
      headers: {
        /** Entity tag for cache validation */
        ETag: string;
        /** Cache directives */
        "Cache-Control"?: string;
        /** Last modification date */
        "Last-Modified"?: string;
      };
    };
    /** Not Modified - use cached version */
    304: {
      body: unknown;
      headers: {
        /** Entity tag matching the request */
        ETag: string;
      };
    };
  }>
> =>
  openAPIFetch(
    config,
    {
      path: "/with-etag",
      method: "get",
      requestSchema: z.object({
        headers: z.object({
          "If-None-Match": z.string().optional(),
        }).optional(),
      }),
      responseSchema: {
        200: z.object({
          body: z.object({
            id: z.string().optional(),
            content: z.string().optional(),
          }),
          headers: z.object({
            ETag: z.string(),
            "Cache-Control": z.string().optional(),
            "Last-Modified": z.string().optional(),
          }),
        }),
        304: z.object({
          body: z.unknown(),
          headers: z.object({
            ETag: z.string(),
          }),
        }),
      },
    },
    request,
  ) as any;

/**
 * Example with headers inferred from examples
 */
export const getInferredHeaders = (config: OpenAPIClientConfig): Promise<
  OpenAPIResponses<{
    /** Response with headers inferred from examples */
    200: {
      body: {
        message?: string;
      };
      headers: {
        /** Unique request identifier */
        "X-Request-Id"?: string;
        /** Response time in milliseconds */
        "X-Response-Time"?: number;
        /** API server version */
        "X-Server-Version"?: string;
        /** Whether response was served from cache */
        "X-Is-Cached"?: boolean;
      };
    };
  }>
> =>
  openAPIFetch(
    config,
    {
      path: "/inferred-headers",
      method: "get",
      responseSchema: {
        200: z.object({
          body: z.object({
            message: z.string().optional(),
          }),
          headers: z.object({
            "X-Request-Id": z.string().optional(),
            "X-Response-Time": z.number().int().optional(),
            "X-Server-Version": z.string().optional(),
            "X-Is-Cached": z.boolean().optional(),
          }),
        }),
      },
    },
  ) as any;

export { createCustomClient } from "jsr:@brad-jones/deno-net-open-api-client@0.2.0";

/**
 * Create a client with all available operations.
 * This is convenient but will include all operations in your bundle.
 * For better tree-shaking, use createCustomClient() to select specific operations.
 */
export function createClient(config: OpenAPIClientConfig) {
  return createCustomClient(config, { getPaginatedData, getRateLimitedData, getWithEtag, getInferredHeaders });
}
