// deno-lint-ignore-file no-explicit-any
// This file was auto-generated by @brad-jones/open-api-client

import {
  type OpenAPIClientConfig,
  openAPIFetch,
  type OpenAPIResponses,
} from "jsr:@brad-jones/deno-net-open-api-client@0.2.2";
import { z } from "npm:zod@^4.1.12";

export type Coordinate = number;

/** A text message describing an error */
export type ErrorMessage = string;

export type Mark = "." | "X" | "O";

export type Board = Mark[][];

export type Winner = "." | "X" | "O";

export type Status = {
  winner?: Winner;
  board?: Board;
};

export const CoordinateSchema: z.ZodType<Coordinate> = z.number().int().min(1).max(3);

export const ErrorMessageSchema: z.ZodType<ErrorMessage> = z.string().max(256);

export const MarkSchema: z.ZodType<Mark> = z.enum([".", "X", "O"]);

export const BoardSchema: z.ZodType<Board> = z.array(z.array(MarkSchema).min(3).max(3)).min(3).max(3);

export const WinnerSchema: z.ZodType<Winner> = z.enum([".", "X", "O"]);

export const StatusSchema: z.ZodType<Status> = z.object({
  winner: WinnerSchema.optional(),
  board: BoardSchema.optional(),
});

/**
 * API Client class with path-based access to all operations.
 * All methods are inline within the class.
 */
export class ApiClient {
  constructor(private readonly config: OpenAPIClientConfig) {}

  readonly "/board" = {
    /**
     * Get the whole board
     *
     * Retrieves the current state of the board and the winner.
     */
    get: (): Promise<
      OpenAPIResponses<{
        /** OK */
        200: {
          body: Status;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/board",
          method: "get",
          responseSchema: {
            200: z.object({ body: StatusSchema }),
          },
        },
      ) as any,
  };

  readonly "/board/{row}/{column}" = {
    /**
     * Get a single board square
     *
     * Retrieves the requested square.
     */
    get: (request: {
      path: {
        /** Board row (vertical coordinate) */
        row: Coordinate;
        /** Board column (horizontal coordinate) */
        column: Coordinate;
      };
    }): Promise<
      OpenAPIResponses<{
        /** OK */
        200: {
          body: Mark;
        };
        /** The provided parameters are incorrect */
        400: {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/board/{row}/{column}",
          method: "get",
          requestSchema: z.object({
            path: z.object({
              row: CoordinateSchema,
              column: CoordinateSchema,
            }),
          }),
          responseSchema: {
            200: z.object({ body: MarkSchema }),
            400: z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
    /**
     * Set a single board square
     *
     * Places a mark on the board and retrieves the whole board and the winner (if any).
     */
    put: (request: {
      path: {
        /** Board row (vertical coordinate) */
        row: Coordinate;
        /** Board column (horizontal coordinate) */
        column: Coordinate;
      };
      body: Mark;
    }): Promise<
      OpenAPIResponses<{
        /** OK */
        200: {
          body: Status;
        };
        /** The provided parameters are incorrect */
        400: {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/board/{row}/{column}",
          method: "put",
          requestSchema: z.object({
            path: z.object({
              row: CoordinateSchema,
              column: CoordinateSchema,
            }),
            body: MarkSchema,
          }),
          responseSchema: {
            200: z.object({ body: StatusSchema }),
            400: z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };
}
