// deno-lint-ignore-file no-explicit-any
// This file was auto-generated by @brad-jones/open-api-client

import {
  type OpenAPIClientConfig,
  openAPIFetch,
  type OpenAPIResponsePromise,
  type OpenAPIResponses,
} from "jsr:@brad-jones/deno-net-open-api-client@0.2.5";
import { z } from "npm:zod@^4.1.12";

export type DataSetList = {
  total?: number;
  apis?: {
    /** To be used as a dataset parameter value */
    apiKey?: string;
    /** To be used as a version parameter value */
    apiVersionNumber?: string;
    /**
     * The URL describing the dataset's fields
     *
     * @format uri-reference
     */
    apiUrl?: string;
    /**
     * A URL to the API console for each API
     *
     * @format uri-reference
     */
    apiDocumentationUrl?: string;
  }[];
};

export const DataSetListSchema: z.ZodType<DataSetList> = z.object({
  total: z.number().int().optional(),
  apis: z.array(z.object({
    apiKey: z.string().optional(),
    apiVersionNumber: z.string().optional(),
    apiUrl: z.string().optional(),
    apiDocumentationUrl: z.string().optional(),
  })).optional(),
});

/**
 * API Client class with path-based access to all operations.
 * All methods are inline within the class.
 */
export class ApiClient {
  constructor(private readonly config: OpenAPIClientConfig) {}

  readonly "/" = {
    /**
     * List available data sets
     */
    get: (): OpenAPIResponsePromise<
      OpenAPIResponses<{
        /** Returns a list of data sets */
        200: {
          body: DataSetList;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/",
          method: "get",
          responseSchema: {
            200: z.object({ body: DataSetListSchema }),
          },
        },
      ) as any,
  };

  readonly "/{dataset}/{version}/fields" = {
    /**
     * Provides the general information about the API and the list of fields that can be used to query the dataset.
     *
     * This GET API returns the list of all the searchable field names that are in the oa_citations. Please see the 'fields' attribute which returns an array of field names. Each field or a combination of fields can be searched using the syntax options shown below.
     */
    get: (request: {
      path: {
        /** Name of the dataset. */
        dataset: string;
        /** Version of the dataset. */
        version: string;
      };
    }): OpenAPIResponsePromise<
      OpenAPIResponses<{
        /** The dataset API for the given version is found and it is accessible to consume. */
        200: {
          body: string;
        };
        /** The combination of dataset name and version is not found in the system or it is not published yet to be consumed by public. */
        404: {
          body: string;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/{dataset}/{version}/fields",
          method: "get",
          requestSchema: z.object({
            path: z.object({
              dataset: z.string(),
              version: z.string(),
            }),
          }),
          responseSchema: {
            200: z.object({ body: z.string() }),
            404: z.object({ body: z.string() }),
          },
        },
        request,
      ) as any,
  };

  readonly "/{dataset}/{version}/records" = {
    /**
     * Provides search capability for the data set with the given search criteria.
     *
     * This API is based on Solr/Lucene Search. The data is indexed using SOLR. This GET API returns the list of all the searchable field names that are in the Solr Index. Please see the 'fields' attribute which returns an array of field names. Each field or a combination of fields can be searched using the Solr/Lucene Syntax. Please refer https://lucene.apache.org/core/3_6_2/queryparsersyntax.html#Overview for the query syntax. List of field names that are searchable can be determined using above GET api.
     */
    post: (request: {
      path: {
        /** Version of the dataset. */
        version: string;
        /** Name of the dataset. In this case, the default value is oa_citations */
        dataset: string;
      };
      body: "WARN: application/json is the only supported content type";
    }): OpenAPIResponsePromise<
      OpenAPIResponses<{
        /** successful operation */
        200: {
          body: Record<string, Record<string, never>>[];
        };
        /** No matching record found for the given criteria. */
        404: {
          body: unknown;
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/{dataset}/{version}/records",
          method: "post",
          requestSchema: z.object({
            path: z.object({
              version: z.string().default("v1"),
              dataset: z.string().default("oa_citations"),
            }),
          }),
          responseSchema: {
            200: z.object({ body: z.array(z.record(z.string(), z.object({}))) }),
            404: z.object({ body: z.unknown() }),
          },
        },
        request,
      ) as any,
  };
}
