// deno-lint-ignore-file no-explicit-any
// This file was auto-generated by @brad-jones/open-api-client

import {
  type OpenAPIClientConfig,
  openAPIFetch,
  type OpenAPIResponses,
} from "jsr:@brad-jones/deno-net-open-api-client@0.2.1";

/**
 * API Client class with path-based access to all operations.
 * All methods are inline within the class.
 */
export class ApiClient {
  constructor(private readonly config: OpenAPIClientConfig) {}

  readonly "/count" = {
    get: (): Promise<
      OpenAPIResponses<{
        200: {
          body: {
            currentCount: number;
          };
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/count",
          method: "get",
        },
      ) as any,
  };

  readonly "/ping" = {
    get: (): Promise<
      OpenAPIResponses<{
        200: {
          body: {
            ping: string;
          };
        };
      }>
    > =>
      openAPIFetch(
        this.config,
        {
          path: "/ping",
          method: "get",
        },
      ) as any,
  };
}
