# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev
version: 3

dotenv: [".env"]
set: [pipefail]
shopt: [globstar]

tasks:
  build:
    cmds:
      - echo 'import { builder } from "./src/main.tsx"; await builder.writeOpenApiArtifacts();' | deno run -A -

  start:
    cmds:
      - deno run -A ./src/main.tsx

  watch:
    cmds:
      - >-
          deno run
          --watch=$(deno eval -p 'Deno.args.join(",")' ./**/*.{ts,tsx})
          --watch-exclude=deno.json
          --watch-exclude=src/client.ts
          -A ./src/main.tsx

  watch-hmr:
    cmds:
      - >-
          deno run
          --watch-hmr
          --watch-exclude=deno.json
          --watch-exclude=src/client.ts
          --no-clear-screen
          -A ./src/main.tsx
