on:
  workflow_call:
    inputs:
      project:
        description: The name of the cog project to publish
        type: string
        required: true

env:
  CI: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
      attestations: write
    steps:
      - name: ⬇️ Git Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: ⚙️ Install pixi env
        uses: prefix-dev/setup-pixi@v0.9.1
        with:
          pixi-version: v0.56.0
          activate-environment: true

      - name: Additional Environment Initialization
        run: task init

      - name: 🚀 Publish
        run: try-cog-bump.ts -p ${{ inputs.project }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
