on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  container:
    uses: ./.github/workflows/_publish.yaml
    secrets: inherit
    permissions:
      id-token: write
      contents: write
      packages: write
      attestations: write
    with:
      project: container

  configuration:
    needs: [container]
    uses: ./.github/workflows/_publish.yaml
    secrets: inherit
    permissions:
      id-token: write
      contents: write
      packages: write
      attestations: write
    with:
      project: configuration

  problem-details:
    needs: [configuration]
    uses: ./.github/workflows/_publish.yaml
    secrets: inherit
    permissions:
      id-token: write
      contents: write
      packages: write
      attestations: write
    with:
      project: problem-details

  http-context:
    needs: [problem-details]
    uses: ./.github/workflows/_publish.yaml
    secrets: inherit
    permissions:
      id-token: write
      contents: write
      packages: write
      attestations: write
    with:
      project: http-context

  logging:
    needs: [http-context]
    uses: ./.github/workflows/_publish.yaml
    secrets: inherit
    permissions:
      id-token: write
      contents: write
      packages: write
      attestations: write
    with:
      project: logging

  formatter:
    needs: [logging]
    uses: ./.github/workflows/_publish.yaml
    secrets: inherit
    permissions:
      id-token: write
      contents: write
      packages: write
      attestations: write
    with:
      project: formatter

  bundler:
    needs: [formatter]
    uses: ./.github/workflows/_publish.yaml
    secrets: inherit
    permissions:
      id-token: write
      contents: write
      packages: write
      attestations: write
    with:
      project: bundler

  islands:
    needs: [bundler]
    uses: ./.github/workflows/_publish.yaml
    secrets: inherit
    permissions:
      id-token: write
      contents: write
      packages: write
      attestations: write
    with:
      project: islands

  middleware:
    needs: [islands]
    uses: ./.github/workflows/_publish.yaml
    secrets: inherit
    permissions:
      id-token: write
      contents: write
      packages: write
      attestations: write
    with:
      project: middleware

  app-builder:
    needs: [middleware]
    uses: ./.github/workflows/_publish.yaml
    secrets: inherit
    permissions:
      id-token: write
      contents: write
      packages: write
      attestations: write
    with:
      project: app-builder
