on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  container:
    uses: ./.github/workflows/_publish.yaml
    secrets: inherit
    permissions:
      id-token: write
      contents: write
      packages: write
      attestations: write
    with:
      project: container

  app-builder:
    uses: ./.github/workflows/_publish.yaml
    secrets: inherit
    permissions:
      id-token: write
      contents: write
      packages: write
      attestations: write
    needs:
      - container
    with:
      project: app-builder
